### ISSUE TITLE
False detection

### ISSUE THREAD

**Issue by aravindvnair99** [KieronQuinn/TapTap#1]
Actions are triggered when notifications arrive with vibration. Otherwise works fine.

Steps to reproduce:

- Enable service
- Get a notification with vibration
- Action is triggered

**Comment by KieronQuinn** [comment]
This can't be solved unless I can find a way to allow sensitivity config. I'll leave it open for now, and this will become the master ticket for ideas of how to reduce it.

**Comment by janiksudo** [comment]
@aravindvnair99 mentioning your device would be helpful.

I am using a Pixel 4 XL, and this ist not the case for me. 
You have to remember that the TF models are only for Pixel 3 XL, Pixel 4 and 4 XL. If your device has similar proportions (and I guess the position of gyroscope/accelerometer within the device matters as well, it could be that the vibration motor is just very close in your device, or you are using a case that doesn't lay even on the table when vibrating, or or or), it should work okay, but otherwise there is no guarantee.

**Comment by aravindvnair99** [comment]
> @aravindvnair99 mentioning your device would be helpful.
> 
> I am using a Pixel 4 XL, and this ist not the case for me.
> You have to remember that the TF models are only for Pixel 3 XL, Pixel 4 and 4 XL. If your device has similar proportions (and I guess the position of gyroscope/accelerometer within the device matters as well, it could be that the vibration motor is just very close in your device, or you are using a case that doesn't lay even on the table when vibrating, or or or), it should work okay, but otherwise there is no guarantee.

@janiksudo I have a Xiaomi POCO F1 aka Xiaomi Pocophone F1. Your explanation makes perfect sense to me. My phone seemed most similar to the Pixel 3 XL, so I set the ML model to that. I don't face the issue often though. Just sometimes when the notifications with vibration come, it does trigger. And sometimes when I'm typing fast on the keyboard or keeping the phone down on the table quickly. In most cases, it doesn't happen. But it still does happen. Could be the position fine-tuning as you said.

**Comment by Martin5001** [comment]
Would it be possible to create custom tensor model for other devices? I think maybe we could record the data on our phones, flagging positive and negative triggers. (User opens data-gathering app and taps, shakes, puts down or moves the phone in different ways, then answers the question "Was this a double tap?" as yes or no to train the model.) Collecting enough false trigger data patterns would be crucial to prevent false detection.

**Comment by arunk140** [comment]
Could the Sensitivity Option be implemented by using the Confidence value from the prediction? I am not sure how well that would work. Will try to test that out.

**Comment by KieronQuinn** [comment]
Sensitivity added in 0.5 alpha
