### ISSUE TITLE
Activates on GBoard

### ISSUE THREAD

**Issue by stenbrin** [KieronQuinn/TapTap#105]
GBoard haptic keyboard activates it on Pixel 3a. No option for a gate on keyboard.

**Comment by KieronQuinn** [comment]
Add Gboard as an app gate

**Comment by stenbrin** [comment]
Gboard doesn't show up in apps list.

**Comment by KieronQuinn** [comment]
Looks like the app list is only showing launchable apps, so that's a bug. Enable the app icon in Gboard's settings and it will appear in the list as a temporary workaround.

**Comment by stenbrin** [comment]
Sorted. 👍😁
