### ISSUE TITLE
Using on redmi note 8 pro, app works properly (on pixel 3 xl device model other two dont work ).But when the ram is cleared it stops working even after the app is opened again and allowed to run in background

### ISSUE THREAD

**Issue by gokul1312** [KieronQuinn/TapTap#11]

**Comment by ChooTingFeng** [comment]
Try locking the app in Recent Apps / checkout dontkillmyapp for instructions to keep app alive

**Comment by OSMaxwell** [comment]
Same here with Xiaomi Mi 9.
Cleaning Cache or closing app stops the service.
Opening the App again doesn't help. (Reinstall required.)

**Comment by KieronQuinn** [comment]
Please try disabling battery optimisation in whatever way is normal for your device. Accessibility services should not be killed, but apparently OEMs don't care.
