### ISSUE TITLE
Export/Import or Backup/Restore settings

### ISSUE THREAD

**Issue by sharanvelu** [KieronQuinn/TapTap#112]
For most of the custom ROM users, they have to often wipe their data whenever they are trying new ROM or whenever the developer changes the device tree or even for  better experience.

So it would be helpful for user if there is an option to export and import settings such as actions and gates.

Recently i have to wipe my phone's data for new ROM, I experienced this one. So, i hope so others will.

**Comment by KieronQuinn** [comment]
Added in 0.10 beta.
