### ISSUE TITLE
Gesture not working

### ISSUE THREAD

**Issue by Natsu-Dragnel** [KieronQuinn/TapTap#114]
Gesture not working on OnePlus 3 A3003 with all Pixels (3XL, 4, 4XL) options, with case and without case.
App starts and works, but there is simply no reaction to the gesture. I tried tapping the entire area of the phone's back cover.
Changing other settings also does not give results.
OnePlus 3 A3003, Android 7.1.1, App v0.4.
Need more information?

This is duplucate of #17, because i can't re-open #17  issue

UPD: I'm update the app to v0.5, and the gesture still doesn't work at any level of sensitivity, and with case/without case, and with all Pixels (3XL, 4, 4XL). No reaction. All gates is off

**Comment by lividhen** [comment]
I am having this same issue, on sm-t350 (tab A 2015) android pie.

**Comment by Shadowspear123** [comment]
I have the same exact issue on a Galaxy S8 on Android Oreo.

**Comment by Martin5001** [comment]
Same on Galaxy J7 (I guess it's the TF model, so not sure if listing unsupported devices is any helpful.)

**Comment by S-Shen** [comment]
I'm able to trigger action on my 3T, but it's like only once or twice out of 10 tries. Fairly inconsistent. 

OnePlus 3T A3000
Lineage OS 17.1
v0,4 with device model Pixel 4. Battery optimization disabled

**Comment by Natsu-Dragnel** [comment]
> 
> 
> I'm able to trigger action on my 3T, but I have to be very deliberate with taps and it only works perhaps two or three times out of 10 tries.
> 
> OnePlus 3T A3000
> Lineage OS 17.1
> v0,4 with device model Pixel 4. Battery optimization disabled
> 
> Edit:
> Turning sensitivity up in v0.5 helps a bit, but still requires very deliberate slow tap.

in what area of the back did you manage to trigger the gesture? can you show it in the photo?

**Comment by S-Shen** [comment]
> 
> 
> > I'm able to trigger action on my 3T, but I have to be very deliberate with taps and it only works perhaps two or three times out of 10 tries.
> > OnePlus 3T A3000
> > Lineage OS 17.1
> > v0,4 with device model Pixel 4. Battery optimization disabled
> > Edit:
> > Turning sensitivity up in v0.5 helps a bit, but still requires very deliberate slow tap.
> 
> in what area of the back did you manage to trigger the gesture? can you show it in the photo?

Right below the OnePlus logo

**Comment by Natsu-Dragnel** [comment]
> Right below the OnePlus logo

hmmm, no reaction...

**Comment by KieronQuinn** [comment]
Now covered in #354, make sure to follow the steps and if it still doesn't work there's nothing I can do.
