### ISSUE TITLE
error when using the application 

### ISSUE THREAD

**Issue by 9000000** [KieronQuinn/TapTap#115]
If I'm using the selected application to skip the touch and when the notification bar is pulled down, the tap tap will no longer work.

**Comment by KieronQuinn** [comment]
I don't understand what you mean, could you explain in a bit more detail

**Comment by 9000000** [comment]
when the notification bar is pulled down, And back to playing the game, accidentally double-clicking, the screen turns off

![Screenshot_20200810-175151_Tap, Tap](https://user-images.githubusercontent.com/11648045/89775653-7cfca000-db32-11ea-9e73-eadb04ab78de.jpg)

**Comment by KieronQuinn** [comment]
The notification shade is SystemUI, if the system isn't telling the service that it's been closed (which it often doesn't, hence the inability to make a gate for that), it will still think SystemUI is in front and will not trigger that gate. This cannot be fixed.
