### ISSUE TITLE
Sensitivity setting please. Placing phone face-up on my desk is triggering Tap, Tap.

### ISSUE THREAD

**Issue by Logansfury** [KieronQuinn/TapTap#116]
Hello Kieron,

So far the Alpha 0.4 is running stable on both my SM-N960U1 w/Android Q10 and my SM-N960U w/Android 8.1.0. It continues function thru multiple reboots of devices and I have not had to uninstall/re-install to retain fuction as I did with previous build.

However, Sensitivity of the app seems hyper-acute. Merely gently placing the phone on a desk and sliding it back a few inches away from the edge is triggering Tap, Tap and firing my assigned Tasker reaction.

May we please have a Sensitivity setting to try to control this?

Thank you!

Logan

**Comment by KieronQuinn** [comment]
#1
