### ISSUE TITLE
Battery issues

### ISSUE THREAD

**Issue by shivangchopra22** [KieronQuinn/TapTap#122]
The app works perfectly, only issue is the battery drain. I've re enabled battery optimization for the app and noticed less battery drain when screen is off, but when the screen is on battery is draining a bit too fast and even charging is taking much more time (yes I've uninstalled the app and compared). 

I'm on redmi note 7 pro

**Comment by aravindvnair99** [comment]
@shivangchopra22 Duplicate of #86 Why not keep a common thread for battery issues than one for each device or person?

**Comment by shivangchopra22** [comment]
@aravindvnair99 yeah that's a better option, my bad sorry.
