### ISSUE TITLE
False triggering

### ISSUE THREAD

**Issue by Andriy2** [KieronQuinn/TapTap#123]
It's some feel, that on 0.4 more false triggers than on previous versions. 

Google Pixel 4
Android 11 Beta 3

Same on my friends:
Google Pixel 3XL
Android 10

**Comment by Andriy2** [comment]
And, maybe, if it possible, add some notification (?) when triggered to improve Machine Learning with some feedback (Is this Action was accidental or not?) for devices with ML component

**Comment by Andriy2** [comment]
Sorry, it sensativity was mentioned in #1, but war about notification for ML component?

**Comment by KieronQuinn** [comment]
Sensitivity is indeed in #1 and will be added soon. TensorFlow Lite does not support on-device training, so the idea of improving the ML is not possible in its current state.
