### ISSUE TITLE
Not working on Samsung Galaxy A20 (Android 10).

### ISSUE THREAD

**Issue by Salman7236** [KieronQuinn/TapTap#125]

**Comment by KieronQuinn** [comment]
More information please, state exactly what isn't working, what you have tried, etc.

**Comment by Salman7236** [comment]
Tried all kinds of actions with all gates opened using different device models at different sensitivity, disabled all kinds of battery optimizations and locked the app in memory. Still doesn't work.

**Comment by Salman7236** [comment]
I mainly want to turn on flashlight with the app. Only gate I enabled was the "during call" one. It doesn't work.
