### ISSUE TITLE
App detection not stable in landscape

### ISSUE THREAD

**Issue by Zeanon** [KieronQuinn/TapTap#135]
I just discovered, that if I have my phone in landscape mode(OnePlus 7t pro), the detection of the current app is probe to fail.
I tested it with different apps and the "falling through" for different actions does not always work.
E.g. if I have an action for WhatsApp and one for camera, as the second one, the camera action will not always launch, even if WhatsApp is open

**Comment by KieronQuinn** [comment]
The detection is using what's provided to the accessibility service, if the system is providing the wrong package I can't really do anything about that.

**Comment by Zeanon** [comment]
I also did some more testing on this, it seems, as if the standard OnePlus camera app is very strange, since it appears to somehow not be in proper landscape, even though it is in landscape, so it's definitely on op and not Tap tap :)
