### ISSUE TITLE
Not working on Redmi Note 5A Prime - LineageOS 14.1

### ISSUE THREAD

**Issue by kubalav** [KieronQuinn/TapTap#136]
Accessibility granted, battery optimization disabled. I tried all device models with high sensitivity. Action set to camera app. Gates on - Display off, On call.

Logcat:
[Logcat.txt](https://github.com/KieronQuinn/TapTap/files/5249159/Logcat.txt)

**Comment by KieronQuinn** [comment]
Please try again on the newer versions, they seem to be more reliable for others on Xiaomi devices

**Comment by kubalav** [comment]
Not working with 0.8b version. Double tap, triple tap no action performed.

**Comment by kubalav** [comment]
0.8.1 Beta Logcat
[logcat_09-21-2020_08-02-39.txt](https://github.com/KieronQuinn/TapTap/files/5253656/logcat_09-21-2020_08-02-39.txt)

**Comment by kubalav** [comment]
I use LOS 17 now.
