### ISSUE TITLE
Camera opens in limited functionality mode if "lauch camera" selected

### ISSUE THREAD

**Issue by MuseCat77** [KieronQuinn/TapTap#14]
![Screenshot_20200731-121828](https://user-images.githubusercontent.com/66839978/89022125-31741600-d32a-11ea-8e90-d9802521b867.jpg)
If I select camera as app it's ok:
![Screenshot_20200731-122018](https://user-images.githubusercontent.com/66839978/89022187-48b30380-d32a-11ea-87c0-cd62011d0a1b.jpg)
Also, if I select camera as app, I need to unlock my phone before I can shoot something. It would be nice if I could choose secure camera activity as on the shortcut on the lockscreen

**Comment by KieronQuinn** [comment]
Added in #37 which is part of the 0.2 alpha release out now
