### ISSUE TITLE
Reachability not working properly

### ISSUE THREAD

**Issue by Zeanon** [KieronQuinn/TapTap#141]
When you deactivate the reachability action, by triggering it again, the Google app opens
(OnePlus 7T pro)

**Comment by KieronQuinn** [comment]
The option isn't actually opening anything other than itself when run, so this bug is not caused by Tap, Tap

**Comment by Zeanon** [comment]
Ok,

I just tested it again, it did not occur anymore, which is quite interesting, since it first occurred on 2 different phones, one OnePlus and one Sony :)
