### ISSUE TITLE
Separate screen 

### ISSUE THREAD

**Issue by yuepokman** [KieronQuinn/TapTap#148]
Separate screen wont work on the main screen, but it doesnt trigger the second move I setted

**Comment by 4shutosh** [comment]
Split Screen does not work on Home Screen anyway. You need to be on an app screen to trigger the split-screen feature.
The list works as a priority queue the actions listed below will only be triggered if the action/actions above them are already completed / already running / are unavailable.
Split screen is a toggle (ON/OFF) action so it's always available and any actions below it won't work.

**Comment by KieronQuinn** [comment]
What @4shutosh said is correct, this is working as intended.
