### ISSUE TITLE
How to use tasker with Taptap?

### ISSUE THREAD

**Issue by linwhitehat** [KieronQuinn/TapTap#151]
When I add the Tasker task in advanced, it told me that "can't find the named task".
![image](https://user-images.githubusercontent.com/20349381/89749019-a7ca0280-daf8-11ea-8cc7-7a1249276401.png)

**Comment by shivangchopra22** [comment]
Check the name of the task again, or set up a profile with that task and the event as tap tap (can be found in plugins)
