### ISSUE TITLE
Kill switch

### ISSUE THREAD

**Issue by sharanvelu** [KieronQuinn/TapTap#152]
Needs a kill switch or enable disable toggle.
Sometimes there is a need to turn off the feature.
In such case, I am turning off the accessibility service or force stopping the app.

But a toggle within the app would be very convenient.

**Comment by sharanvelu** [comment]
Additional : Schedule for turning on and turning off the feature.

**Comment by 4shutosh** [comment]
I think the accessibility menu is itself on the top of the app to make it work as a toggle.
The gates are quite sufficient for making tap, tap work in specific conditions and I don't find any use of scheduling the feature but can surely be considered in future.

**Comment by Martin5001** [comment]
> In such case, I am turning off the accessibility service or force stopping the app.
But a toggle within the app would be very convenient.

I would prefer using a quick setting toggle in the notification area.

**Comment by shivangchopra22** [comment]
Can be made using tasker probably

**Comment by avarayr** [comment]
Go to **Phone Settings** -- **Accessibility** -- **TapTap** -- **TapTap Shortcut**.

Then, by pressing both of your **volume keys** you can toggle TapTap on or off.

**Comment by sharanvelu** [comment]
> Go to **Phone Settings** -- **Accessibility** -- **TapTap** -- **TapTap Shortcut**.
> 
> Then, by pressing both of your **volume keys** you can toggle TapTap on or off.

That's a good suggestion. But not everyone's volume keys are in perfect condition. Even though that was a work around, a switch within the app would be great.

**Comment by KieronQuinn** [comment]
Added in 0.7 Alpha.
