### ISSUE TITLE
Sensitivity(bug)

### ISSUE THREAD

**Issue by Oi-Baba** [KieronQuinn/TapTap#155]
So the sensitivity works pretty well most of the time but then it stops.
Reopening the app makes the actions stop working and I have to re add the action for it to work.
But I am getting fewer unintentional triggers.

I know this is experimental atm so its fine.

**Comment by KieronQuinn** [comment]
You will need to provide much more information than this for it to be a valid issue. Please give info about what happens, like if the gesture stops working entirely, the conditions when that happens and device information. Re-open the issue with this information once you've got it.
