### ISSUE TITLE
No funciona en mi A30s

### ISSUE THREAD

**Issue by Valen-372** [KieronQuinn/TapTap#157]
Tengo un Samsung Galaxy A30s con android 10 One UI 2.0 y no me funciona, pruebo tocando la parte trasera sin la funda por si ese es el problema pero sigue sin responder, desde que lo descargue funcionó una sola vez, las demás veces se activa solo.

**Comment by ZonaRMR** [comment]
Desactiva el ahorro de batería en esta app, al igual que puedes bloquear la app para que el sistema no mate su proceso en segundo plano.

**Comment by Valen-372** [comment]
Hola buen dia, ya tengo hecho eso y sigue sin funcionar solo se prende con
toques accidentales o solo sin tocar nada, sinceramente nose que hacer. Si
tienen alguna solución se los voy a agradecer. Desde ya, muchas gracias!!!

**Comment by KieronQuinn** [comment]
Disabling battery optimisation has fixed it for you if you are getting a response after that. Change the sensitivity to fix your other problem.
