### ISSUE TITLE
Lock Screen action not working

### ISSUE THREAD

**Issue by Abijith-Suresh** [KieronQuinn/TapTap#16]
I use a Samsung galaxy m30s. No matter what I do the lock screen action doesn't seem to work. Everything else I have tested seems to work fine

**Comment by KieronQuinn** [comment]
What Android version is this on?

**Comment by Abijith-Suresh** [comment]
It is on Android 10. I've also noticed that the recents function also seems
broken.

**Comment by KieronQuinn** [comment]
Fixed in 0.10 beta
