### ISSUE TITLE
Hide the multitask background card

### ISSUE THREAD

**Issue by rkdawn** [KieronQuinn/TapTap#160]
Hope to add a hidden multitask background card, so we can show this application not in the background, but still running

**Comment by 4shutosh** [comment]
It is supposed to be running in the background what device are you using?

**Comment by rqtingfeng** [comment]
> It is supposed to be running in the background what device are you using?

Our device is not a native or native-like system, it is deeply customized, manufacturers in order to suppress rogue software, clear the background card, will directly clear the task

**Comment by 4shutosh** [comment]
Please provide some details of the operating system and device

**Comment by rqtingfeng** [comment]
> Please provide some details of the operating system and device

![Screenshot_2020-08-15-14-35-43-1878073691](https://user-images.githubusercontent.com/42829652/90306951-cd924580-df04-11ea-8d75-a06723fbfa89.png)

**Comment by KieronQuinn** [comment]
It's a stupid thing OEMs do, clearing from recents = killing the task. It's not really for security, it's to save memory. This might be an option in the future, I'd like to have it off by default though.

**Comment by rkdawn** [comment]
May be you don't know Chinese software ecosystem, it is not that specification of Google play market, without a unified push service, rogue software before android O it is hard to pin, back-end services often associated startup, often software 1 with multiple software starts, in the absence of the user agrees to the resident, causing huge waste of power, this is the manufacturer for many years has been solved, but the pros and cons, native or native system in task CARDS hidden, still can continue to run, and the custom system is can't hide away, so the domestic many individual developers, they will be changed slightly in the software, To adapt to the domestic environment, they adhere to the Android Green Convention, which is worthy of my admiration compared to many large software companies``

**Comment by KieronQuinn** [comment]
Western OEMs do it to, it's not just a Chinese thing.

**Comment by rkdawn** [comment]
This is not clear. What I feel is a big gap. Just like this app, the phone I use can only be put on the card, while this system can run in the background all the time without worrying about it
![3c6948d6e318ebe3](https://user-images.githubusercontent.com/42829652/90577236-e5164a80-e1f2-11ea-9884-70d9a877a9e6.png)

**Comment by KieronQuinn** [comment]
Please test if this is an issue still with the  changes in 0.7 Alpha, if it is I'll look at adding an option to hide the recents task too.

**Comment by rkdawn** [comment]
It still doesn't work, custom UI killing background is very serious, a lot of our solution is to make magISK module, into the system application
![Screenshot_2020-09-10-09-28-36-975_com coolapk market](https://user-images.githubusercontent.com/42829652/92671397-bc442980-f348-11ea-9453-79354b02e277.jpg)

**Comment by rkdawn** [comment]
It still doesn't work, custom UI killing background is very serious, a lot of our solution is to make magisk module, into the system application
![Screenshot_2020-09-10-09-28-36-975_com coolapk market](https://user-images.githubusercontent.com/42829652/92671584-3f657f80-f349-11ea-842d-a693c9e97d67.jpg)
我们这采用的大多数是这种方式，不占用系统卡片。
![IMG_20200910_093705](https://user-images.githubusercontent.com/42829652/92671625-57d59a00-f349-11ea-8f8b-db70838afb50.jpg)

**Comment by KieronQuinn** [comment]
Closing as this now sits under the #354 issue (though it didn't at the time so you were fine making it).
