### ISSUE TITLE
Always activates when extending/collapse popsocket - custom tap count?

### ISSUE THREAD

**Issue by wallentx** [KieronQuinn/TapTap#164]
This is awesome, and I use this to activate my flashlight. I have a Pixel 3 XL with the Google cloth case, so taps don't transfer well through the case, but they work perfect when I tap on my popsocket.

When I extend or collapse my popsocket, I've noticed that it activates my flashlight a high percentage of the time.

Is it possible to set a custom tap count for activation for popsocket compatibility?

Or should I fork and have "taptaptaptap" branch 😁

**Comment by KieronQuinn** [comment]
Reducing the sensitivity should fix this.
