### ISSUE TITLE
双击选择唤起语音助手未成功/wake up the system voice assistant doesn't success

### ISSUE THREAD

**Issue by icemytime** [KieronQuinn/TapTap#165]
当我选择双击唤起系统语音助手时，没有唤醒系统的语音助手，唤醒的是QQ浏览器的，然后会打开它的语音功能。（手机是荣耀V30PRO系统是magic 3.0)
谢谢.
When I choose to wake up the system voice assistant,the "tap tap"app doesn't wake up that,but it will wake up the QQ browser and open it's voice assistant.(My phone is honor V30 pro and the system is magic 3.0) 
THANK YOU.

**Comment by KieronQuinn** [comment]
The assistant action runs the system default assistant app. If you would like to change that, you can do so in the system settings.
