### ISSUE TITLE
Taptap

### ISSUE THREAD

**Issue by josem19498** [KieronQuinn/TapTap#166]
I downloaded on my note 10 plus and it works ok but needs to be improved it doesn't work all the time and I have to  keep tapping behind my phone until it takes the screen shot also I sign it to launch the camera and seems not to work only to take the screen shot

**Comment by KieronQuinn** [comment]
Please read the actions help dialog to know how they work - if the order is Screenshot then Camera, the camera action will never be run as the screenshot will always succeed. 
If you are having trouble tapping, increase the sensitivity and try a different model
