### ISSUE TITLE
How to install it in my phone?

### ISSUE THREAD

**Issue by Zakaria55** [KieronQuinn/TapTap#168]
Hi everyone,

In fact, I have downloaded the ZIP to my PC and copied it to my phone, but I don't know how to install it!

Could you help me, please?
Thanks in advance.

**Comment by popuguy4ik** [comment]
@Zakaria55 Maybe you downloaded sources?

**Comment by KieronQuinn** [comment]
Install the latest APK from the releases page.

**Comment by Zakaria55** [comment]
Thanks for your answer @KieronQuinn, but I didn't find the APK in the "release" folder.

**Comment by KieronQuinn** [comment]
The GitHub releases page, not the release folder: https://github.com/KieronQuinn/TapTap/releases

**Comment by Zakaria55** [comment]
Ah, ok. Thanks a lot.
