### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Natsu-Dragnel** [KieronQuinn/TapTap#17]
This app not working on OnePlus 3 with all Pixels options

**Comment by ritamdas47** [comment]
Mine one is working for some time then ot stops again

**Comment by KieronQuinn** [comment]
You will need to provide much more information than this for it to be a valid issue. Please give info about what happens, like if the gesture stops working entirely, the conditions when that happens and full device information. Re-open the issue with this information once you've got it.

**Comment by Natsu-Dragnel** [comment]
Gesture not working on OnePlus 3 A3003 with all Pixels (3XL, 4, 4XL) options, with case and without case.
App starts and works, but there is simply no reaction to the gesture. I tried tapping the entire area of the phone's back cover.
Changing other settings also does not give results.
OnePlus 3 A3003, Android 7.1.1

Re-open pls.
