### ISSUE TITLE
Add a gate:run only when there is music playing

### ISSUE THREAD

**Issue by Gluneklairo** [KieronQuinn/TapTap#172]
![Screenshot_20200822-154058~2](https://user-images.githubusercontent.com/65527723/90951517-4574e880-e48e-11ea-936f-95f78ab70858.png)
I think these two gates are the same. 

I hope it can run only when there is music playing so that I won't start playing a song  unintentionally.

**Comment by arkon** [comment]
From what I can vaguely remember when working on Phonograph a few years ago, it doesn't quite set up the MediaSession correctly, so I suspect that's why it's not working properly.

Retro's based on Phonograph, so it inherits most of its issues.

**Comment by KieronQuinn** [comment]
Label has been fixed in 0.7 Alpha. Please report issues with specific apps to their developers as stated above.
