### ISSUE TITLE
[Bug] Enabling table gate leads to crash

### ISSUE THREAD

**Issue by aravindvnair99** [KieronQuinn/TapTap#173]
Enabling the `Table` gate ends up in an app crash. The app hangs for a while and then force closes in [0.6.1_alpha](https://github.com/KieronQuinn/TapTap/releases/tag/0.6.1_alpha)

After it stops responding, if I click "wait" and then reopen the app, I can see it's disabled but added to list. And then enabling it seems to be fine. I guess there's some bug in click in "Add gate" to add to list.

Device: Xiaomi POCO F1
Android: 10

**Comment by KieronQuinn** [comment]
This should be fixed in 0.7 Alpha.

**Comment by aravindvnair99** [comment]
> This should be fixed in 0.7 Alpha.

@KieronQuinn Yes, I can confirm the same. Closing this issue. 👍
