### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by bhaskar452** [KieronQuinn/TapTap#178]
Hay, I want to tell you something about alpha 0.6.1 . 
The previous version (alpha 0.5) is working properly on MIUI(but have some issues like battary drainage,key board gate is not working properly etc.). But in this new version this is not working properly. When I installed the alpha 0.6.1, at first for few minutes it works normaly but after some time this was stop working. I tried several thing but nothing happened. Then I uninstall and reinstall it; At that time the same problam was happened again. Then I uninstall it and install 0.5 version. 
This is works nice but drains so much battary.
Think youtube vanced drains approx 4% in day and it drains approx 1% in approx 1 hour.
This is the mejor issue I am facing with it.
Please try to fix those in the next version.
Hope you will understand my problems.
Thank you.

**Comment by bhaskar452** [comment]
I have already applied what @busybox11 said. But it is working on v0.5 not on v0.6.1
But the most suffering thing is it's battery issue.
And I am sending some screen shots that you can understand that what permissions I gave for it.![Screenshot_2020-08-23-22-43-01-770_com.miui.securitycenter.jpg](https://user-images.githubusercontent.com/69151104/90984393-370ff500-e592-11ea-802a-7a338a8d2871.jpg)![Screenshot_2020-08-23-22-43-09-427_com.miui.powerkeeper.jpg](https://user-images.githubusercontent.com/69151104/90984397-4000c680-e592-11ea-9dbf-1b1aa7779cf6.jpg)![Screenshot_2020-08-23-22-43-23-729_com.miui.securitycenter.jpg](https://user-images.githubusercontent.com/69151104/90984403-47c06b00-e592-11ea-8d02-b0cf35b05872.jpg)

**Comment by KieronQuinn** [comment]
There have been no changes that would affect battery usage or running in the background between 0.5 and 0.6(.1). What you are seeing as a "difference" is totally coincidental.

**Comment by bhaskar452** [comment]
I didn't mean that the battary issue of 0.6.1 is much grater than 0.5 
I said there is a battary issue on 0.5 not on 0.6.1
And the problam what I am facing with 0.6.1 is it's not working. this i already told you before.
I don't know any thing about 0.6.1 without it's not working issue.because of I didn't use it properly that I don't kown about 0.6.1 problams.
Hope you will understand
