### ISSUE TITLE
Issue founded sometimes it works sometimes it dont

### ISSUE THREAD

**Issue by Shadab4khan** [KieronQuinn/TapTap#18]
Yeah there is an issue sometime the app works sometimes dont when i keep it for a while long time then it stops working

**Comment by KieronQuinn** [comment]
You will need to provide much more information than this for it to be a valid issue. Please give info about what happens, like if the gesture stops working entirely, the conditions when that happens and device information. Re-open the issue with this information once you've got it.

**Comment by Shadab4khan** [comment]
Gesture stops working entirely when i lock and unlock my phone for a longer
time
device information - realme X2 Pro indian unit

**Comment by KieronQuinn** [comment]
OEM issue then, I can't do anything about it if your firmware decides to kill an accessibility service. Try disabling battery optimisation for Tap, Tap.

**Comment by joaomgcd** [comment]
Just a thought, you might direct users here when they complaint about stuff like this: https://dontkillmyapp.com/
