### ISSUE TITLE
Can't scroll upwards.  

### ISSUE THREAD

**Issue by tetarwal** [KieronQuinn/TapTap#181]
All options are not visible in the menu. I mean can't scroll up to see "accessibility service" option. Device is Asus Zenfone Max Pro M1 running n android pie. ![Screenshot_20200824-205942.png](https://user-images.githubusercontent.com/43969568/91064684-35573780-e64d-11ea-95c1-ee78909dfdcd.png)

**Comment by tetarwal** [comment]
Just wanted to let you know about the bug. Thanks for the great app.

**Comment by KieronQuinn** [comment]
#52
