### ISSUE TITLE
Back and Home actions fail on some ROMs

### ISSUE THREAD

**Issue by sr1canskhsia** [KieronQuinn/TapTap#182]
Some ROMs use the new SOURCE_NAVIGATION_BAR as input. This caused the Back/Home actions to fail.

[See this commit for details](https://github.com/ResurrectionRemix/android_frameworks_base/commit/504c4b269c7e61ffbc3bc07b2db29114225f413c)

**Comment by KieronQuinn** [comment]
There's nothing I can do to fix this, the app uses the accessibility service inputs rather than KeyEvent. If ROMs decide not to support that, that's their issue.
