### ISSUE TITLE
Fix for getting killed in the background/Bug

### ISSUE THREAD

**Issue by Zeanon** [KieronQuinn/TapTap#183]
First of all I have an idea, which is rather simple stupid, to mitigate the problem of the app getting killed in the background: add an option for a persistent notification, since the app seems to get killed even though battery optimization is disabled on my OnePlus 7T Pro.

On the other hand I discovered something interesting:
I have one action launching the cam app(as launch app) and after that to launch gcam.
If I activate the gesture, when the phone is in the locked lock screen, the cam app is open when I unlock it, but if I activate it again, it won't switch to gcam.
Is there an option for a gate to detect, whether the phone is in the lock screen/locked?

**Comment by tjsuominen** [comment]
I have OP Nord and this "killed in the bg" is pain in the... well you know... It's impacting buch of my apps I use on Windows (e.g. WhatsApp and Yourphone app) that require same wifi connection than laptop - the moment lockscreen (screen is locked) is on, the moment Wifi connection seems to drop and I need to re-activate my phone to be able use those apps on my PC.

Related: yes, this bg killing is impacting for TapTap on OP Nord as well...

**Comment by Zeanon** [comment]
For me persistent notification seems to make "Your Phone" quite stable :)

**Comment by KieronQuinn** [comment]
Persistent notifications do not apply to accessibility services, as they are not foreground services which is what the requirement is for.
