### ISSUE TITLE
Facing issue with gates in 6.1

### ISSUE THREAD

**Issue by SanOtaku09** [KieronQuinn/TapTap#184]
I am facing i a very weird problem 
I am currently using tap tap to open a lyric app and had
put a music playing gate on that action. 

and also turned on display off gate and call gate (main gates)

So app should behave like this :- when i tap it should open app only if music is playing and display is turned on and it does for sometime but 
After some hours that app doesn't open when i tap even if music is playing , display is on and tap tap app is running in foreground. 

But when i go to main gates and enable display on gate and disable it again action starts working. 

Also device optimization is off so tap tap is always running in background.
I wasn't facing this problem on version 5 but is facing now on 6.1 don't know about 6 never tried that one.

Please help.

![Screenshot_20200825-153158_Tap, Tap](https://user-images.githubusercontent.com/61407097/91161281-30939180-e6e8-11ea-864d-3a7fa1138dd1.jpg)
![Screenshot_20200825-153154_Tap, Tap](https://user-images.githubusercontent.com/61407097/91161304-38ebcc80-e6e8-11ea-99aa-31a002727e58.jpg)
![Screenshot_20200825-153204_Tap, Tap](https://user-images.githubusercontent.com/61407097/91161305-39846300-e6e8-11ea-85b4-ad314c688960.jpg)

**Comment by KieronQuinn** [comment]
Please see if this still happens in the more recent versions, especially with the added options around split service.

**Comment by SanOtaku09** [comment]
Ok
