### ISSUE TITLE
The app works, but rarely, and with a delay.  Samsung Galaxy A6 Android 10

### ISSUE THREAD

**Issue by RamBamBooOff** [KieronQuinn/TapTap#187]
Please, I really love this app.  But it doesn't work well on my smartphone.  It rarely responds to tapping and is most often delayed.  Otherwise, everything is super
API 29
Arm-v7a
Let me know if that's not enough

**Comment by RamBamBooOff** [comment]
I tested the app with a selection of all devices and maximum sensitivity.  Battery saver is disabled.  The application is locked in multitasking.  It really works with delays: recently I tapped on my smartphone many times, after about a minute it began to continuously play actions

**Comment by KieronQuinn** [comment]
The new update should help with the delay, but I can't do anything about it rarely triggering on your device. I can't train models so we're left with what it came with.

**Comment by RamBamBooOff** [comment]
Thanks,
