### ISSUE TITLE
Stops working

### ISSUE THREAD

**Issue by TheOakLord** [KieronQuinn/TapTap#190]
I am running Android 10 on OnePlus 6t version 10.3.5 rooted with magisk 20.4 and the app completely stops working after I disable the 'display off" gate. I am forced to reinstall it else it doesn't work. I tried force stoping and clearing data without success. Not sure if this is because I rooted or the app itself.

Edit: Also realized the assistant gesture stops working after 1 use

**Comment by Oi-Baba** [comment]
try disabling the accessibility service and turning it on again, that's what I'm doing for now.

**Comment by KieronQuinn** [comment]
Please try with the new update, specifically trying one or both of the new advanced options.

**Comment by KieronQuinn** [comment]
Now covered by #354, make sure you have followed all the steps and if it still doesn't work there's nothing I can do.
