### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Oi-Baba** [KieronQuinn/TapTap#192]
Didn't know what title to put in.

Samsung Galaxy M21 OneUI Core 2.0

So there are 3 bugs

The sensitivity setting stops working after a while, so even if I have the sensitivity set very low, light taps trigger actions.
Fixing this just needs me to readjust the slider(like move it a bit higher or lower and then move it back to the preferred position).
I don't think there's any specific trigger for this, it just happens after a while.
(This was there in v5)

So I have it setup to open flashlight when the screen is off, now this works the first few times after the screen is off and after a while it stops working, it's not like taptap completely stops working, if I unlock the screen the actions work normally and when the screen is locked we go back to it working the first few times and then stopping.

If I leave the phone untouched for hours(overnight in my case) taptap stops working completely, but its strange as other apps say habithub is able to work properly and send me notifications(it doesn't have any sort of persistent notification).
I could only get it working again by disabling the accessibility service and turning it on again.
(This wasn't there in v5)

![1](https://user-images.githubusercontent.com/69052158/91591314-62bc2200-e97a-11ea-8b9d-9fda0b4d65fa.jpg)

![2](https://user-images.githubusercontent.com/69052158/91591427-8bdcb280-e97a-11ea-95d7-6c94bc95afae.jpg)

**Comment by Z7AL3G37VZ7** [comment]
I'm having the same issues with 6.1 as I leave the phone untouched for too long it stops working completely then have too toggle the gates display off/on both for it to work again. Also the sensitivity stops working at random. As I only use the flash light while the screen is off, I rolled back too version 0.5 as I don't have any issues.

**Comment by KieronQuinn** [comment]
Please try with the new update, specifically trying one or both of the new advanced options.

**Comment by Oi-Baba** [comment]
> 
> 
> Please try with the new update, specifically trying one or both of the new advanced options.

So things are better in 0.7.1 (kind of)

Actions are triggered way faster now.

Taptap doesn't stop working anymore overnight with and without split service now (I had kept the auto restart option turned on so I don't know if that's the reason, I didn't test without it.
The sensitivity also doesn't stop working.
However, taptap does stop working after a while after turning off the screen like before and works again after turning on the screen.

There's a new issue now, taptap goes crazy at times, the actions are triggered multiple times, sometimes two, sometimes 3 and sometimes it just goes haywire. I Couldn't find any reason for this. When this happens, the killswitch stops working too like it doesn't matter if it's turned on or off. Turning off the accessibility service manually and turning it back on also doesn't fix this. The only way I could make it go back was by force stopping taptap and then opening it again and re enabling the service or restarting the phone.

**Comment by KieronQuinn** [comment]
Are you using the advanced option to restart the service?

**Comment by Oi-Baba** [comment]
> 
> 
> Are you using the advanced option to restart the service?

Yes I had that turned on, I'll try without it

**Comment by Jalilimm** [comment]
Galaxy A-71 / Although I removed the voice assistant action, every time I double tap it opens Bixby. For example, I set a screenshot action for Instagram, I double tap and it takes a screenshot and then opens Bixby! The interesting part though is my default voice assistant is Google not Bixby!!!

**Comment by Oi-Baba** [comment]
> Are you using the advanced option to restart the service?

So I tried without enabling auto restart in advanced settings and I'm getting the same results, don't know why it isn't any different.

**Comment by KieronQuinn** [comment]
I made some changes to the service in 0.8 Beta that may fix this, please try that

**Comment by Oi-Baba** [comment]
> 
> 
> I made some changes to the service in 0.8 Beta that may fix this, please try that

Things are better. With auto restart turned on, I've only had to manually restart the service a few times.

But actions are still triggered multiple times every now and then.

The sensitivity stays fine.

Using split service doesn't make any noticeable difference.

I didn't try the three tap gesture much.

**Comment by Oi-Baba** [comment]
So with the .9 update the app keeps working even after keeping the phone at standby for a long time after turnig on auto restart.

But the app did trigger actions multiple times a couple of times, I turned off split services and it's been 2 days since it did that again.

And btw love the new tutorial, it's pretty good.

And what's the second service for?

**Comment by KieronQuinn** [comment]
Not a clue what would cause some actions to trigger but some not when the screen is off. You're not blocking wake locks or anything are you?

**Comment by Oi-Baba** [comment]
> Not a clue what would cause some actions to trigger but some not when the screen is off. You're not blocking wake locks or anything are you?

Nope, maybe it's just oneui

**Comment by Oi-Baba** [comment]
Ok man the app is unsuable for me now, the app just keep repeating actions and this is the 5th time it's happening since yesterday. I tried with and without split services and auto restart

**Comment by KieronQuinn** [comment]
Hopefully this should be fixed in 0.10 beta with the rewrite, please ping me if it isn't and I'll reopen and look at it again.

**Comment by Oi-Baba** [comment]
> Hopefully this should be fixed in 0.10 beta with the rewrite, please ping me if it isn't and I'll reopen and look at it again.

Hey man, so the issue where the app stops responding when the screen turns off is still there and I think it's just because of oneui.

Now about the gesture sensitivity being lost, so if I don't enable the auto restart option the app stops working after a while and the sensitivity setting stops working after a long time too, so I tried disabling the app and enabling it(from the toggle) and guess what the sensitivity setting wasn't working( like before setting it gain works for a while).

The multi trigger bug hasn't occured till now
