### ISSUE TITLE
Support for Wear OS?

### ISSUE THREAD

**Issue by vojtapolasek** [KieronQuinn/TapTap#193]
Would it be possible to implement this for wear OS? So that I would double tap on my watch and it would do something? My idea is to have a specific app launched when the screen is off. To explain; I am blind and Apple Watch have a feature which tells you time through vibration when you double tap on them. This could be maybe done with your app? At least the activation part, the vibration app already exists. Thank you.

**Comment by tegutistgut** [comment]
Im not a programmer but I think that it would be very hard to implement this in a smartwatch.

**Comment by tegutistgut** [comment]
Im not a programmer but I think that it would be very hard to implement this in a smartwatch.

**Comment by KieronQuinn** [comment]
I looked more into the feasibility of this for 1.0 and have decided that it would simply use the CPU too much, and a number of watches don't actually have the required hardware anyway. Perhaps Google will add official support using the low power mode on the Pixel Watch.
