### ISSUE TITLE
Feature addition

### ISSUE THREAD

**Issue by bhaskar452** [KieronQuinn/TapTap#195]
Add a feature to "tap to wake device" while "lock screen to tap device" is enabled.
I mean at a time both of the gestures will working.

And if you can add a other feature then you can add three/triple tap gesture.(twice tap and trice tap both will work at a same time)

And I have a quarry - do you have any 
telegram group or channel? if you have, please send me the link.

**Comment by KieronQuinn** [comment]
Triple tap was added in 0.8 Beta, as well as Lock Device overriding the wake feedback (which I think is what you meant?)
