### ISSUE TITLE
Tasker freezes after few hours when I use Tasker intent

### ISSUE THREAD

**Issue by grm18** [KieronQuinn/TapTap#198]
When I use Tasker intent, Tasker app freezes after few hours and I have to force close Tasker.I'm using oneplus 5T stock Android 10 non root. 
Regards

**Comment by KieronQuinn** [comment]
@joaomgcd any idea what might be causing this?

**Comment by joaomgcd** [comment]
Hi. Can you clarify what you mean by "When I use Tasker intent"? Thanks in advance.

**Comment by grm18** [comment]
> Hi. Can you clarify what you mean by "When I use Tasker intent"? Thanks in advance.

Hi Jao, I use tap tap through taaker event. I notice that Tasker  hangs frequently. If I do not use tap tap through tasker, issue is not there

Regards

**Comment by joaomgcd** [comment]
Is the task that you're running maybe what's blocking?

**Comment by grm18** [comment]
> Is the task that you're running maybe what's blocking?

Hi Jao,

I'm running some sunp5 tasks3 like opening apps based to double or triple tap and orientation of the phone. I have sent you the log where I started debug when the issue again came up. I have mailed through grmohan1808@gmail.com
net.dinglisch.android.taskerm version 5.9.3; flavor: market; Source "com.android.vending"; BuildTime 2020-08-04 20:27


OS Buid ONEPLUS A5010_43_200513
OS Code 29
OS Target 28
Device ONEPLUS A5010
Manufacturer OnePlus
Product OnePlus5T

User report: tasker hangs frequently

Files:
https://drive.google.com/file/d/1ZYmCIleXtvLZuD9fJLvHO2h_7vRt9me7/view 


Regards

**Comment by joaomgcd** [comment]
Thank you. Seems like something is running over and over in a loop on your setup. Will respond there. I guess this can be closed since it doesn't seem related to TapTap.

**Comment by KieronQuinn** [comment]
Thanks for the help @joaomgcd and @grm18
