### ISSUE TITLE
Doesn't work on my Samsung a20e 

### ISSUE THREAD

**Issue by mrgionny** [KieronQuinn/TapTap#199]
I Have activated the double tap, but doesn't work

**Comment by KieronQuinn** [comment]
You need to provide much more information than that. Does it not work at all, no matter where and how hard you tap? What models have you tried? Have you tried adjusting the sensitivity?

**Comment by mrgionny** [comment]
I tried this app on the Samsung a20e and the double tap works rarely south
the maximum sensibility. I wait a reply...

Il Mar 1 Set 2020, 22:36 Kieron Quinn <notifications@github.com> ha scritto:

**Comment by Jacky3103** [comment]
I have the same problem with my samsung a7 2018 (android 10). I tried the last version of Tap tap (alpha 0.6.1) and I also tried with different levels of sensibility. I tried to tap everywhere on the phone and with different intensity, but I have the same result. The tap tap function starts more frequently when the phone is in a pocket (or when I use the keyboard) than when I try to activate it.

**Comment by KieronQuinn** [comment]
If the tap is working in a single position, then it's working as well as it can do. Try changing the models, otherwise there's nothing that I can do as I can't train models.

**Comment by mrgionny** [comment]
I download the latest beta version 0.8 and i try It but it works a bit,
after the installation, on my a20e, but after, it doesn't work....

Il Mer 9 Set 2020, 22:38 Kieron Quinn <notifications@github.com> ha scritto:

**Comment by KieronQuinn** [comment]
If it worked once, it's being killed by the system. Try changing some of the advanced options to stop that.
