### ISSUE TITLE
Feature: double tap to touch screen

### ISSUE THREAD

**Issue by mauri870** [KieronQuinn/TapTap#203]
When using any google cardboard compatible VR device you can use double tap to touch the screen if you do not have  magnets in place. This would be an awesome adition alongside a gate to only work when an app is fullscreen or VR mode.

**Comment by creeper6530** [comment]
I'd personally like it too

**Comment by vpguru** [comment]
I too like this feature.. sometimes easy to execute when our phone is on table

**Comment by mauri870** [comment]
So I finally decided to implement the suggestion that I made two years ago. 

Any feedback will be appreciated and looking forward to have this feature available to users.
