### ISSUE TITLE
Lifecycle Bugs

### ISSUE THREAD

**Issue by FFXV-alphaX-ReSoFa01** [KieronQuinn/TapTap#206]
Although the Taptap is growing and has long way to go .
Developers, you Do Really Are Amazing .
I love this app .

There're some problems I found when it was actived for a while .
I'm not sure how many models have these little bugs .
So I organize a few key points on here .

The sensitivity action event stops working after a while, even if I readjust the slider of sensitivity set , no action reflect anymore .
There's no any specific trigger for this, it just happens after a while .

And I have setup to play/pause music when the screen off.
Now the action runs the first few times after display off and after a while it stops working, it's not  TapTap fully stopped .
When you unlock the device, the action works usually and you turn device lock again , it goes back work at the first few times but  stopping immediately. Also it's happened when I leave the phone untouched for hours . (such like overnight )
TapTap working completes stopped .
The method of solution now I found to get it works again only by disabling the accessibility service and turning on again . But it soon stops again . 
BTW , the developer options shown the service still alive in the background but there's no clear reason why no action is triggered .

Model Type : ASUS ZenFone 5z 
CPU : s845
RAM : 6GB
System : android 10 ( Zen UI )
![Screenshot_20200905-205633317.png](https://user-images.githubusercontent.com/70799274/92305613-7b9c8700-efbb-11ea-9866-7fd267a7d6c3.png)![Screenshot_20200905-205651016.png](https://user-images.githubusercontent.com/70799274/92305615-7dfee100-efbb-11ea-8e7a-388979be954f.png)![Screenshot_20200905-205657773.png](https://user-images.githubusercontent.com/70799274/92305620-8525ef00-efbb-11ea-8d9c-bcdc878435d0.png)![Screenshot_20200905-205704044.png](https://user-images.githubusercontent.com/70799274/92305621-87884900-efbb-11ea-96a2-12fe7ad882bc.png)![Screenshot_20200905-205715060.png](https://user-images.githubusercontent.com/70799274/92305624-89520c80-efbb-11ea-9749-54596c45a506.png)![Screenshot_20200904-214213755.png](https://user-images.githubusercontent.com/70799274/92305639-b1417000-efbb-11ea-9c70-6b0a0f32af1c.png)![Screenshot_20200904-215434723.png](https://user-images.githubusercontent.com/70799274/92305642-c1594f80-efbb-11ea-803a-e8e4cd9b8272.png)![Screenshot_20200904-214213755.png](https://user-images.githubusercontent.com/70799274/92305669-e51c9580-efbb-11ea-9ace-c30022fcff84.png)![Screenshot_20200904-214241403.png](https://user-images.githubusercontent.com/70799274/92305677-f36ab180-efbb-11ea-8a87-ae4502559041.png)

**Comment by Oi-Baba** [comment]
I've got pretty much the same issues

#192

**Comment by FFXV-alphaX-ReSoFa01** [comment]
Thanks for your kind reminder .
It seems different oem roms and model types have quite similar problems .
Cheers !

**Comment by FFXV-alphaX-ReSoFa01** [comment]
> I've got pretty much the same issues
> 
> #192 

Thanks for your kind reminder .
It seems different oem roms and model types have quite similar problems .
Cheers !

**Comment by KieronQuinn** [comment]
As above, see other issue
