### ISSUE TITLE
Background Check App(suggestion)

### ISSUE THREAD

**Issue by Oi-Baba** [KieronQuinn/TapTap#207]
So some apps use another small application that kinda acts as a background checker. I recall you replying to a bug that accessibility services can't utilise persistent notification or other stuffs that a foreground app can use but these two apps(applock and aodnotify) both use accessibility service and they haven't failed to work.

I found these in the developer settings(pic)

Is this something that can be  implimented?

![20200906_215542](https://user-images.githubusercontent.com/69052158/92330368-f03ef680-f08b-11ea-8743-ecfaea75c327.jpg)

**Comment by KieronQuinn** [comment]
The accessibility services in these apps won't be using foreground notifications - because they don't work. They'll be using two separate services, like I implemented in 0.7 Alpha. This therefore is now resolved as much as it can be, please try the update.
