### ISSUE TITLE
Play pause action doesn't work normally after a while

### ISSUE THREAD

**Issue by rahim21** [KieronQuinn/TapTap#208]
Sometimes it skips tracks rather than play/pause 
And sometimes it plays and then pauses by itself.

When I clear app's data it works normally but this issue comes back again after a while

Also the service gets killed a lot ( didn't face this issue in previous versions).

galaxy A50, android 10
App is set to Not optimised

**Comment by KieronQuinn** [comment]
The music actions are simply passed  to the system, what they do is entirely out of this app's control.
