### ISSUE TITLE
Mui-ify Shortcut open panel

### ISSUE THREAD

**Issue by KrystalEbron** [KieronQuinn/TapTap#209]
Hey, I really love the concept of this app. The first thing I thought was now I dont have to worry about losing my mui-ify panel functionality when I enable full navigation gestures. I have been having issues when I'm on my home screen on my Samsung galaxy s10e. Sometimes it doesn't come up at all or takes a long time.

**Comment by KieronQuinn** [comment]
The delay after going home is imposed by the system. There's nothing I can do to speed it up or stop it from happening.
