### ISSUE TITLE
Can add more than one of each gate

### ISSUE THREAD

**Issue by shtraus12** [KieronQuinn/TapTap#21]
There is possibility to add two, three an more of each gate. If only one of these gates activated, gesture won't work.

P.S. Also I can help you to do Russian localisation, if you need it.
![image](https://user-images.githubusercontent.com/34423521/89037541-5925a700-d347-11ea-9d2a-c685eb83839d.png)

**Comment by KieronQuinn** [comment]
This is intended, it's to allow for as many gates that have customisation as possible. You can also remove gates, so there needs to be a way to add them back. I may add a filter to prevent multiple of the same non-configurable gate however.

**Comment by shtraus12** [comment]
> I may add a filter to prevent multiple of the same non-configurable gate however.

I think, this will make app better.

Best regards
