### ISSUE TITLE
No response while screen is off (Android 11)

### ISSUE THREAD

**Issue by EricWM612** [KieronQuinn/TapTap#212]
In using a Pixel 3a, and I have tried the new advanced options before submitting this report. I'm using the flashlight action, but I tested with the assistant action too. TapTap works fine on the lock screen and in normal use, but not with the screen off. I was thinking this may have to do with Android 11's new privacy settings?

**Comment by KieronQuinn** [comment]
Just checking, you have disabled the screen off gate right?

**Comment by EricWM612** [comment]
Oh come on, I thought I had checked everything 😅. That was the problem all along. Sorry for that waste of time, and thanks for the help!
