### ISSUE TITLE
Multiple Gates not works

### ISSUE THREAD

**Issue by Fenixs8973** [KieronQuinn/TapTap#214]
When adding multiple restrictions, only the first one works
Samsung Galaxy A50, Android 10:) 
Tap, tap 7.1

**Comment by Fenixs8973** [comment]
Device Wake-up doesn't work
Disabling gestures when the screen is off is disabled

**Comment by KieronQuinn** [comment]
Could you please post some screenshots of your configuration so I can try to reproduce it, thanks

**Comment by Fenixs8973** [comment]
![Screenshot_20200910-204013_Tap, Tap](https://user-images.githubusercontent.com/61942811/92774170-df50f680-f3a5-11ea-9991-0cbe1dfb74dc.jpg)

The top two(Russian)

**Comment by KieronQuinn** [comment]
It will run the first action that matches those conditions, so in your case the home button will be pressed all the time, as the device is on (and most of the time no music will be playing)

I would guess what you want is the following:
- Back action at the top, with the keyboard condition (will only be run when the keyboard is open)
- Volume down action second, with the screen off or music playing conditions
- Home action third, as it should be run most of the time with those conditions. 

As a general rule, put the actions whose conditions are met the most at the bottom, and least at the top. 

I see you have a fourth too, so adjust as necessary, putting it at the top if its condition is met the least amount of time.

I tested this exact setup on my phone and it works fine. Keyboard closes when gesture is run when it's open, volume goes down if music is playing, device goes home in other scenarios.

**Comment by Fenixs8973** [comment]
In other words, the action is performed if one of the conditions is met?

**Comment by Fenixs8973** [comment]
> It will run the first action that matches those conditions, so in your case the home button will be pressed all the time, as the device is on (and most of the time no music will be playing)

In other words, the action is performed if one of the conditions is met?

**Comment by KieronQuinn** [comment]
> > It will run the first action that matches those conditions, so in your case the home button will be pressed all the time, as the device is on (and most of the time no music will be playing)
> 
> In other words, the action is performed if one of the conditions is met?

Yes, that is how the conditions work.

**Comment by Fenixs8973** [comment]
Yeah, got it. In this case it would be great if you added a function where all the conditions had to be met to perform the action
