### ISSUE TITLE
Add the "menu" button to the actions

### ISSUE THREAD

**Issue by Kortiego** [KieronQuinn/TapTap#219]
Add the "menu" button to the actions. It can really improve full gesture usage on the clear android 10-11. Cause back gesture conflicts with gamburger menu gesture. And it can really improve the ux for many users.

**Comment by KieronQuinn** [comment]
As in tap the hamburger menu? There's no global action for that.

**Comment by Kortiego** [comment]
Ok. It is sad. But it can be definetly possibly realised. Just tested the first app in the store which correctly using menu button in different apps. Maybe you will find the way to realise this feature in the analogy of this app. Here is the working app -https://play.google.com/store/apps/details?id=jettoast.menubutton&hl=en_US

**Comment by KieronQuinn** [comment]
That's the overflow menu, not the hamburger menu. Either way, neither of them are supported natively in Accessibility Service (the options are: Back, Home, Recents, Notifications, Quick Settings, Power Menu, Toggle Split Screen and Screenshot). 

However, it might be possible with some hackery to get it to work on some (but not all) apps. I'll look into it.

**Comment by KieronQuinn** [comment]
https://streamable.com/ucvyzd
Far from perfect, it is literally just tapping at [25,{statusBarHeight+25] so will also trigger back buttons or whatever else may be at that position (so maybe using triple tap 👀 would be more suitable, or at the very least using conditions to lock it to certain apps), but it does work.

Will be in the next release.

**Comment by KieronQuinn** [comment]
Added in 0.8 Beta.
