### ISSUE TITLE
More then just on the back

### ISSUE THREAD

**Issue by MKCOOL142** [KieronQuinn/TapTap#223]
I don't know how hard it is to add but I'd like to see a feature that also allows double taps on the front (with a turned off screen), I assume it not that hard to add but I have no clue how this app works in the first place.

 The use case would be f.e. when the phone is on a table or something  else laying flat that you could wake the screen, pause/play music, skip songs or enable the flashlight at night.

This would be especially cool for phones without double tap to wake where apps that just block out the screen require a OLED screen.

I hope this gets added, kind regards!
Luis k.

**Comment by KieronQuinn** [comment]
Unfortunately the ML model does not appear to support this and I can't change that.
