### ISSUE TITLE
"Play next audio" skips 2 times

### ISSUE THREAD

**Issue by kutlaykizil** [KieronQuinn/TapTap#224]
I've cleared app data and set it up again, issue still exists.

If someone try repeating the same problem on their phone I'm sure it would be helpful.

v0.7.1
Phone: Xiaomi mi A3
Player: YouTube music

**Comment by KieronQuinn** [comment]
Do any of the other actions run twice or is it just that one?

**Comment by kutlaykizil** [comment]
Sorry for responding late turns out github app doesn't send a notification for responds.

Anyway, I only tried "play next audio" and "play/pause" and only next audio was repeating itself. Just now I've tried again and all functions are triggers once as intended.

I don't know what caused this issue earlier, I've tried clearing app's storage and cache and reinstalled it before creating the issue. So It looks like caused by something other than app (maybe sensor error idk).

I'll close this issue and start using the "play next" action from now on, If I find something new I might open it again.
