### ISSUE TITLE
Actions for Torch and Screenshot.

### ISSUE THREAD

**Issue by seriousabin** [KieronQuinn/TapTap#226]
I use two actions.One for Torch when Display is off and One for Screenshot when Display is on.

Whenever i use Action for Torch the Display suddenly gets turned on and it automatically tries taking screenshots.I use Pin so whenever i try to take screenshot on pin it automatically blocks it and gives a warning.That is how i know it is trying to take screenshots.

I am on Realme 6 (Android 10 Realme UI).

**Comment by KieronQuinn** [comment]
Disable the wake device feedback option.
