### ISSUE TITLE
Action for Google assistant.

### ISSUE THREAD

**Issue by seriousabin** [KieronQuinn/TapTap#227]
It does not launch default assistant when Headset turned on.Rather Screenshot action takes over.
Note:I do not use Battery saver.

Realme 6 (Android 10 Realme UI)

**Comment by KieronQuinn** [comment]
Please post a screenshot of your config.

**Comment by seriousabin** [comment]
> Please post a screenshot of your config.

Sorry for posting this issue.Fault on my part i think.Sorry for wasting your time.
![Uploading Screenshot_2020-09-18-19-50-02-82.jpg…]()
