### ISSUE TITLE
Multiple Actions exceuted on same condition!

### ISSUE THREAD

**Issue by viveknerle** [KieronQuinn/TapTap#231]
Hello,

**Device used - One Plus 7
Android Version -  10
Build - Oxygen OS 10.3.4.GM57AA
Issue found in v0.7.1**

**Description** - 
•I added 2 actions(show power menu & volume panel) with same condition(when display on), you can find in screenshot. 
And both actions executed..(**As per description provided in app they should not executed... But this what I need it, I can save my phone button life**)

•Then I checked some cases like changing sequence, and found that if volume panel kept at first position, then power menu action not executed, my observation on this is power menu and volume panels displayed in different layered. Because when at first test, clicking possible to power menu first and then after that close volume panel accessible.

• Same thing I checked with notification panel and volume panel and power menu. Getting sort of behaviour.

•Then after some hours app stopped responding to taps. So I cleaned data and catche and app worked as per description in app (single action at a time for condition in ascending order).

Attaching screenshots.. within testing I added and removed some Actions like flash on display off, pocket mode off like..

**Note - screenshot added with action and result.**

![Screenshot_20200919-001756](https://user-images.githubusercontent.com/12202329/93661413-3ecd9700-fa75-11ea-89f8-b17146f43ef0.jpg)
![Screenshot_20200918-194324](https://user-images.githubusercontent.com/12202329/93661415-42611e00-fa75-11ea-9a8a-d5f9c519a716.jpg)

**Comment by KieronQuinn** [comment]
Reboot, this has been reported multiple times.

**Comment by viveknerle** [comment]
But this should work as feature if no special reason behind single action on unique condition.

Or atleast need new Action which will popup power menu and volume panel simultaneously.

**Comment by KieronQuinn** [comment]
If you're wanting to combine actions, you're beyond the scope of this app. Use Tasker and the Tasker Event action to add more complex actions.
