### ISSUE TITLE
It always opens the Google assistant.

### ISSUE THREAD

**Issue by tegutistgut** [KieronQuinn/TapTap#237]
Hello,
Device: Samsung Galaxy A51 (SM-A515F/DSN) unlocked, OneUI 2.1, September update.

Tap tap version: 0.8 Beta

Issue: whatever action I give the app, it always opens the Google assistant, when I tap 2 or 3 times the backside of my phone.

Solution: idk/unsolved for me

Edit: could we please have the option, to change the language in the app?

Thanks in advance

**Comment by KieronQuinn** [comment]
Reboot your phone.
