### ISSUE TITLE
App crashes if triple tap has no actions 

### ISSUE THREAD

**Issue by kutlaykizil** [KieronQuinn/TapTap#238]
If triple tap is active and has no action assigned, and double tap has an action, triple tapping crashes the app.

This does not happen while no action is assigned to double tap either. (So basically nothing is set for both 2&3 taps)

Easiest solution seems like disabling the 3 tap automatically if no action is assigned to it.

-----
Xiaomi mi a3 & v0.8

**Comment by KieronQuinn** [comment]
Confirmed, will fix

**Comment by KieronQuinn** [comment]
Fixed in 0.8.1 Beta.
