### ISSUE TITLE
Kill switch (issue)

### ISSUE THREAD

**Issue by sharanvelu** [KieronQuinn/TapTap#239]
Gestures still works even if the **enable gesture** button is turned off.

**Comment by KieronQuinn** [comment]
Fixed in 0.8.1 Beta hopefully.

**Comment by sharanvelu** [comment]
Yes it works.

**Comment by sharanvelu** [comment]
It seems to work fine just after installing the update.
But after few hours, the gestures are working even if the **Enable Gestures** switch is turned off.

**Comment by KieronQuinn** [comment]
Please try rebooting your device.
