### ISSUE TITLE
Enable gesture only to work when tapping on rear fingerprint sensor

### ISSUE THREAD

**Issue by nik048** [KieronQuinn/TapTap#245]
Hi, great tool. 

Is it possible to fire the gesture action only when tapping on the fingerprint sensor.

Useful for phones with rear fingerprint sensor, will reduce the ghost/mistake taps.

Thanks

**Comment by KieronQuinn** [comment]
Fingerprint gestures can only be detected by one app at a time (so adding this would remove the user's ability to use other swipe apps), and take too long after the tap is recognised to be reliable for this, so no this is not feasible.
