### ISSUE TITLE
Split screen showing incorrectly.

### ISSUE THREAD

**Issue by 0Jumpero** [KieronQuinn/TapTap#246]
When I double tap with the split screen action assigned, it splits the screen but the lower one is moved down like this: 
![Screenshot_20200922-130130](https://user-images.githubusercontent.com/53096124/93874527-cc0e2700-fcd3-11ea-9fc5-8c20f55ef33b.png)
And this is how it should look (when I do it manually without Tap tap):
![Screenshot_20200922-130341](https://user-images.githubusercontent.com/53096124/93874706-10012c00-fcd4-11ea-8b9c-869752af5ec4.png)

**Comment by KieronQuinn** [comment]
The service simply triggers the system split screen. There's nothing I can pass to it, nothing I can launch automatically, no parameters. Only launch. 

I spent hours getting Reachability working (the other split screen option), which uses an extremely hacky method and requires control of the app that's launched into split screen to work, so is not a solution for normal split screen.

In short, can't fix this.
