### ISSUE TITLE
[Bug] TapTap service dies in OP Nord (Android 10)

### ISSUE THREAD

**Issue by tjsuominen** [KieronQuinn/TapTap#250]
Hi,

Every once in a while (on daily basis) the TapTap service just "dies" (aka does not respond to double or triple taps). De-and re-enabling the service makes it functional again.

The app is configured NOT to go to sleep mode.

Anything can be done?

**Comment by KieronQuinn** [comment]
Disable the OnePlus battery optimisation for the app (it's separate to the Android one, in the app info), switch to split services. If that doesn't work, nothing I can do about it.

**Comment by tjsuominen** [comment]
Switched to split services, has been working since 👍

**Comment by KieronQuinn** [comment]
Good to know, thanks.
