### ISSUE TITLE
Delay for first open. 

### ISSUE THREAD

**Issue by nivibilla** [KieronQuinn/TapTap#251]
Hi, 

First of all great app btw. It works pretty much perfectly on my OnePlus 6. Still figuring out the exact sensitivity I need. But just a small issue I've found is that it takes a while for WhatsApp(my chosen action) to open up on first try. There is like a 2 second delay. I'm on the latest beta. 

To replicate it, just go to recents and clear all apps. Including the action app. And then tap twice . The app should pop up in a out 3 seconds. After it is open the following taps are pretty much instantaneous.

Also an idea for better battery. Maybe add the option for people to have the service turned off if the screen is off? Not sure if this is the same as the gate though.

**Comment by KieronQuinn** [comment]
You are seeing the 5 second 'rule', which is built into Android. After going home or using the home button/gesture, a service cannot start an app for 5 seconds. There is no workaround for this.

**Comment by nivibilla** [comment]
Ah ok nw.
