### ISSUE TITLE
Couple of enhancements I thought of.

### ISSUE THREAD

**Issue by nivibilla** [KieronQuinn/TapTap#252]
I think it'll be great to have a Morse code Easter egg. Or something along those lines. So for example. A specific sequence of taps followed by approximate gaps can unlock the device?

But a simple one I use a lot is switching to the previous app. Historically this is assigned to double tapping the recents button. But I think itll be great to have this functionality here.

Thanks

**Comment by KieronQuinn** [comment]
Switching apps is already being looked into, and an easter egg may come soon (but it won't be morse code, triple tap is as much as I'm doing and it's not built to monitor times precisely enough for that).

As for unlocking the device, that is very hard to implement in a userspace app and is way out of scope for this app.

**Comment by nivibilla** [comment]
I understand, I've solved the problem of switching apps by using tasker. But a built in function would be useful for people who don't have experience with takser.
