### ISSUE TITLE
Chrome Tab Preview

### ISSUE THREAD

**Issue by RodrigoJPBraga** [KieronQuinn/TapTap#255]
When enabling accessibility option for tap tap, google chrome no longer display a preview of the tabs opened. Dont know if the problem is from google chrome or not.

![Screenshot_20200924-111846_Chrome](https://user-images.githubusercontent.com/71822126/94132907-dd803c00-fe57-11ea-894f-1a97a1ce4c46.png)

![Screenshot_20200924-111905_Chrome](https://user-images.githubusercontent.com/71822126/94132926-e40eb380-fe57-11ea-812c-74b9f52f4daf.png)

**Comment by KieronQuinn** [comment]
This is not caused directly by Tap, Tap, and has been discussed on the XDA thread three times in the last three days. Chrome settings > Accessibility > Disable simplified content & tabs.
