### ISSUE TITLE
Google Assistant Fails to Work with Screen Off

### ISSUE THREAD

**Issue by OneplusUser** [KieronQuinn/TapTap#257]
On my OnePlus 6 when I trigger the gesture the phone clearly makes the noise that Google assistant has been activated however after logging in with face unlock ( I believe this is part of the issue) the Google assistant screen must have been dismissed meaning it fails to appear once I reach the home screen. Alternatively if I trigger it with my voice on screen off the Google assistant appears on the lock screen and then if needed asks for me to log in and it continues to work. I was wondering whether there is either a fix or alternatively whether there could be an included optional time delay (or waiting until phone is on trigger/ queuing up actions) to trigger the actions to overcome this barrier. Thanks

**Comment by KieronQuinn** [comment]
Whether an app is able to be displayed above the lock screen is controlled by the app and can't be overridden unfortunately.

**Comment by OneplusUser** [comment]
I managed to work around it anyway by triggering a Nova Launcher activity to launch the Google assistant so it is working well now.
