### ISSUE TITLE
Taking 5 screenshots at once when used for long time and with combined with triple tap in redmi 9 t pro

### ISSUE THREAD

**Issue by bhaskarvilles** [KieronQuinn/TapTap#267]
Taking 5 screenshots at once when used for long time and with combined with triple tap in redmi 9 t pro.

**Comment by KieronQuinn** [comment]
Please try rebooting to see if it persists. What version is this on too?

**Comment by bhaskarvilles** [comment]
Tried after rebooting , failed in mi k 20 pro indian version.

**Comment by KieronQuinn** [comment]
Which version?

**Comment by bhaskarvilles** [comment]
Miui 12 (android 10)

**Comment by KieronQuinn** [comment]
No, which _app_ version.

**Comment by bhaskarvilles** [comment]
0.8 beta

**Comment by bhaskarvilles** [comment]
I have changed device now so i can't test now sorry brother.
