### ISSUE TITLE
"Screen on" gate

### ISSUE THREAD

**Issue by Oi-Baba** [KieronQuinn/TapTap#27]
It would be cool to have more gates.
Here's my suggestion : not allowing actions when screen is tuned on

I'd read that you might implement gates for specific actions so I think this would go well together,
like in my case I want it to take screenshots when the screen is on and toggle flashlight when the screen is off

**Comment by KieronQuinn** [comment]
Renamed to make it easier to find in the future

**Comment by KieronQuinn** [comment]
Added in #37 which is part of the 0.2 alpha release out now
