### ISSUE TITLE
[Feature Request] Add "Flashlight On" or "Flashlight Off" as a requirement?

### ISSUE THREAD

**Issue by dustintinsley** [KieronQuinn/TapTap#270]
I believe adding "Flashlight On" as a requirement could be beneficial. I am looking for a way to turn off the flashlight if it is already on and the screen is on. However, with the way it is now, you can only toggle the flashlight. Just an idea that could be useful to myself and others.....

**Comment by KieronQuinn** [comment]
The way the flashlight code works in the app would mean if this were done it would only be able to know if the flashlight is on *and* the app turned it on. It doesn't have a concept of other apps turning it on, so if this were added it would make it very easy to get out of sync. 

As others said on the xda thread this also would add more complexity to the app and is therefore out of scope. For more complex options like this, use Tasker.
