### ISSUE TITLE
Device size models are not clear

### ISSUE THREAD

**Issue by Sominemo** [KieronQuinn/TapTap#273]
I got confused by what "Small", "Medium" and "Largest" are, since every person has own constraints for these definitions. What about adding some explainer to what average sizes should be for each model to consider which one is better to use.
Thank you.

**Comment by KieronQuinn** [comment]
This change was made due to a large amount of people saying the opposite. All including the models did was confuse people into thinking it only worked on those devices and wouldn't on theirs.
