### ISSUE TITLE
[feature suggest] triger different action by tap on different side

### ISSUE THREAD

**Issue by rhjdvsgsgks** [KieronQuinn/TapTap#274]
is it possible to detect which side of device has been tapped, that can be used to trigger different actions. such as double tap right side of phone to back, and left side to open recent activity

**Comment by KieronQuinn** [comment]
This is not possible as the models do not support it. I left this open as there were signs in the Android 11 code that Google were working on this, but now the feature has been released without it, it's not something I can add.
