### ISSUE TITLE
incorrect display of text

### ISSUE THREAD

**Issue by andonlya** [KieronQuinn/TapTap#276]
name="setting_actions_double"
name="setting_actions_triple"
Russian language
![Screenshot_20201010-103042.jpg](https://user-images.githubusercontent.com/50917209/95648991-fb9a9d00-0ae3-11eb-8dbc-fd4ba4e12fad.jpg)![Screenshot_20201010-103004.jpg](https://user-images.githubusercontent.com/50917209/95648992-fdfcf700-0ae3-11eb-9d93-8a1087799875.jpg)

**Comment by KieronQuinn** [comment]
Doing some house cleaning: Was this fixed in the rebuild?

**Comment by VladWinner** [comment]
> Doing some house cleaning: Was this fixed in the rebuild?

Yes

**Comment by KieronQuinn** [comment]
Great, thanks!
