### ISSUE TITLE
Flashlight running intermittently

### ISSUE THREAD

**Issue by legolasdimir** [KieronQuinn/TapTap#278]
I'm trying to use the double tap gesture to run flashlight with the screen off. Galaxy s10 e Android 10. It runs for a little bit and then doesn't seem to work anymore I've tried fiddling with the sensitivity but I can't seem to get it to work reliably. I don't even have a very thick case on my phone so I don't know if this is a bug or an issue but any advice I could get would be helpful

**Comment by KieronQuinn** [comment]
Please try with a different action to see if it's an action issue or a flashlight issue. Also make sure you have disabled battery optimisation as shown in the setup.

**Comment by legolasdimir** [comment]
Optimization has been disabled. I have tried it with the default assistant
action as well as the flashlight action with the same results on the
default sensitivity. Also the requirement that the display is off was part
of what I had set for both attempts

**Comment by KieronQuinn** [comment]
If none of the actions are working, something is killing the app. I can't do anything about that, follow the steps here: https://dontkillmyapp.com/samsung

**Comment by Oi-Baba** [comment]
> If none of the actions are working, something is killing the app. I can't do anything about that, follow the steps here: https://dontkillmyapp.com/samsung

Nope, I've got the same issue.
For me the app isn't closed, it keeps working after turning on the screen, and after turning off the screen it again keeps working for a while and then stops till I turn on the screen.
#192
