### ISSUE TITLE
Open notifications action sometimes sends back button press instead

### ISSUE THREAD

**Issue by SBence** [KieronQuinn/TapTap#281]
Cannot reproduce reliably but happens quite often. Using a OnePlus 7T Pro.

**Comment by KieronQuinn** [comment]
This happens due to there being no API to know when the drawer is open. If you close the drawer manually and then do the gesture again before the window changes (by a navigation in the app), it will run back instead as it has no way of knowing you've closed the drawer. There is no fix for this.
