### ISSUE TITLE
Download now button does not work when app detects an update.

### ISSUE THREAD

**Issue by S10MC2015** [KieronQuinn/TapTap#282]
Even though it tries to open download link using browser it doesn't work.

This may be due to mitigations against no user interaction downloads.

**Comment by KieronQuinn** [comment]
Which browser are you using? I've never had this issue on Chrome.

**Comment by S10MC2015** [comment]
This is with chrome

**Comment by KieronQuinn** [comment]
Unable to reproduce in that case. The download link opens a blank page, but with a popup at the bottom to download the APK. That is the mitigation, it doesn't just not download a file.

**Comment by d4rn0tt** [comment]
I get this issue too, it opens up a weblink then closes

**Comment by KieronQuinn** [comment]
Fixed in 0.10 beta, though you won't see a difference until the next release obviously. APK is on the releases page if you need to download it manually.
