### ISSUE TITLE
An option to temporarily stop the app when battery saver is on

### ISSUE THREAD

**Issue by spectkiller** [KieronQuinn/TapTap#283]
its no brainer that tap tap use extra battery life and i think at battery saver mode, it can afford to be stop till i plug it into charging.

**Comment by KieronQuinn** [comment]
This was actually implemented in 1.1, but I forgot to close it. Adding the Battery Saver gate will disable the service when it is enabled, just so long as it's the first gate encountered (see the battery & optimisation Wiki page). Add it as your first gate and it should meet your requirements.
