### ISSUE TITLE
MIUI not launch app

### ISSUE THREAD

**Issue by PL7963** [KieronQuinn/TapTap#284]
I can only launch app while in the app.
MIUI 12.0.2 Global Xiaomi Mi9
Accessories ON
Battery optimization disable

**Comment by LaughingCoffinLawl** [comment]
Same issue here.
Redmi Note 8 Pro.
MIUI 12.0.1
Everything is on, i even tried to disable MIUI optomization.

**Comment by Reda96R** [comment]
Same thing with my redmi note 8

**Comment by PL7963** [comment]
I fixed that. If you have same issue with MIUI please enable display pop up window while running in the background.
![Screenshot_2020-10-26-20-06-17-641_com.miui.securitycenter.jpg](https://user-images.githubusercontent.com/44529370/97170641-01bc9900-17c7-11eb-9c16-d083dee1c730.jpg)
