### ISSUE TITLE
Change sensitivity per Gesture

### ISSUE THREAD

**Issue by IPWright83** [KieronQuinn/TapTap#285]
It would be really nice to be able to change the sensitivity for different gestures/actions, to help deal with false positives etc. For example:

I've got a gesture for when the screen is locked/lock screen to turn on the flashlight. It normally takes a couple of attempts. 

I also have a gesture to lock screen on double tap, this frequently triggers by accident when I'm typing on the keyboard (6x writing this issue).

I'd really like to tone down the sensitivity when trying, but not make it harder when locked.

**Comment by KieronQuinn** [comment]
Not possible. The sensitivity is actually how much noise the model is filtering out, so you'd need to have a whole service running for every single action and gesture for this to work. That would take a massive amount of battery and CPU usage.
