### ISSUE TITLE
Wrong Assistant App being Opened

### ISSUE THREAD

**Issue by GoodarzMehr** [KieronQuinn/TapTap#286]
Hi,

First of all, I am really impressed by the app, it works really well and the interface is really nice.

I did encounter a problem however. Running it on Galaxy S20+, when I set it to wake up the Assistant it woke up Bixby, instead of my default Google Assistant. I did check to make sure that my default was indeed Google Assistant.

I would appreciate it if you could look into this. Thanks!

**Comment by KieronQuinn** [comment]
The app is simply starting Intent.ACTION_VOICE_COMMAND. If you have a different assistant app set to that, or if Bixby overrides that somehow, there is nothing I can do about it. Try clearing the defaults of Bixby and seeing if it prompts you to select one instead.
