### ISSUE TITLE
Very sensitive when typing - false positives

### ISSUE THREAD

**Issue by abusarlihah** [KieronQuinn/TapTap#288]
Pixel 5 - haptic feels stronger than my Pixel 4. In any case. When messaging the double tap for flashlight is triggered on and off several times.

**Comment by KieronQuinn** [comment]
Enable the Keyboard gate.

**Comment by abusarlihah** [comment]
Tried that sir.
I've disabled accessibility services for now. Was going a little haywire.
Even when I removed the flashlight as an action. It was still initiating it.

Love the thought of the app. Will be looking closely at it!
