### ISSUE TITLE
Malfunctioning on Pixel 4a running Android 11

### ISSUE THREAD

**Issue by waterlava** [KieronQuinn/TapTap#289]

**Comment by waterlava** [comment]
I have turned the sensitivity down to low, but I constantly activate Tap Tap without meaning to. This often happens when typing or tapping the screen repeatedly, but my sensitivity is now so low that I can barely activate the gesture by doing an actual back tap.

**Comment by KieronQuinn** [comment]
Which device size are you using?

**Comment by waterlava** [comment]
"Smallest" as my screen is only 0.11 inches bigger than the pixel 4.

**Comment by KieronQuinn** [comment]
Try the other two sizes see if that makes a difference.

**Comment by jjmoeller** [comment]
I am finding the same.  I have tried all of the sizes and the Advanced - Custom sensitivity.  It doesn't seem that any of them have any real affect.  Let me know if I can provide any more details.  I like the app but it is currently unusable on this device.

**Comment by waterlava** [comment]
Ok so I've done a little testing and I think medium works best. It still activates by accident, but it's much less often. It would still be nice to have the option to turn off the gesture when the keyboard is active or something.
Thanks for all the great work you've put into this app so far!
