### ISSUE TITLE
Works only for the 1st time after installation.

### ISSUE THREAD

**Issue by nandans98** [KieronQuinn/TapTap#29]
Downloaded on Poco f1, The app works only for the 1st time after installing it and once its closed and opened again - it stops working. If i clear the data of the app it would again start working.

**Comment by KieronQuinn** [comment]
Please try disabling battery optimisation in whatever way is normal for your device. Accessibility services should not be killed, but apparently OEMs don't care.

**Comment by nandans98** [comment]
Tried doing it and enabled the app to restart on its own but to no avail!
