### ISSUE TITLE
Problem after upgrading from 1.1 to 1.3

### ISSUE THREAD

**Issue by Bradford1040** [KieronQuinn/TapTap#290]
I created a few posts on xda, I am on version 1.3 & had updated from 1.1. I have a Samsung A50 A10 one ui 2.0, use nova launcher & Klwp & tasker. All permissions have been given, I have done a fresh install, wiped cache & data, restarted. Everything I have read or knew of, I have done.

The app is working, but it isn't, I can not change any settings as the app is stuck at "connection to services" but as I have said it's still working, apps that I had forced via 1.1 are still in dark mode (after I run adb Wifi cmd). The big one for me is Amazon shopping app, because of late night window shopping lol.

Is there anything I can do to fix the problem? Or something I did that is causing it?

**Comment by KieronQuinn** [comment]
This is the repository for Tap, Tap not DarQ. Please remake this issue on https://github.com/KieronQuinn/DarQ/issues
