### ISSUE TITLE
App isn't detecting my taps

### ISSUE THREAD

**Issue by alok-debnath** [KieronQuinn/TapTap#291]
So, I am a user of Samsung galaxy j7 pro (32 bit Android 9) and I am using the latest v0.9. I am using this app since back you guys added the support for 32bit, but the app never worked on my device. I tried every possible way, tried increasing the sensitivity and so on. If I can help you guys in fixing this in any way then please ask me, I would love to see the app running perfectly in every device. Thanks, hope that this app will be fixed for users like me.

**Comment by KieronQuinn** [comment]
Does it not even work during the setup, following the troubleshooting steps in there if needed?

**Comment by alok-debnath** [comment]
> Does it not even work during the setup, following the troubleshooting steps in there if needed?

I have tried that, it isn't working in the setup screen.

**Comment by KieronQuinn** [comment]
There's nothing I can do without having the device in my hands in that case unfortunately. No further debugging can be done remotely.

**Comment by alok-debnath** [comment]
> There's nothing I can do without having the device in my hands in that case unfortunately. No further debugging can be done remotely.

If you want then I can provide CatLog to help you fix this issue. I saw a lot of people reporting the same issue. Btw, thanks for this wonderful app.
