### ISSUE TITLE
Action Combo not Properly Working

### ISSUE THREAD

**Issue by GoodarzMehr** [KieronQuinn/TapTap#292]
I have set my triple tap actions to 1. Split screen and 2. Launch assistant. Split screen says it doesn't work on the home screen so I think a triple tap should launch the assistant, but nothing happens.

**Comment by KieronQuinn** [comment]
Split screen doesn't actually know what screen it's being launched from so can't skip if it wouldn't actually launch successfully. What you should do is add the launch assistant action _above_ the Split screen action, and add a requirement that it only runs when the home screen app is showing. That will allow the app to do what you want.
