### ISSUE TITLE
Feedback bug with triple tap option

### ISSUE THREAD

**Issue by Zeanon** [KieronQuinn/TapTap#294]
Something I just encountered while playing around with triple tap actions: the "feedback" for the gesture is activating even if the action is blocked by a gate.
That means for example I have a triple tap action only to activate when the lock screen is showing and only that one action and if I do a triple tap with my phone unlocked it will still vibrate even though the action is not run(as expected since lock screen is not showing)
Also triple tap actions seem to kind of override the "wake device" feedback since when I have "wake device" disabled and use a triple tap action in lock screen, the pin pad is showing (which it doesn't with double tap,as expected)
This behaviour will not occur when the phone is "off" but the vibration feedback will still be send.

On the same note: would it be possible to have different feedback for different actions.
For example I am using triple tap to mute/unmute and double tap for camera so it would be kind of awesome to be able to have wake device for double tap(as I want to enter the camera when opening it) but the device does not need to be woken up when I mute/unmute it

**Comment by KieronQuinn** [comment]
Fixed in 0.10 beta. Feedback for different actions (particularly wake) is on the roadmap, but the new wake logic in 0.10 also will not do a full unlock wake on actions that don't need it (and will instead just wake the device to the lockscreen)
