### ISSUE TITLE
Stops working after the screen is turned off for a few seconds.

### ISSUE THREAD

**Issue by AdityaAnand99** [KieronQuinn/TapTap#296]
I'm using this app on my LG G8X.
Specifications : snapdragon 855, 6GB RAM, LG UX9. 
The app works perfectly fine while the screen is on and after the screen is turned off, it still works for at most 30 seconds before becoming unresponsive. Starts working again the moment screen is turned on. I've tried everything, excluded the app from battery optimisation. Never had any kind of trouble on Nokia 8.1.

**Comment by KieronQuinn** [comment]
If it's being killed and doesn't work again when the screen turns back on, there's nothing I can do. The system killing the app even after it being excluded is out of my hands.

**Comment by AdityaAnand99** [comment]
Actually it starts working again when the screen turns on.

**Comment by KieronQuinn** [comment]
You have disabled the screen off gate right?

**Comment by AdityaAnand99** [comment]
That's the weird thing, I have not. I'm using your app since the v0.1. I know every nook and corner of it.

**Comment by AdityaAnand99** [comment]
I confused the wording and yes I have disabled the screen off gate.

**Comment by KieronQuinn** [comment]
If you have disabled the gate I have no idea what's going on. I don't have a Samsung device like yours to test on to figure it out either.

**Comment by AdityaAnand99** [comment]
Thanks anyway. I'll rather return the device than use it without TapTap.
