### ISSUE TITLE
Bluetooth headset selector/filter

### ISSUE THREAD

**Issue by tommasoberlose** [KieronQuinn/TapTap#299]
Hi! I'm in love with this application because it helps me to open the notifications panel on my OnePlus 8T without using any gesture. I've set up the double-tap action but when I'm driving it's triggered by the vehicle vibrations.
Is it possible to add a filter to the Headset gate to check if one or multiple devices are connected? For example the vehicle Bluetooth in my case.

That could be really useful!
Thank you

**Comment by KieronQuinn** [comment]
It doesn't actually check for bluetooth devices as such, it simply asks the system if any bluetooth audio device is connected. For what you require, I'd recommend using the Tasker plugin as things like detecting specific bluetooth devices are out of scope for this app as it would open the floodgates to a million requests to add x feature from Tasker when Tasker already does it fine.
