### ISSUE TITLE
Three taps action

### ISSUE THREAD

**Issue by Madis0** [KieronQuinn/TapTap#3]
Not sure how reliable that would be, but probably worth testing.

**Comment by KieronQuinn** [comment]
The TensorFlow model doesn't support three taps by default, but this is something I'd like to look at adding

**Comment by Martin5001** [comment]
Nice idea. Just a small note: maybe what might happen there is the user accidentally tapping one more time – 4 times instead of 3 – so maybe that's the reason why there isn't this gesture in the model? 🤔

**Comment by KieronQuinn** [comment]
Added in 0.8 Beta.
