### ISSUE TITLE
Triple Tap Is Not Working When I Remove The App From  Recents But Double TapIs Working Fine

### ISSUE THREAD

**Issue by Mr-Spandan** [KieronQuinn/TapTap#301]
I use Redmi Note Nine Pro Max with MIUI 12 based on android 10

I've disabled MIUI optimizations.
I've enabled every permissions.
Ive done everything that's on the start page.

But the triple taps is not being registered.

**Comment by KieronQuinn** [comment]
0.10 has likely fixed this but in case it doesn't, make sure the app is pinned to the recents. It might prevent you removing it, but MIUI is known to kill apps when swiped away so can cause problems.
