### ISSUE TITLE
App is causing issues with camera stabilization

### ISSUE THREAD

**Issue by vmirage** [KieronQuinn/TapTap#302]
When Tap, Tap service is running, my camera stabilization goes haywire. Videos recording is shaky whenever I just shake my phone lightly. I'm using Samsung Galaxy Note 10. Not sure if this affects only samsung camera stabilization or other phones as well. Turning the Tap Tap service off seems make my camera stabilization behave well again.

**Comment by LucasDRavarotto** [comment]
Also happens to me

**Comment by KieronQuinn** [comment]
Please try with the 1.0 rewrite. If it still happens, I can only assume it's due to some sort of system interaction on that device when the gyroscope is in use by multiple apps. You may also want to simply add an "App Showing" gate for the camera, which will disable it when the camera is open.
