### ISSUE TITLE
More TF models - maybe training built into the app?

### ISSUE THREAD

**Issue by fonix232** [KieronQuinn/TapTap#304]
I'm not sure if it's possible at all, but it would be nice to have the possibility to train a custom model specific to the phone - maybe as a guided wizard that allows for the recording of the necessary data, and sent back to GitHub or a service running on Firebase for proper TensorFlow processing. 

This could allow for more device-specific profiles to be created and added to the app. For example, on my Note20 Ultra, even on highest sensitivity, tap recognition is very hit and miss. Sometimes it can activate from rustling in my pocket, sometimes it won't even respond to the hardest taps in the same location that it worked before - but on my OnePlus 7T Pro, it works perfectly.

**Comment by KieronQuinn** [comment]
Not possible, I don't have the original TensorFlow models and you can't train models with TensorFlow Lite anyway, it only runs against models.
