### ISSUE TITLE
FLASHLIGHT TOGGLE PROBLEM

### ISSUE THREAD

**Issue by umarfarooqumzen** [KieronQuinn/TapTap#306]
Let's say I double tap to turn on the flashlight
Then I manually turn off the flashlight from the notification bar 
And then again double tap so the flashlight turns on but it doesn't
The device vibrates but nothing happens. After double tapping again for the second time it works
Maybe it should be a toggle I mean when I double tap the code should check if the flashlight is on or not, if on turn off and if off turn on. It would be a improvement I guess.

**Comment by KieronQuinn** [comment]
This isn't possible without using system APIs (as SystemUI does) or always having a camera listener open, which would drain battery and be a security concern. Use one or the other or just do the gesture twice when it happens.
