### ISSUE TITLE
Launch function not working

### ISSUE THREAD

**Issue by HR88** [KieronQuinn/TapTap#307]
I'm on Mi 10T Pro, it seems that the double tap launch function doesn't work unless when the app is on the main screen. When minimised the launch action won't work for double or triple tap. The phone does vibrate when taped meaning it does read the double tap.

For task such as screenshot or flashlight it does work fine

**Comment by KieronQuinn** [comment]
Have you disabled all the MIUI battery optimisation and the Autostart option? This isn't standard Android behaviour, if MIUI is preventing background services from launching activities there's absolutely nothing I can do about it.

**Comment by HR88** [comment]
Seems like turning off the autostart fixed the issue. Thanks 😊

**Comment by HR88** [comment]
The autostart option is the culprit. Turning it off fixed it. Thanks!
