### ISSUE TITLE
Unstable sensors gates: Pocket and Table

### ISSUE THREAD

**Issue by rodrigoswz** [KieronQuinn/TapTap#310]
Sensor gates like Pocket and Table are very problematic on my device. It works very well until suddenly it starts blocking all my taps, when I disable them immediately everything back to work.

I don't know if this is something that occurs on other devices, so anything I can help with, please let me know.

**Device:** Xiaomi Mi 9T
**OS:** Android 11 (AOSP ROM, not MIUI)

**TapTap:** 0.9beta
**Battery optimization:** Off
**Accessibility services:** Primary on, Secondary off
**Use split services:** On
**Auto-restart service:** Off

**Comment by KieronQuinn** [comment]
Please check if this is still a problem with the rewritten core in 0.10 beta.

**Comment by LucasDRavarotto** [comment]
it happens to me too

**Comment by KieronQuinn** [comment]
Please try with the 1.0 rewrite, if it still happens then there's nothing I can do, sorry.
