### ISSUE TITLE
Gate "keyboard open" does not work for bubble conversations (e.g. Facebook Messenger)

### ISSUE THREAD

**Issue by Cheptii** [KieronQuinn/TapTap#311]
Hey,

the gate "Keyboard open" does not work for bubble conversations for apps like Facebook Messenger.
I keep getting the double tap triggered because of the haptic feedback on the keyboard.

It would be great to implement a gate that detects whether the vibrator motor is triggered or not, which would certainly avoid many accidental activation of the double tap.

Otherwise Great App and thanks for your work !!

**Comment by KieronQuinn** [comment]
The keyboard gate underneath is actually just an app gate looking for the keyboard. There's no other way provided by Android to detect it from a service. 

As for haptic feedback detection, that's also not possible from a service.
