### ISSUE TITLE
Vibrate after action performed isn't working

### ISSUE THREAD

**Issue by 0ibaba** [KieronQuinn/TapTap#312]
OneUI Core 2.5

I don't know why but my phone doesn't vibrate after the actions are performed

**Comment by KieronQuinn** [comment]
You probably need to enable the option to vibrate when DND is enabled

**Comment by Oi-Baba** [comment]
> You probably need to enable the option to vibrate when DND is enabled

nah man that doesn't fix it either

**Comment by KieronQuinn** [comment]
I updated the feedback code in 1.0, if it's still not working then there's nothing I can do, as it's using standard system code.

**Comment by 0ibaba** [comment]
> I updated the feedback code in 1.0, if it's still not working then there's nothing I can do, as it's using standard system code.

Everything seems to work properly in the current update.
It stops after the screen turns off but starts right back up when it's turned on, so It's just bad battery management from oneui and not the app's fault.

**Comment by KieronQuinn** [comment]
> > I updated the feedback code in 1.0, if it's still not working then there's nothing I can do, as it's using standard system code.
> 
> Everything seems to work properly in the current update. It stops after the screen turns off but starts right back up when it's turned on, so It's just bad battery management from oneui and not the app's fault.

You probably need to disable the screen off gate.

**Comment by 0ibaba** [comment]
@KieronQuinn It is disabled
I've had this problem from the really early builds. So it's probably just oneui
