### ISSUE TITLE
Gesture does not work when screen is off

### ISSUE THREAD

**Issue by the-chirag** [KieronQuinn/TapTap#314]
None of the gesture works when the screen is off. I have checked the gate also for the same but it didn't work. I am using this app on OnePlus 8T with Android 11.

**Comment by KieronQuinn** [comment]
Have you disabled OnePlus battery optimisation for it in the app info settings?

**Comment by the-chirag** [comment]
No I have set to do not optimise.

**Comment by KieronQuinn** [comment]
Please post screenshots of your config in that case, the actions, gates and feedback screens.

**Comment by JacksonCampbell99** [comment]
Does thing when the screen is off. Registers triple tap with haptic feedback, but does no feedback or anything on double tap.

**Comment by KieronQuinn** [comment]
> Does thing when the screen is off. Registers triple tap with haptic feedback, but does no feedback or anything on double tap.

Have you disabled the screen off gate? It's (intentionally) on by default.

**Comment by JacksonCampbell99** [comment]
Thank you. I just stumbled upon that before seeing this. I will mention that it doesn't turn on the screen when set to launch an app. The app launches with the phone off.

**Comment by KieronQuinn** [comment]
The turn screen on method has been changed in 0.10 Beta, and definitely now works on my OnePlus device so it should also do for you.
