### ISSUE TITLE
While typing also it is taking the screenshot

### ISSUE THREAD

**Issue by Abs7992** [KieronQuinn/TapTap#315]
if I'm speed typing something then automatically it takes screenshot multiple times. The gestures are working even when I've turned the gestures off, deleted more than 50 screenshots since last 2 hrs. I guess i've to uninstall it to stop it from taking the ss even after turning it off. I'm using the latest beta available on xda .

**Comment by KieronQuinn** [comment]
Add and enable the keyboard gate.
