### ISSUE TITLE
[ Feature Request ] Run gesture only while holding phone in vertical position. 

### ISSUE THREAD

**Issue by PremGandhi** [KieronQuinn/TapTap#321]
Some times accidental double tap gesture runs while putting phone on table. So please add requirement that gesture runs only when phone is in vertical position. * Not screen orientation but phone orientation * @KieronQuinn

**Comment by KieronQuinn** [comment]
This already exists. The table gate.

**Comment by PremGandhi** [comment]
It stops working when I turn on table gate.
