### ISSUE TITLE
Pause/play only playing 

### ISSUE THREAD

**Issue by jettsd** [KieronQuinn/TapTap#326]
When. Using double tap to pause and play music I can only get it to start playing and double tapping again quicky pauses and in pauses and sometimes reads me the time. Nothing else is set

**Comment by KieronQuinn** [comment]
The play/pause actions are simply sent to the system. If the system decides to not send them on (as it sounds like is happening here), it's not caused by this app.

**Comment by jettsd** [comment]
The issue got a bit weirder and now pause/play is just reading out the time but my bixby remap is working as intended with pause/play

**Comment by KieronQuinn** [comment]
Again, all it is doing is sending the play/pause command to the system. You can see the code for it here: https://github.com/KieronQuinn/TapTap/blob/master/app/src/main/java/com/kieronquinn/app/taptap/columbus/actions/MusicAction.kt

**Comment by jettsd** [comment]
After farther testing including using other alternative gesture apps such as bx actions your app was the only one that has issues. Make of that what you will.
