### ISSUE TITLE
Switch sound profiles no function

### ISSUE THREAD

**Issue by yZhentan** [KieronQuinn/TapTap#327]
At the "triple tap"，the "Switch sound profiles" doesn't work while you are at another app (tap,tap is running in the background ". But if tap, tap is running in the foreground，the "Switch sound profiles" will working.

*My phone, Oppo Reno 10x zoom

**Comment by KieronQuinn** [comment]
Disable all the battery optimisation options for Tap, Tap on your device, including any that mention background starting or "auto start". If it's working in the foreground but not in the background, the issue is down to restrictions/killing from the system, not the app itself.
