### ISSUE TITLE
Inconsistency 

### ISSUE THREAD

**Issue by KJ-77** [KieronQuinn/TapTap#331]
I use tap tap on a note 10+ exynos, and when it works, it works perfectly, but if i stop using it for a while(a while being 15 mins), i can not, for the life of me, get it to work. At that point i would have to go to the app, turn off gestures, triple tap, and the tap tap secondary service, then turn them on again and start tapping away on the back of my phone for a couple of minutes, looking for the right spot and the right amount of force to use, to get it to work. So there is no sweet spot for it, and no specific force to get used to even though im not touching the sensitivity settings, and no guarantee that i can just pop my phone out and tap the back and have it work, which is why im holding off on flexing on my friends with this app lol. And just to note, i had a strange bug once where i tried tapping the back of my phone to do a specific action and it didnt work, so i started tapping with variable force and in different spots to get it to work, but after a gd 5 mins of tapping i gave up and opened the app, and the second i did, all those unregistered taps from my 5 mins of spamming started registering one after another and it was pure mayhem until the unregistered taps ran out😂😅. So basically this is a great and even an amazing app to use when it works, but sadly, it working isnt very common for me right now:(

**Comment by KJ-77** [comment]
Btw i have all advanced settings toggled on except for a custom sense

**Comment by KieronQuinn** [comment]
Sounds like your device is killing the app in the background. Make sure you have disabled battery optimisation following these steps: https://dontkillmyapp.com/samsung
