### ISSUE TITLE
Launch Apps

### ISSUE THREAD

**Issue by bill-chr** [KieronQuinn/TapTap#332]
I have tried the Launch Assistant option with double or triple tap, but it works only when the app is open. When I am in home screen or in another app and tap twice/ three times it only vibrates, but the assistant isn't launching

**Comment by KieronQuinn** [comment]
Do any other actions work?

**Comment by bill-chr** [comment]
> Do any other actions work?

Yes, always, in both double and triple tap

**Comment by KieronQuinn** [comment]
Could you please try another action that launches an app (such as 'Launch app' funnily enough). I suspect you're either hitting a background launch limit (are you using MIUI?) or the 5 second rule.

**Comment by bill-chr** [comment]
> Could you please try another action that launches an app (such as 'Launch app' funnily enough). I suspect you're either hitting a background launch limit (are you using MIUI?) or the 5 second rule. 

Yes, I'm using miui. None of the actions from launch option works out of the app whatever I wait. Just a vibration

**Comment by KieronQuinn** [comment]
> > Could you please try another action that launches an app (such as 'Launch app' funnily enough). I suspect you're either hitting a background launch limit (are you using MIUI?) or the 5 second rule.
> 
> Yes, I'm using miui. None of the actions from launch option works out of the app whatever I wait. Just a vibration

Follow the steps on here: https://dontkillmyapp.com/xiaomi. Autostart is I think what is to blame here, it prevents background services from launching apps.

**Comment by bill-chr** [comment]
> > > Could you please try another action that launches an app (such as 'Launch app' funnily enough). I suspect you're either hitting a background launch limit (are you using MIUI?) or the 5 second rule.
> > 
> > Yes, I'm using miui. None of the actions from launch option works out of the app whatever I wait. Just a vibration
> 
> Follow the steps on here: https://dontkillmyapp.com/xiaomi. Autostart is I think what is to blame here, it prevents background services from launching apps. 

I had already Autostart enabled. However, I activated pop-up windows in app's settings and now it works perfectly. Thank you!
