### ISSUE TITLE
All gestures are not working on Xiaomi Redmi Note 5

### ISSUE THREAD

**Issue by taroj1205** [KieronQuinn/TapTap#334]
The latest version of Tap Tap is not working on my Xiaomi Redmi Note 5.

My settings are highest sensitive, accessibility granted and battery optimization is disabled.

**Comment by KieronQuinn** [comment]
Do they work during setup?

**Comment by taroj1205** [comment]
I'm sorry for late response.
It worked on older versions of Tap tap.
But when I installed the new version, it stopped working.
But it's okay because I bought new phone few days ago and it's working on it.
Thank you.
