### ISSUE TITLE
Multiple inputs/doesn't always work

### ISSUE THREAD

**Issue by KJ-77** [KieronQuinn/TapTap#336]
I had a problem with tap tap not working on my note 10+ exynos, and was told to turn off battery optimisation and sleeping apps, which i did, and after 5 days of trying that, I've encountered a couple of new issues. The first one is I have triple tap set to "next", as in play the next song, and even though i have the sense way down, one triple tap skips literally around 7 or more songs, and sometimes even pauses the song it lands on somehow. And another weird issue is that after not using tap tap for a while, like when i go to sleep, when i wake up and try it, the first one or 2 times work perfectly but then it just stops taking gestures. I have both advanced options toggled on btw

**Comment by KieronQuinn** [comment]
It sounds like it's triggering multiple times when it shouldn't, please try rebooting to see if that helps.

**Comment by KJ-77** [comment]
Tried it for a while, didnt work:(

**Comment by KieronQuinn** [comment]
In that case all I can suggest is to play with combinations of different models with the size option and sensitivity levels. Note that the size doesn't always match your device, you may find it works better with a different option selected.
