### ISSUE TITLE
oppo a7

### ISSUE THREAD

**Issue by asmprotk** [KieronQuinn/TapTap#337]
don't work on my device. 
oppo A7

**Comment by KieronQuinn** [comment]
Please give more information, this is not enough to be a valid issue. Does it work during setup? Have you followed all the troubleshooting steps including trying all the model sizes, increasing the sensitivity, tapping harder etc.?

**Comment by asmprotk** [comment]
I use all that things  
but still don't work.

**Comment by KieronQuinn** [comment]
Ok so it worked during setup? Then it's being killed by the system and you need to follow the battery optimisation disabling steps here: https://dontkillmyapp.com/oppo and the ones in the app.
