### ISSUE TITLE
Spontaneous Triggering

### ISSUE THREAD

**Issue by bmduke1997** [KieronQuinn/TapTap#338]
White my phone just sitting on the table, in my pocket, or even in my hands with fingers nowhere near the fingerprint sensor the gesture will trigger. I.e. the flashlight spontaneously turns on and occasionally off again. Other times I have to turn it off by tapping twice for the trigger.

I am using a Pixel 5 completely up to date. U.S. Unlocked.

Thanks for the hard work, love the app!

**Comment by KieronQuinn** [comment]
There are gates that disable it when on the table or in your pocket, I advise you use those. As for the fingerprint sensor, that's just a guide - tapping anywhere on the device with sufficient force will in fact work.

**Comment by bmduke1997** [comment]
I don't see gates for either of those. All. Used are options for "display off", "display on", "usb device", "on call", and "charging". I could choose display off, but I'd rather not. Besides I would almost assume if no input was given it shouldn't trigger?

**Comment by KJ-77** [comment]
Tap the "add gates" button at the bottom when you have the gates screen open to find the ones you want, and its still in beta so🤷‍♂️

**Comment by bmduke1997** [comment]
Thank you for the help. I hope you found this thread helpful in some way. I was purely trying to help document a bug if found. This is ana amazing app and keep up the good work!
