### ISSUE TITLE
(Bug) [Xiaomi Mi 9T Pro] Gestures don't work all of a sudden and apps permissions revoked.

### ISSUE THREAD

**Issue by NicolasSilveira96** [KieronQuinn/TapTap#340]
I was able to test the app and features for a little while but suddenly I figured out some apps lost permissions I already granted long ago (i.e. WhatsApp and Telegram asked me to access contacts, media, camera and mic again).
As soon as I fixed that, the TapTap gestures stopped working. The app didn't ask for anything else to work, and I didn't change anything app-related, so I have no idea how one symptom is connected to the other.

I'm running MIUI Global 12.0.3 on my Xiaomi Mi 9T Pro.

**Comment by KieronQuinn** [comment]
Reinstall the app and follow the battery optimisation disabling steps again. This sounds like a system bug, nothing to do with the app.

**Comment by NicolasSilveira96** [comment]
> Reinstall the app and follow the battery optimisation disabling steps again. This sounds like a system bug, nothing to do with the app.

Did this and the app is running as it should again, at least by now
