### ISSUE TITLE
Gates for applications doesn't work

### ISSUE THREAD

**Issue by Styxrich** [KieronQuinn/TapTap#341]
I have gates set for certain apps where screenshot would be blocked from certain apps as I do not want tap tap to screenshot at certain apps as it is too sensitive even when I set the lowest sensitivity, tap tap still senses it and randomly screenshots but sometimes it takes very long and doesnt even screenshot and also sometimes misread my taps and takes 2 screenshots instead of 1

**Comment by KieronQuinn** [comment]
Fixed in 0.10 beta.
