### ISSUE TITLE
Doesn't work after restart

### ISSUE THREAD

**Issue by MKCOOL142** [KieronQuinn/TapTap#342]
So I had this on 2 completely different phones already, but after restarting the phone the back gesture doesn't work, plus let me know if there is a workaround or if this is known

**Comment by KieronQuinn** [comment]
Which devices?

**Comment by MKCOOL142** [comment]
Huawei honor play and OnePlus 7 Pro, which device do you use for testing?

**Comment by KieronQuinn** [comment]
OnePlus 7T Pro. Make sure you have disabled battery optimisation on both devices (including the OEM optimisation, see the advice on https://dontkillmyapp.com/) as they will both aggressively kill services and prevent them starting on boot.

**Comment by morfinrider** [comment]
I have the same issue on OnePlus 6 with Android 10. Used to work beautifully until previous beta - 0.8. After the upgrade, it stopped working. Even going back to 0.8 did not fix :-( 
Let me know if you need any additional details to help debug and fix.

**Comment by KieronQuinn** [comment]
Now covered by #354, just make sure you've followed all the steps. Locking the app from the recents seems to be the most important thing on OnePlus devices, for some reason, so make doubly sure you have done that.
