### ISSUE TITLE
A bunch of unexpected behaviour

### ISSUE THREAD

**Issue by VBtheFirbolg** [KieronQuinn/TapTap#345]
I am not sure as to how to furnish detailed logs for what is happening, and I would like to preface that I would gladly do so if someone gives me instructions (needless to say, I am an absolute dunce when it comes to coding).

1. When I install the app on my phone, it works for a while (a day or so) and then it starts malfunctioning. It performs actions which aren't even listed in the hierarchy of actions it can choose from. I have used the double tap option to play/pause media and the triple tap option to toggle the torchlight. These are the only two tasks that are there in their respective hierarchies. Eventually, the double tap option started being interpreted as "Play Next", and at times even my default assistant was opened.

2. When I decided to disable the service as I did not hove to resolve this issue, I toggled the enable service button to off, but then the app started working normally again! I thought toggling the button would make the app stop altogether, but it doesn't, for some reason.

Again, if there is any way I can furnish more information, I would be glad to do so.

**Comment by KieronQuinn** [comment]
Rebooting will fix this, its also resolved in the next update hopefully with an overhaul of how the service works

**Comment by KieronQuinn** [comment]
Fixed in 0.10 beta.
