### ISSUE TITLE
[Working as intended?] Launch Camera shortcut requires passcode before use

### ISSUE THREAD

**Issue by dephunk** [KieronQuinn/TapTap#346]
Basically if I'm on the lockscreen I can swipe camera from bottom right and get into it without using my passcode. When setting launch camera through double tap, it was ask me for passcode before launching app. Is this intended? 

Poco X3 NFC, stock MIUI.

**Comment by KieronQuinn** [comment]
Hmm, good question. I should be able to make it detect when the device is locked and fire off the "secure" camera I think, I'll look into it.

**Comment by KieronQuinn** [comment]
I changed the functionality of this in 0.10 beta to support opening the secure camera when the device is locked, but keep the normal camera when unlocked.
