### ISSUE TITLE
Custom tap sequences

### ISSUE THREAD

**Issue by dkeitley** [KieronQuinn/TapTap#348]
Hi,

I'm a huge fan of this tool. I've really enjoyed playing around with it and using it to trigger different Tasker profiles. 

I was wondering if you knew how possible it would be to use the pretrained tflite models to recognise different tap patterns (e.g. three taps, or taps in a particular temporal pattern)? 

My initial thinking was that I could do some sort of transfer learning by adding additional layers to the tflite model. I know that tflite models can't be converted back into their original format but I've also read that you can use them to extract weights and get a glimpse of the model architecture, implying that maybe it would possible...? 

Do you know what the input/output features are for the tflite models or what the model architecture might be? I'd be really interested to hear any thoughts on how I might be able to recognise different tap patterns.

**Comment by KieronQuinn** [comment]
You wouldn't actually need to retrain the model for this, which is how triple tap _already_ is in the app. The models actually recognise single taps and the app responds based on taps per time limit, so it would be absolutely possible to program patterns like you suggest, but for at very least the time being is out of scope for this app.

**Comment by dkeitley** [comment]
Oh interesting - sorry I didn't realise! I assume this time limit check is implemented in the TapRT/CustomTapRT classes in columbus.jar? Is there any way I can play around with this?

**Comment by KieronQuinn** [comment]
The check for the double tap within the time is in TapRT (in the jar), and the triple tap is implemented in CustomTapRT indeed. If you wanted to disable the original checks entirely, you could build a similar CustomTapRT class extending TapRT and overriding checkDoubleTapTiming, but never call the super method. checkDoubleTapTiming is called every time there's a back tap recognised, so you should be able to create your own pattern recognition within that, using _tBackTapTimestamps as with my implementation.

**Comment by KieronQuinn** [comment]
This should be easier with the full reverse engineering of Columbus included in 1.0 FYI, but I'm closing this now as it's outside the scope of Tap, Tap.
