### ISSUE TITLE
App no longer works

### ISSUE THREAD

**Issue by DiCaprio37** [KieronQuinn/TapTap#349]
Hi,
I'm a big fun of this project and I used to enjoy using it, but lately (with the last update?) after I setup the app and close it the service no longer works, the only way to make it work again is to reinstall it or delete app data.

**Comment by KieronQuinn** [comment]
Please give some information such as device model, Android version, have you tried rebooting and the other troubleshooting steps?

**Comment by DiCaprio37** [comment]
Hi, I have a Xiaomi mi 9 lite, I've tried to reboot, disable gates, mess
with the settings of the app and disable all kind of optimisation. As I
said the app work after the first setup until I close it and does not
longer works after that. I'll try further, for now I'll leave a photo of
the specs below.
 Thanks for the interest.

**Comment by KieronQuinn** [comment]
Make sure you have followed _all_ the steps here: https://dontkillmyapp.com/xiaomi, if it works until you close the app and rebooting doesn't fix it then the system is very likely killing it

**Comment by DiCaprio37** [comment]
I've made all I could think of and it just stays on a bit longer, but after
a while the service is killed.
Dk what to do.

**Comment by KieronQuinn** [comment]
If you've done everything on that list, there is nothing I can do. OEMs killing accessibility services is wrong, especially if it's done solely in the name of "battery optimisations".

**Comment by DiCaprio37** [comment]
Oh, okay what a shame. Thanks for the help anyway, I'll wait until the next
update, maybe it will fix something.
