### ISSUE TITLE
Gate for "Using Keyboard" and "Using Fingerprint Sensor"

### ISSUE THREAD

**Issue by tliebig** [KieronQuinn/TapTap#35]
Hi,
the app is honestly great, and works out of the Box on my Samsung Galaxy S8 (SM-G950f) running Pixel Experience Rom. Great Job!

I'm using it to active the flashlight, and had two unwanted activations:
- when writing something over the keyboard, with vibration feedback for the keyboard set to "on"
- when using the fingerprint sensor on the back

Maybe you could add two more gates as in the subject, which would probably remedy this.

**Comment by Martin5001** [comment]
And maybe these should be enabled automatically by default. At least for the keyboard, probably not the fingerprint as some phones have front sensor, which would likely not cause this issue, thus no need to exclude it, but typing on the keyboard could be excluded always.

**Comment by KieronQuinn** [comment]
Keyboard has been added in 0.5 Alpha

**Comment by tliebig** [comment]
Excellent 🤗. Thank you!

**Comment by EzioTheDeadPoet** [comment]
Somehow the gate is not working at least sometimes for me, as if the app had forgotten my sensitivity and gate setting and the only gate it still honored was the display off gate. If it helps this happens after using the device for a longer amount of time.

**Comment by KieronQuinn** [comment]
Just tried to implement one using the fingerprint listener provided to accessibility services. Not only does it barely work (like it only works when you swipe, not touch), but it also prevents other apps from using gestures on the sensor. Therefore, that gate won't be added.
