### ISSUE TITLE
Not working with LG V30 s

### ISSUE THREAD

**Issue by TeeM28** [KieronQuinn/TapTap#351]
The app works fine during the setup/introduction, vibration works when tapped the phone. But everything stops working when I start the actual configuration.

**Comment by KieronQuinn** [comment]
If it works during setup, it's getting killed by the system. Disable all the battery optimisation for the app and reboot.

**Comment by TeeM28** [comment]
Hi

Thanks for the answer.

I enabled a gate 'the keyboard open', but it doesn't seem to work on triple
tap. So when I type fast enough, the phone shuts the screen as it thinks
there is a triple tap... Is there something I can do about it?

Br Timo

la 6. helmik. 2021 klo 15.38 Kieron Quinn <notifications@github.com>
kirjoitti:

**Comment by KieronQuinn** [comment]
Reduce the sensitivity. The keyboard gate does normally work for triple tap, it's just not perfect on every device so may not be working at all.

**Comment by TeeM28** [comment]
Hi

I'm using 0.0001 as sensitivity but nothing changed.
Br. Timo

to 11. helmik. 2021 klo 17.46 Kieron Quinn (notifications@github.com)
kirjoitti:

**Comment by KieronQuinn** [comment]
Nothing else I can suggest then unfortunately, unless you want to add a load of apps that use a keyboard to your app showing list to blanket block them
