### ISSUE TITLE
Tripple Tap also executes action in Double tap

### ISSUE THREAD

**Issue by paramSonawane** [KieronQuinn/TapTap#352]
I have set `perform tasker task` as action for tripple tap and `take screenshot` as double tap action. But when I tripple Tap, it executes the tasker task and then takes screenshot.

I am on android 10 device and app versiom is 0.9Beta. Rebooting the device rarely fixes this.

**Comment by KieronQuinn** [comment]
This should be fixed in the rewrite in 0.10 beta, ping me if it isn't and I'll reopen.
