### ISSUE TITLE
App crashes if I try to add gate after deleting action

### ISSUE THREAD

**Issue by Trixter313** [KieronQuinn/TapTap#356]
[bugreport-redfin-RQ1C.210205.006-2021-02-07-14-59-23.zip](https://github.com/KieronQuinn/TapTap/files/5939861/bugreport-redfin-RQ1C.210205.006-2021-02-07-14-59-23.zip)
Device: Pixel 5, February security patch
App version: 0.10 Beta

Steps to reproduce:
1. Have at least 2 actions in double tap actions menu.
2. Select and delete the top action.
3. Click on the "Add..." button on one of the remaining actions.
4. App crashes.

It seems that if you delete the bottom action, it doesn't crash. Only adding gates to actions below the one you deleted crashes I believe.

**Comment by KieronQuinn** [comment]
Confirmed and reproduced, will fix for next release.

**Comment by KieronQuinn** [comment]
Fixed in 0.10.1 beta
