### ISSUE TITLE
Issues with third party keyboard 

### ISSUE THREAD

**Issue by Sirdroftardis8** [KieronQuinn/TapTap#360]
I use SwiftKey and despite having the gate for when keyboard is in use, it activates my task while typing. It makes the app nearly unusable with third party keyboards.

**Comment by KieronQuinn** [comment]
Unfortunately Android does not provide a way of knowing when a keyboard is open for a background service (it didn't even provide a way for the foreground app until last year), so the keyboard gate is based solely on whether the keyboard is reporting accessibility window events to the service, which is how it works currently. If some keyboards don't work with that, there's nothing I can do about it unless Android provides a way for accessibility services to know when the keyboard is open.
