### ISSUE TITLE
Gate "Keyboard" not working

### ISSUE THREAD

**Issue by Natsu-Dragnel** [KieronQuinn/TapTap#362]
Disabling the gesture when the keyboard is shown does not work.
Other gates (for example "Lock screen showing") work normally.
If necessary, I can record a video.
Device - OnePlus 3 A3003
Android - 7.1.1
App - v0.10beta
Sensivity - Maximum
Sevice Size - Smallest

**Comment by KieronQuinn** [comment]
#360

**Comment by Natsu-Dragnel** [comment]
> #360

OK, but I use STOCK keyboard. 
The system also has an event for showing and hiding the keyboard
-----------
Possible solution (sorry for Russian) https://fooobar.com/questions/36021/how-to-capture-the-virtual-keyboard-showhide-event-in-android

**Comment by KieronQuinn** [comment]
> > #360
> 
> OK, but I use STOCK keyboard.
> The system also has an event for showing and hiding the keyboard
> 
> Possible solution (sorry for Russian) https://fooobar.com/questions/36021/how-to-capture-the-virtual-keyboard-showhide-event-in-android

Doesn't matter which keyboard does it, just third party ones are often worse at it.

Those solutions don't work for a background/accessibility service, or I'd be using them already.
