### ISSUE TITLE
Taps not working on maximum volume

### ISSUE THREAD

**Issue by darhanger** [KieronQuinn/TapTap#365]
Taps not working when audio play on maximum volume. 
1. Tey change device size;
2. Change sensitivity not help to. 

Device: LG G8 ThinQ
OS: Android 10

**Comment by KieronQuinn** [comment]
Do they work at other times? Struggling to see the correlation here.

**Comment by darhanger** [comment]
ofc, in all other time its work. I think problem in volume and speakers. Its cause problems

**Comment by KieronQuinn** [comment]
If you think it's caused by the speakers causing vibrations and it getting filtered out there's not a lot I can do about that. It's not a bug - it's physics.

**Comment by KieronQuinn** [comment]
Closing due to inactivty
