### ISSUE TITLE
please remember increasing versionCode ;)

### ISSUE THREAD

**Issue by IzzySoft** [KieronQuinn/TapTap#366]
Looks like v0.10 and v0.10.1 both have the very same `versionCode`: 10 – so this update won't reach users of the previous release. Please remember incrementing `versionCode` with each new release :wink:

**Comment by KieronQuinn** [comment]
I'm aware. The built in update system works off the tag not the version code, so it will go out to users fine (this isn't Google Play), I don't want to increment the version code to use hundreds just yet for one tiny bug fix release.

**Comment by IzzySoft** [comment]
> The built in update system works off the tag

Well, the one built into F-Droid does not (and isn't Google Play either), and users might rely [on that](https://apt.izzysoft.de/fdroid/index/apk/com.kieronquinn.app.taptap) having not whitelisted the app itself in their firewall :wink:

**Comment by KieronQuinn** [comment]
> > The built in update system works off the tag
> 
> Well, the one built into F-Droid does not (and isn't Google Play either), and users might rely [on that](https://apt.izzysoft.de/fdroid/index/apk/com.kieronquinn.app.taptap) having not whitelisted the app itself in their firewall 😉

I wasn't even aware it was on F-droid. In fact, last I was told it wouldn't be allowed on F-droid due to the precompiled Columbus library, so I wasn't accounting for that.

**Comment by IzzySoft** [comment]
Surprise :smile: No, it's not on F-Droid.org – but it's in my repo. Consider this as something between "staging" and "non-free", allowing apps to get ready for "F-Droid proper" while already enjoying some of its advantages (and some more, like faster updates). If you wish, feel free to [use this badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) linking to your app in my repo. And once the issue with the Columbus library is solved, I gladly help you "moving over" (disclosure: I'm one of the F-Droid maintainers).
