### ISSUE TITLE
App not installed

### ISSUE THREAD

**Issue by Apolycious** [KieronQuinn/TapTap#367]
Hey ! i was downloading the app, and when the download is done, i open the app and install it. But, when i open it, there's a text that says : App not installed and what should i do? i only can you make a tutorial on how to download it? Thank you :)
I'm using android Oreo btw.

**Comment by KieronQuinn** [comment]
Try installing it over ADB or using the APKmirror app, it'll tell you the actual reason for it failing to install. The generic "app not installed" message is useless as it could be anything.

**Comment by Apolycious** [comment]
> Try installing it over ADB or using the APKmirror app, it'll tell you the actual reason for it failing to install. The generic "app not installed" message is useless as it could be anything. 

Wow, thank you. I'll try that tomorrow

**Comment by Apolycious** [comment]
Hey, i was searching for the app, and i don't found it on the APKmirror, can you give me the link?
