### ISSUE TITLE
App interfering with launcher home screen, app switching

### ISSUE THREAD

**Issue by ToastedVegetables** [KieronQuinn/TapTap#368]
When the home button is pressed, Samsung's default One UI 3 home screen will appear sometimes, instead of my configured third-party launcher (Lawnchair).
When the task switcher/overview button is pressed, the home screen wallpaper is blurred, and pressing home after this will cause the wallpaper to remain blurry and quickly revert to normal.

Turning Tap Tap off doesn't resolve either of the issues, neither does rebooting. Uninstalling fixed the issues.

Tested on a US Samsung S10 5G running Android 11, v0.10.1 beta Tap Tap.

**Comment by KieronQuinn** [comment]
Can only assume Accessibility is the cause here, Tap, Tap doesn't have the permission nor does it try to do anything home screen related (other than the home action which uses the standard Accessibility button API). What actions were you using?

**Comment by ToastedVegetables** [comment]
I was using the double tap actions, specifically to play and pause music. I turned off Tap Tap service's background notification and vibration alerts, but that shouldn't have any effect whatsoever on home screen/app switching. Deleting and reinstalling the apk seems to have solved the issue, but I'm still curious as to why Tap Tap interfered with launcher/app settings and continued to do so after a reboot (maybe an Android 11 issue?). 
Sidenote: when do you think a stable version of the app will be released to the public?

**Comment by KieronQuinn** [comment]
Like I say, I think you likely hit a bug with accessibility in OneUI. Tap, Tap doesn't do anything that can interfere with the home screen, nor does it have the permission to if it wanted to. 

Stable should be soon-ish.
