### ISSUE TITLE
Not sure this is really an issue of the app

### ISSUE THREAD

**Issue by Bradford1040** [KieronQuinn/TapTap#370]
The app sensitivity is all over the place since last night, randomly!

I have been using 0.10.1 since the hour it was posted, had a few problems the day I installed it, but since then I have had no issues.

Till last night, the double tap is like ignoring the gates, I pick the phone up, set it down, put it in my pocket or double tap it, they all act like I am double taping the back. Hard to explain for me, sorry best I can do at the moment

Also, after device reboot, I have to disable both main & triple tap gestures and then enable them again, & have to use the triple gesture first, before it would work normally for the day or so till I rebooted again (till last night) now it is not working normally. I've been using across two different devices from João's taptap share. 

Sorry if this is a nuisance report. It's just frustrating me today, and I haven't changed anything in the app or phone. Was thinking of uninstall after wiping data & cache, reboot, reinstall? Good idea or not?

**Comment by KieronQuinn** [comment]
So I understand, the double tap actions are ignoring all the gates even after rebooting?

I'm also aware of the issue that happens sometimes where the actions don't work after a reboot until you interact with the app. You should be able to get them to work by simply opening the actions pages of the app (which forces a refresh), rather than having to toggle it too.

**Comment by Bradford1040** [comment]
I try that, opening the actions

Test over the next 30 minutes or so and comment back after.

Yes the double & triple tape after reboot don't respond, I have to disable & re-enable, then try the triple first. Then it works (normally)

Just trying to explain & be clear

Today after I rebooted, the double tap gates are being ignored & if I triple tap only 50% of the time does it select the triple action, the other 50% it performs the double tap action

As I keep repeating, only today! Weird? I have no clue why it changed.

I could have delt with the disabled & enabled after reboot, but I use screen shot for my double tap action lol, Google photos had a lot uploaded today (auto backup)

Please don't think I'm am bitchin, I am super thankful for your app! Just one of those annoying days, understand?

**Comment by Bradford1040** [comment]
I still need to disable & enabled after reboot,

I deleted everything, and rebooted, built my actions and gestures settings again, that seems to have fixed the most annoying problem lol

Truly I can live with disable & enable issue for the foreseeable future, I know you got bigger fish to fry.

I probably should have done the erase thing before I posted, I was just frustrated mainly. Hasn't been the best of days.

Stay safe & healthy, again thank you for your time & app!

**Comment by Bradford1040** [comment]
Hey, I downloaded smartpack kernel app, adjusted the governor of the cpu, I have not had an issue with taptap after reboot since!

I removed the governor settings and the issue with taptap comes back, so it's repeatable on LOS 17.1 oneplus 7t pro McLaren

**Comment by KieronQuinn** [comment]
This should be fixed by the rewrite in 1.0, if it is not please reply and I will reopen.
