### ISSUE TITLE
Tap Tap plays music when the music app is closed

### ISSUE THREAD

**Issue by ToastedVegetables** [KieronQuinn/TapTap#371]
When using the double tap to play/pause media action, Tap Tap will play media from a music app that has already been closed. 
For example, if I'm playing music from Spotify, and I pause the music, and close the app, there's no way that I can play the music without re-opening the app. But, when I use the action, Tap Tap will start playing music from the same app _that has already been closed_. 
Putting the music apps into the "Sleeping apps" list doesn't solve this issue, neither does a reboot or reinstall of Tap Tap.
This is annoying, because if I've closed my music app, I don't want my music to start playing again if I double tap the back of my phone. I think that this is an issue with Android 11 background app behavior.
Tested on a US Samsung S10 5G on Android 11.

**Comment by KieronQuinn** [comment]
This is normal Android behaviour, bluetooth headphones and wired headphones with buttons do this too. In fact, internally the app is literally just sending `KeyEvent.KEYCODE_MEDIA_PLAY_PAUSE` to the system - which then handles it as if a button had been pressed.

Nothing I can do about this.
