### ISSUE TITLE
Flash not triggering

### ISSUE THREAD

**Issue by ChildishGiant** [KieronQuinn/TapTap#372]
I've closed all apps and restarted the service but have had no improvements. I can toggle the flash with other apps and the quick tile. Other actions work, just not the flash. This is a new issue and it was working before.

**Comment by KieronQuinn** [comment]
Have you tried rebooting?

**Comment by ChildishGiant** [comment]
Rebooting doesn't seem to fix anything. I can put an action after it and that action will trigger, despite the warning that it'll never happen because the flash will always trigger

**Comment by KieronQuinn** [comment]
That would suggest you have not granted the camera permission, or have revoked it. The only times the flashlight action is skipped is when the device somehow has no flash, or if the permission is revoked.

**Comment by ChildishGiant** [comment]
Ah, that appears to be it. It was set to ask every time (not sure why it changed). Maybe a notification to the user saying there's a perms issue? Either way, thanks for the help :smile:
