### ISSUE TITLE
Feature request: LG V60 Dual screen case open/closed gate

### ISSUE THREAD

**Issue by curiousfur** [KieronQuinn/TapTap#375]
So I'll admit that I have no idea if this is something that can be polled since this phone isn't really a "folding" phone, but the system recognizes when I fold the dual screen case around back. The issue I've run into is that I have set the double tap to turn on the flashlight, but when I open the phone and fold the dual screen back fully, the screen amplifies my taps, triggering the action, and blasting my flashlight into the OLED screen directly against it, which is causing discoloration of the screen. I've set a gate to only allow the action while on the lock screen to prevent me from triggering it accidentally as often, but sometimes just folding the screen backwards on the lock screen causes a double tap input on even the lowest sensitivity. I've tried adding a gate for the "dual screen tool" app, since it makes a persistent notification when the screen is fully folded back, but it doesn't prevent a double tap event from firing off.

**Comment by KieronQuinn** [comment]
Looks like there is an SDK for this: https://mobile.developer.lge.com/develop/sdks/lg-dual-screen-sdk/, whether it would work from a background service is anyone's guess. I'll have a look some time.

**Comment by KieronQuinn** [comment]
Added in 1.5
