### ISSUE TITLE
App ignore action sometimes

### ISSUE THREAD

**Issue by PL7963** [KieronQuinn/TapTap#380]
Sometimes when I tap back the action doesn't work. I'm pretty sure it's working in background and accessibly is enable. I need to re-enable gesture in app to fix that.

**Comment by KieronQuinn** [comment]
#354 
Re-enabling the gesture restarts the service. If that fixes it, it's been killed.

**Comment by PL7963** [comment]
I'm sure it's not be killed. I also tried it in TapTap app. And it's not working. Only click that enable "switch" can be fix.
