### ISSUE TITLE
Ability to add home screen app shortcuts

### ISSUE THREAD

**Issue by Hi1307** [KieronQuinn/TapTap#382]
Is it possible to add a home screen app shortcut (the one where you press and hold an app and the shortcut appears) as an action (similar to Sesame Shortcuts).

**Comment by KieronQuinn** [comment]
Not sure what you mean, to enable and disable the gesture?

**Comment by Hi1307** [comment]
I believe another name used for that is an App Action, an example of which is the "compose" action here: https://www.techrepublic.com/a/hub/i/2019/01/01/b6d67b34-4e36-40bd-b265-989696575e95/appshortcuta.jpg

Is there a way to trigger such an action using the app?

**Comment by KieronQuinn** [comment]
Ok I understand now. 

Only the default launcher or the system can access ShortcutManager to launch shortcuts, so no it's not possible. Might be possible further down the line with root, but for now it's not.
