### ISSUE TITLE
Add threshold

### ISSUE THREAD

**Issue by Robin-april** [KieronQuinn/TapTap#383]
It is hoped that the threshold of the mobile phone on the desktop can be added, so that the action of tap lock screen can be more convenient, and the accidental touch can be reduced to increase the user experience. 
Thank you！

**Comment by KieronQuinn** [comment]
This already exists, it's called sensitivity in the app.

**Comment by Robin-april** [comment]
Oh, sorry, I may not have made myself clear, I mean the threshold at which the phone can use the action of tapping the rear lock screen without opening any apps.

**Comment by KieronQuinn** [comment]
I don't understand what you mean then. What is the "rear lock screen"?

**Comment by Robin-april** [comment]
What I mean by that is that the app detects that I'm not using any other apps at the moment and that the phone is at the threshold of the main desktop to trigger the action.

**Comment by Robin-april** [comment]
The lock screen is just one example.

**Comment by Robin-april** [comment]
This is a bit like the "screen on" threshold that an app already has, but takes it a step further: "screen on and no other apps used."

**Comment by KieronQuinn** [comment]
Set the 'App showing' requirement to your launcher and any other apps you see as being "no other apps used" (the lock screen is SystemUI if you need that), that should do what you want.

**Comment by Robin-april** [comment]
It's a little difficult to understand, please let me think about it, maybe I don't have a thorough understanding of the application you developed, thank you for your reply.
