### ISSUE TITLE
Vibration too low

### ISSUE THREAD

**Issue by FireRunnerYT** [KieronQuinn/TapTap#384]
I dont know if its wanted like this but the vibration when a  double tap was detected is so short that it barely activates the vibration motor. Maybe a slider would be nice to have. I use my double tap to active my flashlight and i wanna feel when its toggled so i will know when its activated by accident.

**Comment by KieronQuinn** [comment]
What phone is this on? I copied the 'feedback' (Google call it that rather than vibration, implying it's meant to be subtle) from the official code, so it's probably meant for devices with a better vibration motor and may be a bit weak on some.

**Comment by KieronQuinn** [comment]
I updated the feedback code in 1.0, so please try with that. If not, please reply and I will reopen and look at it again.
