### ISSUE TITLE
Doesn't work on Xiaomi Redmi 6

### ISSUE THREAD

**Issue by comav** [KieronQuinn/TapTap#387]
Tap, Tap doesn't work at all. Tried to change the device size and sensitivity, but there's no any effect. Also I tried to set custom sensitivity, but this didn't helped

Android version: 9 PPR1.180610.011
MIUI version: MIUI Global 11.0.5 Stable

**Comment by PL7963** [comment]
I had same issue. Just re-enable TapTap by switch on top.

**Comment by KieronQuinn** [comment]
#354
