### ISSUE TITLE
Feature request: Possible preload for OEM and customiation 

### ISSUE THREAD

**Issue by volcano1216** [KieronQuinn/TapTap#390]
hi
Could this app can be preload for smart phone OEM, and customiation for it
including UI and replace traning  model ,if it possible.

**Comment by KieronQuinn** [comment]
No, this is not something I will be offering. The use of the models is already a bit of a grey area, if an OEM decided to include them on a phone it would almost definitely fail certification for Google services.

**Comment by volcano1216** [comment]
as I know ..there is double-tap back gesture for the Pixel 5

**Comment by KieronQuinn** [comment]
Yes, that is the official implementation of this feature. It does not use Tap, Tap. It also doesn't actually work yet.
