### ISSUE TITLE
Triple tap not working

### ISSUE THREAD

**Issue by LucasDRavarotto** [KieronQuinn/TapTap#391]
I activate triple taps and not even double tapping works. Only when I activate triple tap touches are not detected, neither by reconfiguring from zero nor by activating and deactivating the app.

**Comment by KieronQuinn** [comment]
Do double taps start working again if you disable triple taps?

**Comment by LucasDRavarotto** [comment]
Yes, it is
________________________________
De: Kieron Quinn ***@***.***>
Enviado: sábado, 10 de abril de 2021 08:29 p. m.
Para: KieronQuinn/TapTap ***@***.***>
CC: LucasDRavarotto ***@***.***>; Author ***@***.***>
Asunto: Re: [KieronQuinn/TapTap] Triple tap not working (#391)


Do double taps start working again if you disable triple taps?

**Comment by KieronQuinn** [comment]
Please try again with the 1.0 rewrite as this should hopefully be fixed. If it is not, reply and I will reopen.
