### ISSUE TITLE
在主屏进行双击或者三击操作，会有明显较大的延迟(3秒左右))

### ISSUE THREAD

**Issue by DAWNtcc** [KieronQuinn/TapTap#392]
经反复测试，后台服务并没有被杀死。在打开任何一个应用的情况下，进行双击或三击操作，手机振动之后马上就会有动作，但是回到主屏幕，再进行双击或三击操作，震动以后大概要过3秒，才会有动作出来。经询问多人，均有此问题！

**Comment by KieronQuinn** [comment]
This is normal, you are hitting the 5 second home screen delay: https://issuetracker.google.com/issues/36910222

**Comment by DAWNtcc** [comment]
感谢回复，
这真是个凡人的问题呐！



---原始邮件---
发件人: "Kieron ***@***.***&gt;
发送时间: 2021年4月13日(周二) 晚上10:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [KieronQuinn/TapTap] 在主屏进行双击或者三击操作，会有明显较大的延迟(3秒左右)) (#392)




 
This is normal, you are hitting the 5 second home screen delay: https://issuetracker.google.com/issues/36910222
