### ISSUE TITLE
Reachability-esque mode enhancement suggestions

### ISSUE THREAD

**Issue by spectkiller** [KieronQuinn/TapTap#394]
Currently whenever you activate reachability-esque mode, it open tap-tap utility page at 3/4 of screen and other app (user choice) at 1/4 of screen in multi-window BY DEFAULT.

However I would like to suggest to make it 1/2-1/2 screen for both tap-tap and user's choice app or 1/4 of tap-tap and 3/4 of user's app BY DEFAULT

I purpose this suggestion because the default choice give unnecessary space to tap-tap and make user's choice app too compact to use and also I have to adjust it manually everytime.

Hence, I'd be grateful if dev consider this request, thanks you!

**Comment by KieronQuinn** [comment]
This isn't possible, apps don't have control over the size of the multi window screens. In fact, they don't even have control of the bottom half at all - the current implementation is a hack and doesn't work every time.
