### ISSUE TITLE
Cannot find 'take a screenshot' action

### ISSUE THREAD

**Issue by jevoudrias** [KieronQuinn/TapTap#399]
Thanks for developing a splendid app.
However on my Galaxy S7 oreo, I cannot find screenshot action.
app version: 0.10.1 beta
![20210523_145514](https://user-images.githubusercontent.com/84655659/119249934-aecd8780-bbd7-11eb-9028-34413d3695d5.jpg)
![20210523_145505](https://user-images.githubusercontent.com/84655659/119249943-be4cd080-bbd7-11eb-8e87-201d04220327.jpg)
![20210523_145454](https://user-images.githubusercontent.com/84655659/119249952-c4db4800-bbd7-11eb-98e6-224213c416e0.jpg)

**Comment by KieronQuinn** [comment]
Take screenshot is only available on Android 9.0 and above due to a system limitation
