### ISSUE TITLE
Gates Not Working in landscape/game mode

### ISSUE THREAD

**Issue by eliversun** [KieronQuinn/TapTap#40]
The Gates "App showing" doesn't always work when in landscape apps or when the Game Mode is turned on.

My device is OnePlus 7 Pro, and I have a MOBA game (which is in landscape) in the Game Space. When I open the MOBA game, there is a floating window indicating that the Game Mode is automatically turned on (which is a feature on OnePlus Phones). 

And I've added and enabled a Gate "App showing" of this MOBA game to block gesture when it's on the screen. However, the gesture keeps getting triggered when I'm in the game.
![Screenshot_20200801-073230_594ce24a2781d8c70be4683d0faad841](https://user-images.githubusercontent.com/30193345/89088103-363bd700-d3c9-11ea-970e-8016941ed0de.png)
![Screenshot_20200801-073243](https://user-images.githubusercontent.com/30193345/89088105-39cf5e00-d3c9-11ea-89e1-adcabfa77e76.png)
Then I tried another landscape game that is not in the Game Space and won't turn on Game Mode(set up the Gate as well). Seconds after I'm in the game, I can still trigger gesture. 
I've also tried a game in portrait view that will turn on Game Mode. The Gate for this one doesn't work, either.

Really hope you can look into it, thanks.:-)

**Comment by KieronQuinn** [comment]
Fixed in 0.10 beta.
