### ISSUE TITLE
Does not install on Samsung Galaxy J3 Orbit

### ISSUE THREAD

**Issue by jeffyjeffy1023** [KieronQuinn/TapTap#400]
It'll install on my old ZTE Blade T2 Lite, which DOESN'T have an accelerometer, but it straight up refuses to install on my new Samsung Galaxy J3 Orbit???? Which actually has an accelerometer?????????? Whenever I try to install the APK it just immediately says "App not installed." :(

**Comment by KieronQuinn** [comment]
Please provide an actual reason for it failing to install, 'App not installed' is not enough. Use the APKMirror app or ADB to install the APK and it will give a true output. 

Will reopen if this information is provided.

**Comment by jeffyjeffy1023** [comment]
Okay, I don't wanna have to install the whole-ass Android SDK so I used the APKMirror installer- And it actually installed??? But now there's a different problem. The gesture doesn't work... I've even cranked the sensitivity to the max setting and it still doesn't work.. :(
________________________________

**Comment by jeffyjeffy1023** [comment]
Update: Turns out it DOES work, it's just that the taps take a ridiculous time to actually register. I'll make a new issue about this.
