### ISSUE TITLE
Taps take way too long to actually register.

### ISSUE THREAD

**Issue by jeffyjeffy1023** [KieronQuinn/TapTap#401]
Device: Samsung Galaxy J3 Orbit
Android Version: Oreo (8.0.0)
Tap Tap version: 10.1

For whatever reason, the taps don't register (as in preform the selected action) until like 2-5 minutes after I tap? I have both accessibility services on, and battery optimization off.

**Comment by KieronQuinn** [comment]
Please try again with 1.0 and see if the rewrite fixes this. If it does not, I will reopen.
