### ISSUE TITLE
Taking screenshot doesn't work on my oneplus 8 pro

### ISSUE THREAD

**Issue by Saurabh7120** [KieronQuinn/TapTap#402]
App Version: 0.10.1 Beta
Device : OnePlus 8 pro
When I double tap the phone, it just locks or an error comes up saying, "System UI keeps stopping". How do I fix this ?

**Comment by KieronQuinn** [comment]
You can't, this is a OnePlus bug. Tap, Tap hands the command to the system, there's nothing I can do.

**Comment by Saurabh7120** [comment]
I got a software update and it started working ! :D

**Comment by KieronQuinn** [comment]
Excellent, nice to know OnePlus has finally fixed the bug.
