### ISSUE TITLE
"Starting app" function works only if Tap, Tap app opened

### ISSUE THREAD

**Issue by Wavephorial** [KieronQuinn/TapTap#403]
"Starting app" function works only if Tap, Tap app opened, but it triggers with no actions if opened in a background. POCO F2 PRO

**Comment by KieronQuinn** [comment]
This is caused by MIUI, not Tap, Tap. For apps to launch other apps from the background, you have to enable a setting which will be something like this: https://stackoverflow.com/questions/59819539/how-to-allow-miui-start-in-background-permission-for-my-application (the screenshot, not the code)

**Comment by Sneaczy** [comment]
Thx a lot
