### ISSUE TITLE
Constant Activation When Typing

### ISSUE THREAD

**Issue by vy-storm** [KieronQuinn/TapTap#404]
For whatever reason, when typing the Tap Tap command is constantly activated.  The typing gate is set to on.  It doesn't always happen, but when it does start happening it won't stop unless I drop the sensitivity down to low.  Oddly enough it doesn't happen when I pretend to type by tapping the screen, only when actually typing.

**Comment by vy-storm** [comment]
Samsung S8+ Android 9
v0.10.1

**Comment by KieronQuinn** [comment]
I can't do anything about this if the keyboard gate doesn't work. Android doesn't provide a way for background services to know when the keyboard is open so the current implementation is a hack that doesn't work for all keyboards and devices. There's no workaround.

**Comment by vy-storm** [comment]
Not even with root?


On 1 Jun 2021 at 20:51, Kieron Quinn ***@***.***> wrote:

I can't do anything about this if the keyboard gate doesn't work. Android
doesn't provide a way for background services to know when the keyboard is
open so the current implementation is a hack that doesn't work for all
keyboards and devices. There's no workaround.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/KieronQuinn/TapTap/issues/404#issuecomment-852617951>,
or unsubscribe

**Comment by KieronQuinn** [comment]
Not that I'm aware of, no.
