### ISSUE TITLE
Reachability action doesn't open in split-screen

### ISSUE THREAD

**Issue by ZLAurora** [KieronQuinn/TapTap#406]
The experimental reachability-like action, it opens a black window in the top of split-screen
Previously triggering this action, it would have the black window at the top, and the app switcher at the bottom

Now it just opens reachability in full screen 😭 So it's just a black screen if you trigger it
If you check that window in the app switcher it auto closes itself

Also, a lot of the time, after double tapping the phone will vibrate once (like it normally does when a gesture is triggered)
But then it just won't do anything ...

[Screen recording](https://streamable.com/mam650)

**Comment by KieronQuinn** [comment]
There's nothing I can do about this, 'reachability' is a hack, there's no official API for split screen. The current method is the only way that works at all.

See also #246
