### ISSUE TITLE
Alpha 02 - still no Tasker integration 

### ISSUE THREAD

**Issue by tiniwings** [KieronQuinn/TapTap#41]
As per release notes, Alpha 02 version should show Tasker integration in advanced category.

But it still shows old message as "Tasker integration is coming soon" Attached screenshots. 

![Screenshot_20200731-185000](https://user-images.githubusercontent.com/37637608/89088715-63539f80-d35f-11ea-93fe-bb4f80ecb31b.png)
![Screenshot_20200731-185540](https://user-images.githubusercontent.com/37637608/89088730-76ff0600-d35f-11ea-95c8-61ff8293ef65.png)

**Comment by rodrigoswz** [comment]
Tasker integration is available in Utilities and works very well.

Btw... yes, really now Advanced menu should have Tasker or disappear. And a proper Tasker icon.

But for an alpha app, making things work is the priority, these details can wait :)

![Screenshot_20200731-215406414.jpg](https://user-images.githubusercontent.com/14058427/89090315-8474ba00-d378-11ea-8ded-ca10042af504.jpg)

**Comment by tiniwings** [comment]
Sorry, my bad. I am looking under advanced option only and thinking it's missing.

Cosmetic changes can wait and give way to other enhancements.
Thanks for developing and sharing it with community.

**Comment by tiniwings** [comment]
The option is available under Utilities.
