### ISSUE TITLE
Tap sensibility thrown off

### ISSUE THREAD

**Issue by Dekyor** [KieronQuinn/TapTap#414]
After a few hours of not opening the app the tap sensibility works as if it was set to the maximum amount leading to accidental taps. It gets temporarily solved opening the app and slightly tweaking the sensibility. I'm using a OnePlus 8 pro with Android 11. The app is allowed to run on the background without battery optimization.

**Comment by KieronQuinn** [comment]
#354 

This is still a background killing issue, although it sounds like it's just restricting the service rather than killing it entirely. OxygenOS is terrible for background restrictions, there's nothing I can do.

**Comment by Dekyor** [comment]
Okay thanks for your response
