### ISSUE TITLE
it hangs my device

### ISSUE THREAD

**Issue by c0der69** [KieronQuinn/TapTap#415]
![photo_2021-08-16_08-07-25](https://user-images.githubusercontent.com/76617735/129504167-83925321-3bba-4890-9342-77315f43452a.jpg)
when i use the screenshot function sometimes multiple screenshot are taken and it makes the screen display white and then the screen becomes unresponsive and later on i have to soft reboot  with the use of power and volume button

see in image you can see little bit of my wallpaper and icons too

**Comment by KieronQuinn** [comment]
The screenshot function is handled by the system, complain to your OEM or ROM maintainer if you're using a custom ROM.
