### ISSUE TITLE
Feature Request: press certain spot of display

### ISSUE THREAD

**Issue by MKCOOL142** [KieronQuinn/TapTap#417]
I wanted to ask for something similar to the Hamburger Menu feature, but instead the user can select the spot themselves which would allow you to f.e press the shutter button in camera apps, like songs on Spotify ect.

**Comment by KieronQuinn** [comment]
I have decided for 1.0 that this is out of scope as it would require a whole config setup for taps and editing them, which is beyond a simple action. I suggest you use the Tasker integration and a Tasker plugin if you still want this.
