### ISSUE TITLE
BUG (atleast I think so): shortcuts can't be specified to only launch in a certain app

### ISSUE THREAD

**Issue by MKCOOL142** [KieronQuinn/TapTap#418]
I played around and wanted to launch a shortcut only in a specific app (specifically creating a new Tweet by double tapping the back when in the Twitter app, I also tried to set it to other apps cuz I guessed maybe it doesn't work because Twitter was already open but nope, still not working), turns out that's impossible no matter what app or shortcut I'm using, I really hope this ain't an Android issue and can be fixed :)

**Comment by KieronQuinn** [comment]
I looked at this for 1.0 and unfortunately it's not possible to detect the current foreground _activity_, just the app. The check of the foreground app and not launching a shortcut if it's the same app as the shortcut takes priority over the case of running a shortcut to launch a part of an app that's currently in use (as it prevents actions being run twice by mistake).

**Comment by MKCOOL142** [comment]
Okay so idk if we're talking about different things but this app f.e can detect which activity is currently running
https://github.com/eicky/AndroidRocket
![Screenshot_20220123-194835](https://user-images.githubusercontent.com/40364718/150693328-6a44c40a-495a-42a0-881e-89b773c85641.jpg)
