### ISSUE TITLE
Doesnt even work

### ISSUE THREAD

**Issue by maxs99674** [KieronQuinn/TapTap#419]
does nothing when i tap the back of my galaxy a10e

**Comment by KieronQuinn** [comment]
Does it work during setup or not at all?

**Comment by immaturetrader** [comment]
I have samsung a22 5G and galaxy m31, taps on these devices are hardly recognized, fault with the manufacturers. Because, app works like a charm on 1+ 6, pixel 5a, 1+ 9. 

Will try to root the Samsung devices to lineage, check the app functionality and let u know!!!

**Comment by KieronQuinn** [comment]
The gesture code has been rewritten in 1.0 and has some new models. Please try with that version, if it still does not work then there's sadly nothing I can do.
