### ISSUE TITLE
Taps aren't recognised once the app is cleared and reopened 

### ISSUE THREAD

**Issue by manhasy** [KieronQuinn/TapTap#42]
My device is Redmi K20 Pro and when the app was installed it was working perfectly but once I cleared the Tap, Tap from memory and reopened it the app didn't recognise the taps. I tried disabling and renabling the app in accessibility but even that didn't work. Finally, I had to clear all the app data and it's working now. 

I recommend if there was to fix the process with the help of permanent notification that wouldnt let it die even if it cleared in multi tasking window.

Thanks, I really look forward to using this app even more.

**Comment by b-bertonzin** [comment]
Hi, bro! I have the same issue with mi 9t.
Could you solve that problem? How did you did that?

**Comment by Nicolas-Arthur** [comment]
It's common with mine, I am also using pixel experience and it will stop working after several minutes.

**Comment by KieronQuinn** [comment]
More discussion and potential fix in #48
