### ISSUE TITLE
Play sound when an action has finished running

### ISSUE THREAD

**Issue by skff-err** [KieronQuinn/TapTap#420]
There are certain times where a vibration won't be as handy as an indicator for a finished action. for example, switching the sound profile would have 2 vibrations (I assume, my phone doesn't vibrate when an action is done weirdly) when it changes the sound profile to vibrate

there could be a menu to select a custom sound or the user could select different sets of "beeps" that varies in different tones, the beeping frequency, as in beep a number of times, the beeping speed and the ability to play different beeps/sounds after another

for example:

double tap
sound profile vibrate
no beep

double tap
sound profile silent
beep once

double tap
sound profile loud
beep twice

**Comment by KieronQuinn** [comment]
This is out of scope for this app, please use the Tasker plugin for specific functionality like this.
