### ISSUE TITLE
restart app constantly

### ISSUE THREAD

**Issue by xamininglife** [KieronQuinn/TapTap#422]
I love the app so thank you to start off. The only real complaint I have is that I constantly have to restart the service for it to work. Not sure if I'm doing something wrong or it's an issue with the app. It does register taps at times when I just set my phone down.

**Comment by KieronQuinn** [comment]
#354

**Comment by xamininglife** [comment]
This is probably really annoying to you and my bad for creating another issue because I don't realize that was the issue. Thanks for the response!

Sent from Yahoo Mail on Android 
 
  On Tue, Oct 5, 2021 at 4:53 AM, Kieron ***@***.***> wrote:   


#354

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
