### ISSUE TITLE
Tap Tap 0.10.1-beta doesnt seem to send Event to latest Tasker Beta 5.14.1

### ISSUE THREAD

**Issue by kashortiexda** [KieronQuinn/TapTap#423]
Executing a task within the TapTap app works fine but Tasker Profile Condition Event is not triggered by the plugin, even when just Trigger Tasker event is selected in TapTap app as only action for double-tap. I checked with Joao (Tasker dev) and he thinks it may be on the TapTap app side plugin no longer sending Event to Tasker

**Comment by kashortiexda** [comment]
Is there a separate TapTap plugin that needs to be installed over and above installing Tap Tap app ?

**Comment by joaomgcd** [comment]
Awesome, thank you!

**Comment by KieronQuinn** [comment]
Fixed in 1.0.
