### ISSUE TITLE
Include frozen / hidden apps & show package name in app list to distinguish apps with the same name

### ISSUE THREAD

**Issue by Gokou-Ruri** [KieronQuinn/TapTap#424]
包含被冻结APP就不需要解冻后再去选了，同理只取消其中一个被冻结APP的时候也不需要解冻后再去取消了。
显示包名可以用来区分同图标、同名称的APK，例如“共存版本”、“Thanox智能冻结的代理APK”、“女娲石的微信增强包”等等。

**Comment by KieronQuinn** [comment]
The package name is now shown in 1.0. Frozen apps cannot be launched, so are not shown.
