### ISSUE TITLE
关于手势灵敏度和命中率

### ISSUE THREAD

**Issue by Gokou-Ruri** [KieronQuinn/TapTap#425]
目前刚使用数天，使用默认灵敏度时，双手打字时都会触发双击手势，但降低1档灵敏度的话，虽然不会误触发，但敲击的时候会很难触发，需要用指甲略用力敲出明显响声才能触发，这样触发起来不太方便。
还有在默认灵敏度时，把手机放桌子上时，也会触发双击手势。例如设置成双击唤醒，放桌子上就会点亮屏幕。
请教一下这种情况有办法改善吗？

续：百分百确定打字时触发手势并非是手机背后的手指不小心误触，而是触发灵敏度和手势算法的问题。另外，这两天试过默认灵敏度降一档，也会在打字时触发双击手势。

**Comment by KieronQuinn** [comment]
For the sensitivity, set a custom value in the advanced settings. For the table, use the table gate. For the keyboard, use the keyboard gate.
