### ISSUE TITLE
No Tasker integration in version 0.2?

### ISSUE THREAD

**Issue by gpion** [KieronQuinn/TapTap#43]
According to the release notes, Tasker integration should now be available in the "advanced" category.

After 0.2 update I've still the following message there:

"Advanced actions such as Tasker integration are coming soon!"

**Comment by f-arthr** [comment]
Same on OnePlus 7 Pro on Oxygen OS BETA 16 Android 10

**Comment by Andriy2** [comment]
Check `Acrions` - `Utilities`

**Comment by KieronQuinn** [comment]
The release notes have the advanced bit crossed out because it was broken by an issue merging. Will be fixed in a build shortly.
