### ISSUE TITLE
Crashes when you take two screenshots one by one

### ISSUE THREAD

**Issue by kajojDeWot** [KieronQuinn/TapTap#430]
I'm using Tap Tap one OnePlus 8 with Android 11. When I take two screenshots without any break between them my phone crushes. I can do nothing. On screen all the time is the second screenshot. Only thing i can do is to restart my phone. I tried it few times and every time the same thing happened.

**Comment by KieronQuinn** [comment]
The screenshot action is handled by the system via accessibility service, OnePlus are known to break implementation of it and there is nothing I can do about that. #402
