### ISSUE TITLE
Only run when app showing doesn't work in beta 10.1

### ISSUE THREAD

**Issue by maxgamesNL** [KieronQuinn/TapTap#431]
I want to use swipe up on double tap on tiktok. So i have the app showing requirment. But it still swipes down in other places/apps

**Comment by KieronQuinn** [comment]
Is the accessibility service running? And does it work with other apps as the requirement, is it just TikTok?

**Comment by maxgamesNL** [comment]
> Is the accessibility service running? And does it work with other apps as the requirement, is it just TikTok? 

Accessibility is running, the secondary service is also running.

It swipes in all apps and when removing tiktok and placing Gmail or Twitter it still swipes down when tapping. 
So it is nothing app related.
I also have nothing with swiping in the 3 tap function

**Comment by KieronQuinn** [comment]
The 1.0 rewrite has improved the app showing gate a lot, so this should be fixed in that version. if it is not, please reply and I will reopen.
