### ISSUE TITLE
play/pause music with double tap broken MIUI

### ISSUE THREAD

**Issue by Blu3NTV** [KieronQuinn/TapTap#432]
i have a problem where the double tap stopped working, i have it set as play/pause music when a headset is connected. at first it worked but then stopped and 10 mins it started working again, but who knows when it will stop working, my triple tap gesture (flashlight on/off) works just fine and never had any problem, i did everything the app suggested, even closing the lock in the recent apps menu as i'm on a xiaomi device on the latest firmware, although the app suggests i turn off gesture accessibility menu, which might have some problems for certain actions, but i couldn't find such setting on my device. if someone can point me to it on miui 12.5 and it will fix the problem then i'll take this down, but if not i'd like the problem to be fixed

**Comment by KieronQuinn** [comment]
#354
