### ISSUE TITLE
MIUI accessibility settings shows "The Service is Malfuntioning" after some days of usage

### ISSUE THREAD

**Issue by iamkcube** [KieronQuinn/TapTap#433]
It works all fine at first but after some days it doesn't do the task (in my case taking a screenshot). It still vibrates the phone after 2/3 taps. All MIUI battery optimizations are off. I have to do a reinstall to make it work again, still it continues to happen very often.

**Comment by KieronQuinn** [comment]
"The service is malfunctioning" means the app has been force-stopped in a non-standard way (a proper force stop will disable the service), disable the service and re-enable it. There's nothing I can do about this.
