### ISSUE TITLE
Service not getting killed (running for 80+h) but app stops working either way (Pixel 2)

### ISSUE THREAD

**Issue by armandojrod** [KieronQuinn/TapTap#435]
The service is not getting killed but the app stops triggering taps overnight, it works again if I disable it and enable it again

Battery optimization DISABLED

![Screenshot_20211120-190638](https://user-images.githubusercontent.com/10835960/142742231-f0d4575e-32e0-4034-84ca-3a5f88fcf0f3.png)

**Comment by KieronQuinn** [comment]
The accessibility service is not the only service, you are still seeing the foreground service being killed if it stops working. 

#354
