### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by zephy24** [KieronQuinn/TapTap#436]
Xiaomi Redminote 9s
miui 12, eu rom 12.5.1  (based on android 11)

It works fine when the app is in the foreground.
Double Taps are recognized even in the background.
But it doesn't work.

**Comment by KieronQuinn** [comment]
What actions? Chances are MIUI has some sort of "optimisation" that prevents background launches, disable it. 

Otherwise, nothing I can do.
