### ISSUE TITLE
Running tasker intent crashes the app

### ISSUE THREAD

**Issue by NicolaSpadari** [KieronQuinn/TapTap#437]
Using beta 0.10.1, android 12, tasker 5.15.3 beta, not rooted.
Just after choosing what tasker task to perform via the tap tap app, the app crashes immediatly.
Can't enter the double/triple tap menu where i set the task, because the app will crash right away when opening the menu, I have to clean app data in order to make it work again.
I gave all the permissions to tasker and tap tap, sevices are enabled too.

Some incompatibility between betas? A12 fault?
If you need logs let me know

**Comment by KieronQuinn** [comment]
This is probably related to #423 but if you could send a logcat it would be helpful.

**Comment by NicolaSpadari** [comment]
I got a couple:
- this one while filtering only the app package name: [log.txt](https://github.com/KieronQuinn/TapTap/files/7601336/log.txt)
- this one with the generic logcat command (a couple seconds but pretty big file): [full_log.txt](https://github.com/KieronQuinn/TapTap/files/7601338/full_log.txt)

**Comment by KieronQuinn** [comment]
What's your chosen tasker task called?

**Comment by KieronQuinn** [comment]
Actually, never mind, found the issue, it's a fault in the Italian translation. I'll get it fixed for the next update. 

https://github.com/KieronQuinn/TapTap/blob/abec5a3e139786beeea75e2fb5677013d0719bf1/app/src/main/res/values-it/strings.xml#L160

%ls should be %1s.

**Comment by KieronQuinn** [comment]
Fixed in 1.0
