### ISSUE TITLE
Tap tap does not work when z flip 3 screen closed

### ISSUE THREAD

**Issue by keirongulrajani** [KieronQuinn/TapTap#439]
Using 0.10.0 beta. The app functions fine when unlocked, even when locked and the screen is either off or on and the flip screen is open, but when the flip screen is closed the taps do nothing. Not sure if the phone prevents the taps from being detected or that the app does not run when the flip screen is closed. I tried setting all the gates off such as pocket and display off, it made no difference.

**Comment by KieronQuinn** [comment]
Just to check, it does work after you re-open the phone (without having to restart the service by opening the app)?

**Comment by keirongulrajani** [comment]
Yes it does work when the phone is re-opened. So when it is reopened and the lock screen is on tapping works, when it is unlocked it also works, but the minute the flip screen is closed it does not.

**Comment by keirongulrajani** [comment]
Update: I discovered it does actually work when the screen is shut, it is just a lot harder for it to detect taps

**Comment by KieronQuinn** [comment]
Ah well in that case there's not a lot I can really do, sorry. Sounds like the physical hardware of your device isn't optimal for it to work while closed.
