### ISSUE TITLE
Not working on mediatek devices

### ISSUE THREAD

**Issue by Paritosh-Tripathi-Github** [KieronQuinn/TapTap#442]
I tried everything. It didn't even work during the setup. I have four devices, 3 with mediatek processors and one with Qualcomm. In the Qualcomm one it worked absolutely fine.

In the other 3 devices with Android 9, 10 and 11 respectively. It didn't work on either of them. I tried setting custom sensitivity in advanced and various device sizes. Out of the 3 devices 2 were of small size and third one was of large size. It didn't work in either of them.

**Comment by KieronQuinn** [comment]
Which are these three devices, what models? I find it highly unlikely that nobody until now has tried it on any MTK device and found it doesn't work, and there's no reason why the CPU specifically wouldn't be supported, so long as it supports Tensorflow, which they do.

**Comment by Paritosh-Tripathi-Github** [comment]
These 3 devices are from Vivo, Lenovo and Panasonic.

**Comment by KieronQuinn** [comment]
Sorry but that is still not enough info, what **models**?

**Comment by KieronQuinn** [comment]
Please try 1.0. If it still does not work, please provide the models as I asked above and I will reopen.

**Comment by Paritosh-Tripathi-Github** [comment]
It was a gyroscope problem
