### ISSUE TITLE
Only works when in app

### ISSUE THREAD

**Issue by MichalKakol** [KieronQuinn/TapTap#443]
Taps functions only work while being in app. Double checked everything including using different functions on taps, disabling and enabling settings and permissions but nothing changes. The taps work perfectly fine while in app but when it's closed nothing happens. Also there is a bug that when you want to enable MIUI optimisations it says they are off in app and when you disable them the app says that they are enabled for some reason.

**Comment by KieronQuinn** [comment]
#354
