### ISSUE TITLE
Gesture limitations are not registered/recognized. 

### ISSUE THREAD

**Issue by depld** [KieronQuinn/TapTap#444]
I've set up two two tap gestures and set limitations on both of them, so they can't get in the way of each other:
- Screenshot when screen is on and lockscreen isn't showing
- Play/Pause music when screen is off (and lockscreen is visible) 

As I tried it, I noticed that the limitations aren't registered. Only the screenshot action is executed without any limitation. I also deactivated the "wake up device" feedback, wich also is not working. I've forced the app to close, reinstalled the app and restarted my device (Samsung Galaxy S10 Plus / SM-G975F/DS)
Also, after I set up a second action, the tap gesture don't work at all, which is really weird. 
Thanks

**Comment by KieronQuinn** [comment]
This should be fixed in 1.0, please reply if it is not and I'll reopen.
