### ISSUE TITLE
doesn't work on Sony Xperia xa1 plus 

### ISSUE THREAD

**Issue by phantomboy121** [KieronQuinn/TapTap#445]
doesn't work on Sony Xperia xa1 plus 
Android 8.0

**Comment by KieronQuinn** [comment]
Please give more information, does it work during setup or not at all?

**Comment by KieronQuinn** [comment]
Actually, googling it, the xa1 plus doesn't have a gyroscope. Tap, Tap requires a gyroscope, and will show an error if one isn't reported by the system.
