### ISSUE TITLE
Alternative to accessibility service (using root?)

### ISSUE THREAD

**Issue by xezrunner** [KieronQuinn/TapTap#446]
It is known that enabling accessibility services in Android (possibly depending on the type of service and its permissions) can cause performance issues. It was reported on by XDA [from at least 2015 where it was deemed "working as intended"](https://www.xda-developers.com/working-as-intended-an-exploration-into-androids-accessibility-lag/) and is still an issue currently in Android 12, [as discovered on the Pixel 6 series.](https://www.reddit.com/r/GooglePixel/comments/rrbrr3/pixel_66_pro_randomly_freezing_all_touch_inputs/)

With that in mind, an alternative to detecting the gesture using root access or a system app would be interesting to explore.

**Comment by KieronQuinn** [comment]
This is already part of the rewrite, which is coming out soon. You don't need root, and accessibility will only need to be enabled if an action or gate requires it.

**Comment by xezrunner** [comment]
> ... the Pixel 6 bug is not caused by Tap, Tap unless you have the secondary gesture service enabled. That's the whole point of it being a separate service.

I haven't had much of a technical look into how Tap, Tap works from the code perspective yet, so thanks for clearing that up! :)

> This is already part of the rewrite, which is coming out soon.

Issue closed.
