### ISSUE TITLE
I need an option in this app called SlapSlap

### ISSUE THREAD

**Issue by Gymcap** [KieronQuinn/TapTap#448]
I use this app while I'm working so that i can switch songs without taking my phone out of my pocket. It's super convient to be able to just hit at my pocket a bit to change a song, the only problem is that it seems as though the dev has done a really wonderful job at narrowing the capture down very specifically to "taps". 

I find it to be a little harder to accurately tap my phone with one finger 2 or 3 times through my pocket while im working. Because of this ill often go for a little slap of similar force, but the app seems programed not to detect such a hit. It would be super useful to me if I had an option to target only "slaps", or maybe some other way to choose what kind of hit triggers the app.

Great app though, I use it every day

**Comment by KieronQuinn** [comment]
Unfortunately I don't have control over the models, so I can't tweak them to target that. The upcoming update contains models that are more targeted towards specific taps from a single finger though (models from Google)

**Comment by stefanoantonel** [comment]
I have a similar use case where I would like to play / pause music while sking for example (the pocket is on the chest) and I want just to tap hard on the phone to trigger the action but it is not working properly.
I use a Pixel 4a and the latest version 1.0.1.
Will be any way to achieve this?

**Comment by KieronQuinn** [comment]
No, as I say above it's not possible as the models don't support that. I don't have control over creating the models.
