### ISSUE TITLE
Support for automate and macrodroid like apps

### ISSUE THREAD

**Issue by Underday** [KieronQuinn/TapTap#450]
If we could launch such applications with shortcuts we get a chance to do more

**Comment by KieronQuinn** [comment]
Doing some house cleaning, both app shortcuts and legacy shortcuts are now supported, so is any further work required on this?

**Comment by Underday** [comment]
> Doing some house cleaning, both app shortcuts and legacy shortcuts are now supported, so is any further work required on this? 

I think everything is good right now, thanks for your hard work.

**Comment by e-t-l** [comment]
@KieronQuinn @Underday Have either of you been able to make this work with Macrodroid? Since Macrodroid can use any Tasker plugin, it shows TapTap as compatible, but when I tried to set a macro's Trigger to be TapTap plugin's double-tap input, the macro does not fire. I also tried doing it from TapTap's end, by making the Action be to launch an app shortcut to Macrodroid which calls this specific macro, but it still doesn't fire. Do either of you have any idea why this isn't working? (I can open a new issue if you like)

**Comment by tele-panda** [comment]
same, doesn't launch macrodroid shortcuts or macros.

**Comment by tele-panda** [comment]
> [@KieronQuinn](https://github.com/KieronQuinn) [@Underday](https://github.com/Underday) Have either of you been able to make this work with Macrodroid? Since Macrodroid can use any Tasker plugin, it shows TapTap as compatible, but when I tried to set a macro's Trigger to be TapTap plugin's double-tap input, the macro does not fire. I also tried doing it from TapTap's end, by making the Action be to launch an app shortcut to Macrodroid which calls this specific macro, but it still doesn't fire. Do either of you have any idea why this isn't working? (I can open a new issue if you like)

same, doesn't launch macrodroid shortcuts or macros.

**Comment by chaoscreater** [comment]
@KieronQuinn - this is still an issue. If I try to use "Launch a shortcut", then I can't launch a MacroDroid shortcut. After I chose a Macrodroid macro as a shortcut, Tap Tap will say it's not supported, yet obviously it's one of the supported options to configure a tap action.

My workaround is to create a macro in MacroDroid, then long tap on the macro to create a shortcut on the home launcher. Then, in Tap Tap I'll choose "Launch App shortcut" (which is different to "Launch a shortcut") and then I can choose the macro shortcut I just created. However, this seems like a roundabout way to do things and the root issue with "Launch a shortcut" is still there.

**Comment by tele-panda** [comment]
> @KieronQuinn - this is still an issue. If I try to use "Launch a shortcut", then I can't launch a MacroDroid shortcut. After I chose a Macrodroid macro as a shortcut, Tap Tap will say it's not supported, yet obviously it's one of the supported options to configure a tap action.
> 
> My workaround is to create a macro in MacroDroid, then long tap on the macro to create a shortcut on the home launcher. Then, in Tap Tap I'll choose "Launch App shortcut" (which is different to "Launch a shortcut") and then I can choose the macro shortcut I just created. However, this seems like a roundabout way to do things and the root issue with "Launch a shortcut" is still there.

A workaround sounds good 👍. Will checkout sometime.
