### ISSUE TITLE
Accidental triggering of double tap when typing.

### ISSUE THREAD

**Issue by chathura7357** [KieronQuinn/TapTap#451]
I am using a Galaxy a72 on Android 11 with Samsung keyboard.
I have set up the Taptap to capture a screenshot when I double tap the back if the display is on. And in the gates menu I have Enabled the gate for block the gesture when actively typing. But still when I am typing often ut triggers the taptap and it takes screenshots. I havs adjusted the sensivity also to a low level. But still problem continues. So the gate for blocking the gesture when actively typing seems not working. And in addition to that, I would like to suggest you to add a toggle specifically to on or off the double tap gesture just like the tripple tap has. So I can just turn off double tap gesture and take advantage of tripple tap without a hassle until this problem solves. As implied the tripple tap gesture never bothered me sith accidental triggering.

**Comment by Nathan22211** [comment]
Same here on the razer phone 2, but i usually type one handed on a touchscreen

**Comment by KieronQuinn** [comment]
The keyboard gate has been improved a lot in 1.0. If it's still not working, there's nothing else I can do as the system doesn't provide a way for a background app to know if the keyboard is open.

**Comment by chathura7357** [comment]
Appreciate your hardwork on the app anyway. Its a really great and useful
app and the only problem I had was that accidental triggering. So if you
dont have anything to do with that, then please add an option to turn off
the double tap gesture and keep only the triple tap on. The tripple tap
never bothers with accidental triggering so I can enjoy it.

**Comment by KieronQuinn** [comment]
You already can do that, just remove all the double tap actions :)

**Comment by chathura7357** [comment]
How to remove actions? I tried but failed to find a way

**Comment by KieronQuinn** [comment]
In 1.0, just long press them and the floating button will change to delete

**Comment by chathura7357** [comment]
Great. I can enjoy thw app again then. Thank you so much for the app and
support
