### ISSUE TITLE
Tap tap is consistently not responding on my Razer Phone 2

### ISSUE THREAD

**Issue by Nathan22211** [KieronQuinn/TapTap#454]
It didn't do this before. I thought the model used was it but it's not that.

**Comment by Nathan22211** [comment]
Well with the new update it seems to be not finishing starting up, all I see is a notification saying it's starting

**Comment by KieronQuinn** [comment]
Reboot and see if that fixes it, I didn't change anything in the core for 1.0.1

**Comment by Nathan22211** [comment]
That didn't work, still unresponsive. And Razer doesn't have any backround task killer of it's own as far as I'm aware.

**Comment by KieronQuinn** [comment]
Try 1.1, otherwise it's likely the same issue as #464

**Comment by Nathan22211** [comment]
Well, sort of it freezes now when I do a tap action

**Comment by KieronQuinn** [comment]
It freezes when you double tap or single tap?

**Comment by Nathan22211** [comment]
Double

**Comment by Nathan22211** [comment]
At least it's not constantly restarting on me but yeah. I'm using the legacy model and it frezzes on double tap. Which I have nothing assigned. I think triple is doing similar

**Comment by KieronQuinn** [comment]
And I presume it does it with something assigned too?

**Comment by Nathan22211** [comment]
yeah, same story with something assigned

**Comment by KieronQuinn** [comment]
Can you post a full log including when it freezes? A bugreport should be sufficient (in the system developer options)

Unless people in the linked issue simply haven't noticed, your issue isn't the same if the app actually freezes.

**Comment by Nathan22211** [comment]
Well I have a bug report file but it's taking a while for a gist and Github's not letting me attach it. I might have to make a repo for you to grab it

**Comment by KieronQuinn** [comment]
Drive link is fine, thanks. You may now delete that file as I have downloaded it, I'll see what it shows (if anything)

**Comment by Nathan22211** [comment]
I just tried a double-tap to launch Bandlab

**Comment by KieronQuinn** [comment]
From the logs I can see that it's using the NNAPI, can you try disabling the Tensor low power mode in the advanced options and rebooting, see if that helps?

**Comment by Nathan22211** [comment]
That actually fixed it, the double-tap action is working

**Comment by KieronQuinn** [comment]
Ok, that's good news. It also means that the TensorFlow documentation that claims that NNAPI works on all devices is lying. I'll consider changing the default to disabled for that toggle then, thanks.
