### ISSUE TITLE
(suggestion) add reason to incompatibility message

### ISSUE THREAD

**Issue by MKCOOL142** [KieronQuinn/TapTap#457]
![Screenshot_20220123-202823](https://user-images.githubusercontent.com/40364718/150694816-70d7768c-c268-4920-acd6-0ce288852ed0.jpg)
I think it'd be good if you could give users a reason to why certain options might be incompatible, like f.e here I can't understand *why* the quick access wallet is incompatible, I just know that it is but I think you should add a message giving the reason so that users can make it work themselves

**Comment by KieronQuinn** [comment]
Added in 1.0.1. It's not enormously verbose - your error will be "Not compatible with your version of Android", as it encompasses both SDK version and OEM firmware incompatibilities
