### ISSUE TITLE
App Crashing on Startup

### ISSUE THREAD

**Issue by MKCOOL142** [KieronQuinn/TapTap#458]
Sometimes the app crashes for me with an empty crash log, so using Scoop for detecting crash logs I got this:
https://katb.in/zafasowigum
And also an empty crashlog with a preview saying "java.net.UnknownHostException: Unable to resolve host "api.github.com": No address associated with hostname" (I didn't have an Internet connection in that moment so mby that's the reason)
Here's also the TapTap crashlog straight from the app, just in case:
[tap_tap_crash_report_2022-01-24T08_24_42.408.txt](https://github.com/KieronQuinn/TapTap/files/7923527/tap_tap_crash_report_2022-01-24T08_24_42.408.txt)

**Comment by MKCOOL142** [comment]
I did some testing and it only crashes without internet, so yeah, a non-existent internet connection causes ne to crash

**Comment by KieronQuinn** [comment]
Fixed in 1.0.1
