### ISSUE TITLE
Notification shade closing issue

### ISSUE THREAD

**Issue by Farow** [KieronQuinn/TapTap#459]
After opening and closing the notification shade, the next double tap action simulates a back button press.

Steps to reproduce:

- Set double tap action to `Open notifications`
- Trigger the double action 3 times.

Expected outcome: notification shade opens
Actual outcome: back button is pressed on the currently active app (while notification shade has already been closed)

Note: Switching to a different app between the second and third double tap produces the expected behavior.

Device: Poco F2 Pro
OS: Android 11/MIUI 12.5.5

**Comment by ElvenSpellmaker** [comment]
I get the same issue, OnePlus 9 Pro, Android 11

**Comment by Siminon** [comment]
Seems relevant to this thread: 

After doubletap opening the notification shade and manually closing it, the next double tap also simulates a back button press. This happens even after switching the app. 

Steps to reproduce:

    

> Set double tap action to Open notifications
> Trigger the double tap action 
> Manually close the notification shade 
> trigger the double tap action 

Expected outcome: notification shade opens
Actual outcome: back button is pressed on the currently active app. 

Device: LG G7 ThinQ / LM-G710EM
OS: Android 10 / V30h-EUR-XX
TapTap: V 1.0

**Comment by KieronQuinn** [comment]
Fixed in 1.0.1
