### ISSUE TITLE
Check for updates.

### ISSUE THREAD

**Issue by sharanvelu** [KieronQuinn/TapTap#46]
It would be helpful if there is an option to check for updates.

**Comment by tjsuominen** [comment]
Just follow GitHub releases, imo, not worth the effort prior play store availability.

**Comment by tolgaaaltas** [comment]
Use "Releases only" option.
![image](https://user-images.githubusercontent.com/10291048/89099913-79af3900-d3fb-11ea-8dc3-8168a3dbdaad.png)

**Comment by KieronQuinn** [comment]
> Just follow GitHub releases, imo, not worth the effort prior play store availability.

It won't ever be on the Play Store. F-Droid maybe eventually, if they allow it with the columbus.jar dependency.

**Comment by tjsuominen** [comment]
Fair enough, GitHub downloads will do just fine.

**Comment by Martin5001** [comment]
Even though watching github releases is an option, I think checking the updates in the app would still be really good addition. (I don't mean downloading the update, just check the current version against github release – I believe github has an API for that so it shouldn't be that much complicated.)

**Comment by sharanvelu** [comment]
There is a simple api with 'GET' HTTP method to get the latest release.
" https://api.github.com/repos/KieronQuinn/TapTap/releases/latest "
This will get the latest release for TapTap.

The property 'tag_name' gives the release name.
Check with the current app and show whether there is an update or not.

Reference : 
https://docs.github.com/en/rest/reference/repos#get-the-latest-release

**Comment by Poussinou** [comment]
@KieronQuinn The colombus.jar won't be allowed during the F-Droid inclusion. It has to be build from source or taken from a trusted repo. Is it possible?

**Comment by KieronQuinn** [comment]
With extensive rewriting of parts of the decompiled code it might be possible, but that would take a lot of effort (which is why it's in a jar file already). Might be easier to just add the GitHub API as suggested.

**Comment by KieronQuinn** [comment]
Forgot to close this with the previous version, it was added using the GitHub API.
