### ISSUE TITLE
App crashing at start on Pixel 4a

### ISSUE THREAD

**Issue by Stimy80** [KieronQuinn/TapTap#460]
Hello! Today I updated the TapTap app to version 1.0 and the app constantly crashes. I'm using a Pixel 4a. 

[tap_tap_crash_report_2022-01-24T12_14_54.212.txt](https://github.com/KieronQuinn/TapTap/files/7925336/tap_tap_crash_report_2022-01-24T12_14_54.212.txt)

**Comment by KieronQuinn** [comment]
Fixed in 1.0.1
