### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by ViperKey** [KieronQuinn/TapTap#464]
The previous version worked quite fine on my oneplus Nord but the newest diesn't work anymore.

**Comment by KieronQuinn** [comment]
Which models and sensitivity levels have you tried?

**Comment by ViperKey** [comment]
All the models and all the senitivity, the double tap works one time and then stops working.
I've re downloaded the 0.8 beta that is the one that works better.

**Comment by KnightTim** [comment]
I can create a separate issue if you would like.  

I just downloaded v1.0.1 and was going through the setup for the first time on my new Sony Xperia 5 iii and it never recognized the taps.  I downloaded v0.9 beta and it works fine. 

I also tried multiple sizes and moved the sensitivity all the way to the highest setting and nothing was detected.

**Comment by ViperKey** [comment]
It's the same for me

**Comment by pro100jekon** [comment]
Samsung S21: app does not work at all, under any circumstances. Every single device/sensitivity was tested.
Please let me know if you need any other info.
Thank you!

**Comment by uae2ae** [comment]
> Samsung S21: app does not work at all, under any circumstances. Every single device/sensitivity was tested. Please let me know if you need any other info. Thank you!

Same here on the S21 Ultra. I have found out legacy medium size on the highest setting detection works. But only at a specific area at the lower right of the device. It's a really small specific area that I can't even repeat most of the time. I'm surprised I even found it after 15 minutes of trial and error. Hope there's someone that would assist on this.

**Comment by pro100jekon** [comment]
> > Samsung S21: app does not work at all, under any circumstances. Every single device/sensitivity was tested. Please let me know if you need any other info. Thank you!
> 
> Same here on the S21 Ultra. I have found out legacy medium size on the highest setting detection works. But only at a specific area at the lower right of the device. It's a really small specific area that I can't even repeat most of the time. I'm surprised I even found it after 15 minutes of trial and error. Hope there's someone that would assist on this.

Yeah, can confirm that. It is a bit strange that I couldn't reproduce that initially.

**Comment by KieronQuinn** [comment]
The core detection code is the same when using a legacy model in 1.0(.1) as in 0.x beta, the "hybrid" is basically just the old code, properly reversed and with a route added to use the new models. If you are using a legacy model, there is no functional difference and there is likely something else at play, for example Tap, Tap now targets Android 12 and is therefore subject to some throttling of sensor data. I added the high sensor rate permission which is *meant* to work around this, but if it's not working on some devices by different OEMs, there is nothing I can do.

On xda, some people found success when they had upgraded from 0.x to 1.0(.1) and it stopped working by clearing the data, please try that and see if it helps. If you have already installed a fresh, this does not apply.

**Comment by grm18** [comment]
> The previous version worked quite fine on my oneplus Nord but the newest diesn't work anymore.

I had reported the same issue for OnePlus 5t, but the dev dismissed vad battery optimisation issue. He should understand the app worked fine beta, which was also mentioned in my issue

**Comment by KieronQuinn** [comment]
> > The previous version worked quite fine on my oneplus Nord but the newest diesn't work anymore.
> 
> I had reported the same issue for OnePlus 5t, but the dev dismissed vad battery optimisation issue. He should understand the app worked fine beta, which was also mentioned in my issue

Please read the comment immediately above yours and report back if it helps.

**Comment by grm18** [comment]
> > > The previous version worked quite fine on my oneplus Nord but the newest diesn't work anymore.
> > 
> > 
> > I had reported the same issue for OnePlus 5t, but the dev dismissed vad battery optimisation issue. He should understand the app worked fine beta, which was also mentioned in my issue
> 
> Please read the comment immediately above yours and report back if it helps.

Hi Kieron,

I have checked and tried the same. It did not work for tap tap 1.0.1. However I installed the beta version and it is working

**Comment by KieronQuinn** [comment]
In that case, there's nothing else I can do. I don't have a device with these issues, and it is impossible to debug something like this remotely. Re-implementing the old code is not feasible due to changes to the core of the app - and modifying it to work would simply end up with the same code as we have now as that's exactly what the changes from 0.10.1 Beta -> 1.0 are. The only cause I can think of is the new sensor restrictions that are limiting something on these devices, but as I am already requesting the high refresh rate data there's nothing further that can be done, sorry. I suggest you keep using 0.10.1 Beta.

**Comment by KieronQuinn** [comment]
The solution in #454 _might_ work here too, so could someone with this issue try disabling the Tensor low power mode in the advanced settings to see if that fixes it?

**Comment by KieronQuinn** [comment]
Tensor Low Power mode is now disabled by default in 1.2, so if the fix does work it will be applied automatically.

**Comment by KnightTim** [comment]
It seems like turning off the Tensor cores worked for me mostly.

On my Sony Xperia 5 iii I did have to set the sensitivity to max and the phone size to largest, for it to be reasonable on taps, IMO. Otherwise it seems like I have to tap extremely hard for it to register.

**Comment by KieronQuinn** [comment]
> It seems like turning off the Tensor cores worked for me mostly.
> 
> On my Sony Xperia 5 iii I did have to set the sensitivity to max and the phone size to largest, for it to be reasonable on taps, IMO. Otherwise it seems like I have to tap extremely hard for it to register.

The sizes are only for reference, while they work for a lot of devices it's not guaranteed that the closest will be the best due to sensor locations and other factors. Glad it's working for you now.
