### ISSUE TITLE
Tap Tap just crashes

### ISSUE THREAD

**Issue by JacksonCampbell99** [KieronQuinn/TapTap#465]
I just updated to the latest version, and after turning it on, it immediately crashed and has continued crashing since every time I attempt to open the application.
Here's one of the crash reports: 
[tap_tap_crash_report_2022-01-24T12_40_05.65.txt](https://github.com/KieronQuinn/TapTap/files/7928805/tap_tap_crash_report_2022-01-24T12_40_05.65.txt)

**Comment by KieronQuinn** [comment]
This is already fixed in 1.0.1.
