### ISSUE TITLE
Crash when opening app after updating to 1.0

### ISSUE THREAD

**Issue by StarLuigi05** [KieronQuinn/TapTap#467]
[tap_tap_crash_report_2022-01-24T23_06_41.079.txt](https://github.com/KieronQuinn/TapTap/files/7930546/tap_tap_crash_report_2022-01-24T23_06_41.079.txt)

I open the app and it immediately crashes. The taps no longer work

**Comment by KieronQuinn** [comment]
This is already fixed in 1.0.1
