### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by creeperlulu** [KieronQuinn/TapTap#474]
Tap Tap crashes on app launch after update. I'm on Google Pixel 4a, Android 12. Here is my crash report.
[tap_tap_crash_report_2022-01-27T20_56_21.181.txt](https://github.com/KieronQuinn/TapTap/files/7953447/tap_tap_crash_report_2022-01-27T20_56_21.181.txt)

**Comment by KieronQuinn** [comment]
This is already fixed in 1.0.1
