### ISSUE TITLE
When manually disabled, Tap, Tap reenables itself on boot

### ISSUE THREAD

**Issue by digitalcircuit** [KieronQuinn/TapTap#475]
## In brief
* Disabling Tap, Tap is not remembered across reboots
  * Uncheck `Enable Tap, Tap`, reboot, check if Tap, Tap is running
  * Keeping Tap, Tap installed but with the service disabled allows for update checks, etc

## Steps
1.  Install Tap, Tap
2.  Go through setup
3.  Uncheck `Enable Tap, Tap` on the app homescreen
4.  Observe that the `Tap, Tap Service` notification disappears and the service stops
5.  Reboot the phone
6.  Observe notifications

### Expected
Tap, Tap service remains disabled after reboot.

### Actual
Tap, Tap service launches on boot, possibly [due to a missed check in the `TapTapServiceStartReceiver.kt`](https://github.com/KieronQuinn/TapTap/blob/5a648d795c1f12cdd4930d548eb745f5a5f21713/app/src/main/java/com/kieronquinn/app/taptap/receivers/TapTapServiceStartReceiver.kt ) or maybe something else doesn't persist.

### Details
* Device: Pixel 4 XL
* Android version: Android 12 (`SQ1A.220105.002`)
* Tap, Tap version: `1.0.1`

*I plan to make use of Tap, Tap in the future, especially with the recent 1.0 update.  However, I'm not yet ready to configure it fully and I'd prefer to not uninstall it entirely just to keep the service disabled in the meantime.*

**Comment by KieronQuinn** [comment]
Fixed in 1.1, thanks for the report.
