### ISSUE TITLE
Samsung Galaxy Z fold 3 detected as Samsung Galaxy Tab S3 9.7

### ISSUE THREAD

**Issue by Thepokefreek** [KieronQuinn/TapTap#477]
ADB
Shizuku: 12.4

Version: 1.0.1
Device: Z Fold 3
API Version: 31

Foldable options not available because wrong device detected.

**Comment by KieronQuinn** [comment]
The device detection for the model size is unrelated to the foldable options. Are the foldable gates not available for you?

**Comment by Thepokefreek** [comment]
No they aren't.

**Comment by KieronQuinn** [comment]
In that case, your device is not compatible with the version of "Sidecar" used. It's not possible to use a newer version from a service, so this cannot be fixed.
