### ISSUE TITLE
The Gates not working 

### ISSUE THREAD

**Issue by yZhentan** [KieronQuinn/TapTap#479]
I open the Gates>App showing>Blocks gesture when Genshin Impact is showing on screen.

But it is not working，when I play Genshin /and other apps I add to Gates，it still can launch the gesture.
（I have recorded video，shall I email u the video or wat？）
![IMG_20220131_12063070](https://user-images.githubusercontent.com/71588862/151737519-0fb84a47-ea44-4306-855b-e25d81db47c5.jpg)

**Comment by KieronQuinn** [comment]
Make sure the accessibility service is enabled. If it is, there's nothing I can do as there is no other stable and global way to monitor the current app.

**Comment by yZhentan** [comment]
> Make sure the accessibility service is enabled. If it is, there's nothing I can do as there is no other stable and global way to monitor the current app.

I just remember the Android has this permission“Usage access”，this permission allows an app to track what other apps you're using and how often, as well as your carrier, language settings and other details.
I think maybe u can try use this to let Tap,Tap can track what apps are using.
（my phone is OPPO，dunno is it all Android got this access，but at least u can try this way）
![Screenshot_2022-02-12-00-15-01-20_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/71588862/153628569-331bfa3e-9a3a-4029-9e74-76791094329f.jpg)
![Screenshot_2022-02-12-00-15-18-05_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/71588862/153628580-421d5890-007a-41f2-8c28-7a6c38b3c881.jpg)

**Comment by KieronQuinn** [comment]
> > Make sure the accessibility service is enabled. If it is, there's nothing I can do as there is no other stable and global way to monitor the current app.
> 
> I just remember the Android has this permission“Usage access”，this permission allows an app to track what other apps you're using and how often, as well as your carrier, language settings and other details. I think maybe u can try use this to let Tap,Tap can track what apps are using. （my phone is OPPO，dunno is it all Android got this access，but at least u can try this way） ![Screenshot_2022-02-12-00-15-01-20_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/71588862/153628569-331bfa3e-9a3a-4029-9e74-76791094329f.jpg) ![Screenshot_2022-02-12-00-15-18-05_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/71588862/153628580-421d5890-007a-41f2-8c28-7a6c38b3c881.jpg)

That feature is not suitable for this, it's slow and requires an always running service checking periodically (which uses CPU and battery). The only alternative is a UidObserver, which needs root or an ADB service.
