### ISSUE TITLE
Not working on Redmi Note 8

### ISSUE THREAD

**Issue by Hunter2807** [KieronQuinn/TapTap#48]
Hello

I have this app on my Redmi Note 8 6+128 gb and the gestures does not work... I have tried a number of times...

**Comment by deanytb** [comment]
On my redmi note 8 works good

**Comment by tolgaaaltas** [comment]
> On my redmi note 8 works good

Could you share your settings with us?

**Comment by XpressU** [comment]
Pixel 4 
Open app and flashlight
Accessibility Granted
Except call all the other gates are disabled

**Comment by busybox11** [comment]
You can see my answer [here](https://github.com/KieronQuinn/TapTap/issues/53#issuecomment-667560741).

_Sent from my Redmi Note 8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by KieronQuinn** [comment]
Please try what @busybox11 suggested on the duplicate ticket and report back.

**Comment by KieronQuinn** [comment]
Please try with the new update, specifically trying one or both of the new advanced options.

**Comment by KieronQuinn** [comment]
Now covered by #354, follow the steps on there and if it still doesn't work then there's nothing I can do.
