### ISSUE TITLE
Tap, Tap unpauses videos on social media apps.

### ISSUE THREAD

**Issue by tomasventura13** [KieronQuinn/TapTap#485]
This is a bug that I did not have in the versions prior to 1.0, but now everytime I use the double tap feature to turn on the flashlight, a video that I'm watching pauses or unpauses and it's not only with social media apps.

**Comment by KieronQuinn** [comment]
This is due to Android system changes, you can no longer use the camera from a background service so the app has to briefly start an activity, which pauses videos in some apps. There is no workaround.
