### ISSUE TITLE
Gate for Snapchat doesn't work

### ISSUE THREAD

**Issue by kalyway101** [KieronQuinn/TapTap#489]
I have a gate in place that if Snapchat is open, and you double tap, it won't take a screenshot. 

However, the gate doesn't seem to be working. I tested it with Messages and the gate is active. Double tap does nothing. 

I'm running TapTap v1.1
S21 Ultra

**Comment by KieronQuinn** [comment]
The app running gate is using the only method it can without running a high-CPU intensity service or using root/ADB perms. It relies on the system to inform it which app is open (via accessibility), if that's not working there's nothing I can do, sorry.
