### ISSUE TITLE
TapTap on Samsung Galaxy S10 Plus US variant

### ISSUE THREAD

**Issue by horacioj** [KieronQuinn/TapTap#493]
TapTap on Samsung Galaxy S10 Plus US variant, single action: turn off screen when the screen is on.

- 0.9 beta 9: working great
- 0.10.1: gesture doesn't work
- 1.2: gesture work, but it "bounces back". I.e, the screen is turned off but immediately turned on again. In summary, it doesn't work.

HTH

Great app! I'll keep running TapTap 0.9

**Comment by KieronQuinn** [comment]
You probably have the feedback option "Wake Device" enabled.

**Comment by horacioj** [comment]
Yes, that was it. Thanks!

**Comment by horacioj** [comment]
Anyway, FYI, I'm back to TapTap 0.9. I tried (I think) every possible settings on 1.2, but the service stops working after some time. This doesn't happen on 0.9. Yes, I know about https://github.com/KieronQuinn/TapTap/issues/354, this isn't a issue about the service being killed. However, on the same device, 0.9 isn't killed, and 1.2 is killed ¯\_(ツ)_/¯

**Comment by KieronQuinn** [comment]
It's probably restrictions on newer apps, there's nothing I can do like 354 says. It never gets killed on a Pixel with no restrictions.
