### ISSUE TITLE
The disclosure icon performs "Prev" button action

### ISSUE THREAD

**Issue by VladWinner** [KieronQuinn/TapTap#495]
![Screenshot_20220223-044930_Tap, Tap](https://user-images.githubusercontent.com/13555921/155250044-ef0cdd87-d4d8-4ba0-91df-ed1ce2ee9824.jpg)

https://user-images.githubusercontent.com/13555921/155250060-5e96fa5a-e4fc-46e9-86f6-8b8a4cbaf096.mp4

I see two options:
1) Replace the icon with "arrow_back_ios" (in collapsed state)
2) Add a separate button to go to the previous screen

**Comment by KieronQuinn** [comment]
Fixed in 1.4
