### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ImadYamani** [KieronQuinn/TapTap#497]
The app is not working on my Redmi note 10 5G

**Comment by KieronQuinn** [comment]
You will need to provide much more information than that.

What Android version / firmware, what app version, does it work during setup, have you tried all the model sizes, have you tried changing the sensitivity (and combining model size changes / sensitivity changes)?

**Comment by ImadYamani** [comment]
I try everything and still not working

**Comment by KieronQuinn** [comment]
Closing as invalid as you are not providing sufficient information.
