### ISSUE TITLE
Emui 9 doesn't turn on the screen

### ISSUE THREAD

**Issue by MKCOOL142** [KieronQuinn/TapTap#50]
As a emui 9 user I know that Huawei isn't the best at coding so I imagine that they messed with the code and simultaneously broke your app, it'd be nice if you either add a different wake screen code (because other apps can also waje the screen on emui 9, I assume it's because they require the system administrator permission) this isn't a big deal but I imagine you would make a few people happy

**Comment by KieronQuinn** [comment]
Could you please provide a link to one of the apps that does work with waking up (ideally an open source one)?

**Comment by MKCOOL142** [comment]
> Could you please provide a link to one of the apps that does work with waking up (ideally an open source one)?

https://gitlab.com/juanitobananas/wave-up

This one is open source and technically has a different use case but it turns on the screen and that's what matters, I hope you find it useful!

**Comment by kentnek** [comment]
I realize the Wake screen feature is not working on my Pixel 3XL too. Is it a similar bug?

**Comment by KieronQuinn** [comment]
Fixed in 0.10 beta
