### ISSUE TITLE
Doesn't work when screen is off

### ISSUE THREAD

**Issue by devmdeniz** [KieronQuinn/TapTap#503]
I use Poco X3 Pro.

in requirements part, i selected the "Display off" requirement but when i close the screen and try the event (Next Music), it doesn't work and i didn't get any notification about crashes or permissions. (i tried 2 different event (Next Music and Flashlight but doesn't work)

**Comment by KieronQuinn** [comment]
Have you disabled or removed the screen off gate, which is default enabled?

**Comment by devmdeniz** [comment]
I didn't do anything other than the permissions the app asked for.  Can you provide information on how to do it (Or add a section to the app about it)

**Comment by KieronQuinn** [comment]
Gesture > Gates > turn off the Display Off gate.
