### ISSUE TITLE
Doesn't work when screen is off

### ISSUE THREAD

**Issue by devmdeniz** [KieronQuinn/TapTap#506]
https://github.com/KieronQuinn/TapTap/issues/503
I did what you said but still can't get it to work
![1648829057684](https://user-images.githubusercontent.com/68655812/161300739-660d1d66-e6fc-4650-b2d4-d06d41e8a827.jpg)
![1648829057693](https://user-images.githubusercontent.com/68655812/161300744-2556cbec-a409-4e39-a75a-f9a15f7dc104.jpg)

**Comment by KieronQuinn** [comment]
Have you tried rebooting? It may simply be stuck.

**Comment by devmdeniz** [comment]
> Have you tried rebooting? It may simply be stuck. 

yes, doesn't work again (I've tried to much times)

**Comment by KieronQuinn** [comment]
I have no idea what is happening then. Disabling the display off gate is enough for everyone else, all I can suggest is make sure battery 'optimisations' are disabled as they may kill apps with the screen off. There is nothing else I can do.

**Comment by devmdeniz** [comment]
> I have no idea what is happening then. Disabling the display off gate is enough for everyone else, all I can suggest is make sure battery 'optimisations' are disabled as they may kill apps with the screen off. There is nothing else I can do.

I think it may be a different API or permission function for MIUI.

Thank you for your help

**Comment by devmdeniz** [comment]
> MIUI never exposes permissions or APIs, it is always on the user to disable settings. They don't consider developers. All i can suggest is checking the settings like I said.

I've already checked settings. So we can't do anything in this situation. Anyways, thanks again for your time
