### ISSUE TITLE
Lock/Unlock Gate

### ISSUE THREAD

**Issue by janikmu** [KieronQuinn/TapTap#51]
Hi, really a nice "backport" of the Tap Tap Feature.

What I would like to see is a Gate that is active when the device is locked. The screen can be active (there is a gate for this already, so if one does not use a lockscreen, this can be used), but when the lockscreen is still active (not unlocked) it should be cobfigurable to prevent the Tap Tap action through this gate.

The need/idea comes from the action firing a lot when I pick up my phone (Pixel 4 XL) to view notifications but without unlocking it. I usually unlock it (or face unlock does it) after picking it up. So the gate (maybe with  a half a second delay similar to USB gates) would "open" after the potentially misinterpreted action of picking up the device happened. 

Happy to hear your thoughts!

**Comment by KieronQuinn** [comment]
Not sure this is possible (I looked at it before releasing), but I'll see if there's something I missed

**Comment by janiksudo** [comment]
What about using the KeyguardManager?

**Comment by KieronQuinn** [comment]
Using `isKeyguardSecure` was causing issues from memory, but I can't remember what. I'll have a look again.

**Comment by KieronQuinn** [comment]
Added in 0.9 beta using a workaround.
