### ISSUE TITLE
Launch reachability Enhancement

### ISSUE THREAD

**Issue by EAZY5D** [KieronQuinn/TapTap#510]
I really love this feature. But this 2 issues ⚠️ Make me want tear my skin off.

1. Everytime I try 2 get out of the mode with the same. " 3 tap gesture " it takes me back to my phone home page. Normally it should close the top tap tap view and allow the bottom view which is the current app to get back to fullscreen. See Video

https://user-images.githubusercontent.com/55167211/163765111-55211105-a205-4563-b98d-dfd2fcb82969.mp4

2. This is more of a feature request still same topic though Could u pls allow the launch reliability to remember the last used adjustment, look at my video above.

Everytime I open it up it is just too "**Middle**" for me so I have 2 always drag it to a sweet spot every single time

**Comment by KieronQuinn** [comment]
Neither of these are possible as the system controls the split screen.
