### ISSUE TITLE
Torch bug

### ISSUE THREAD

**Issue by EAZY5D** [KieronQuinn/TapTap#511]
I don't really know if this is a bug or if it is the way it was implemented but see the video.

Everytime the keyboard disappears or smt I am doing in fullscreen cancles even 1 other scenario I can't seem to reproduce I am using " **I am using the 2 tap gesture** " to turn on the flash light.

https://user-images.githubusercontent.com/55167211/163766570-bfced9b4-246c-43e0-b544-c7b08976eecc.mp4

**Comment by KieronQuinn** [comment]
Not a bug, this is how it's implemented as services cannot access the camera from the background any more.
