### ISSUE TITLE
Taps not registering well on S21 Ultra

### ISSUE THREAD

**Issue by KeyShr3kt** [KieronQuinn/TapTap#515]
I've been trying to set the app to run on my S21 Ultra by messing with the settings in any way possible, but none of them worked.
The taps sometimes register, but very late and just once, not two times required to do a task, and other times the phone registers taps out of nowhere. Please help!

**Comment by KieronQuinn** [comment]
There is nothing I can do about this. Make sure you've allowlisted the app from any battery optimisations, and make sure you've tried all the models and sensitivity levels. You should also have Tensor low power mode OFF as it's known to cause issues on that device. Other than that, nothing can be done without having the device physically in my hands to test.

**Comment by KeyShr3kt** [comment]
> There is nothing I can do about this. Make sure you've allowlisted the app from any battery optimisations, and make sure you've tried all the models and sensitivity levels. You should also have Tensor low power mode OFF as it's known to cause issues on that device. Other than that, nothing can be done without having the device physically in my hands to test.

Thank you for the very quick reply!
I'll try the above mentioned tips and if they don't work I hope I will find a workaround to the problem.
