### ISSUE TITLE
Tap, tap don't work on redmi note 8 pro

### ISSUE THREAD

**Issue by octoberdocx** [KieronQuinn/TapTap#518]
Android version:10
Miui version:12.0.8 global
Doesn't pass the start screen on the newest version
And have no response to it

**Comment by KieronQuinn** [comment]
Please provide more info, does it crash, does the button not work? Do you get no response to the gesture?

**Comment by octoberdocx** [comment]
The app doesn't crash, the buttons do work. but it need to trun the sensitivity the very high in order to trigger one tap. But sometimes it do work but sometimes not

**Comment by KieronQuinn** [comment]
#48
