### ISSUE TITLE
Play Store / F-Droid availability?

### ISSUE THREAD

**Issue by kvngvikram** [KieronQuinn/TapTap#521]
Is it possible to install this app from any app store?
So that I don't have to worry about updates, and how to update, instead of downloading apks myself.

Thank you.

**Comment by KieronQuinn** [comment]
F-Droid wouldn't be allowed due to the closed source dependencies (Play Services OSS). Play Store would get my account banned, so is also a no.

The app has a built in updater instead.

**Comment by mon-jai** [comment]
@KieronQuinn Is it possible to build an version of the app without Play Services?

Having the app in F-Droid would make it more easy to find.

**Comment by KieronQuinn** [comment]
> @KieronQuinn Is it possible to build an version of the app without Play Services?
> 
> Having the app in F-Droid would make it more easy to find.

See the same issue on DarQ for a response to that: https://github.com/KieronQuinn/DarQ/issues/53

**Comment by CompeyDev** [comment]
> F-Droid wouldn't be allowed due to the closed source dependencies (Play Services OSS). 

I mean, IzzyOnDroid is an option in that case, no?

**Comment by KieronQuinn** [comment]
> What was reasoning for your apps being removed? Since IzzyOnDroid mainly exists to allow for such apps which may have proprietary blobs.

In-app updaters are not allowed and accessibility services need to be opt-in (even though they already are, apparently it's not sufficient to actually have the user physically press the "enable" button). 

I don't adapt my apps to the whims of stores I don't submit to basically, that's one of the reasons I no longer publish to Google Play either.
