### ISSUE TITLE
Stuck on tap tap service loading

### ISSUE THREAD

**Issue by nirajjn76** [KieronQuinn/TapTap#526]
Stuck on Tap tap setvice is loading on lg g8x. Before it was working fine.

**Comment by KieronQuinn** [comment]
Reboot your device

**Comment by nirajjn76** [comment]
Brother, what makes you think i haven't tried rebooting, clearing cache, uninstall and install again the app etc? Tried everything. No software update was applied when this issue occurred. no changes were made into file system. Tap tap just stopped working out of the blue.

**Comment by KieronQuinn** [comment]
Because you gave absolutely no indication that you have done any of those things. Provide a log with a crash and I will reopen, but for now there is insufficient information to do anything.

**Comment by nirajjn76** [comment]
Tried to find logs but couldn't. Where are tap tap logs generated in the device?

**Comment by KieronQuinn** [comment]
https://www.xda-developers.com/how-to-take-logs-android/

A system log is required

**Comment by nirajjn76** [comment]
Oh okay. I thought taptap saves logs on itself. Will provide you with logs. Thank. You.
