### ISSUE TITLE
App cannot be launched by tap tap

### ISSUE THREAD

**Issue by Sneaczy** [KieronQuinn/TapTap#530]
Tap tap cannot launch the app when not in tap tap ui app.

Model: Redmi K20pro
Android version: 11
Tap tap version:1.3

**Comment by KieronQuinn** [comment]
Using MIUI?

**Comment by Sneaczy** [comment]
yes

**Comment by KieronQuinn** [comment]
#403

**Comment by Sneaczy** [comment]
For future possible ppl, the settings should be displayed pop-up window while running in background
Anyway thx Kieron
