### ISSUE TITLE
Tap Tap Install

### ISSUE THREAD

**Issue by jpaterjr** [KieronQuinn/TapTap#533]
I tried to download Tap Tap .apk but file downloaded was .bin. I don't know how to install a .bin file in Android (Samsung S20).

**Comment by Kirkalic** [comment]
Sorry, I'm busy. I'll reply shortly.

**Comment by KieronQuinn** [comment]
If you downloaded the .apk from the [releases page](https://github.com/KieronQuinn/TapTap/releases), you may need to rename it to .apk, some browsers rename the files when downloading for some reason.
