### ISSUE TITLE
Tasker event not triggered

### ISSUE THREAD

**Issue by pierremont** [KieronQuinn/TapTap#535]
Hi!
I'm a big fan of your app, I think it's a wonderful idea
Alas I couldn't set it up to trigger the TAsker event, maybe I'm doing something wrong?

I've set up Tap Tap (1.4) in the Double Tap Actions setting to be Tasker event, but it doesn't seem to trigger Tasker
within tasker I've created a simple profile with a context Double Tapped Back that just flashes "ok" on the screen
I know Tap tap is reacting because i feel a feedback tap right after my double taps. Also, if I choose a specific task for Double Tap action instead a Tasker event - it works

Thank you

**Comment by KieronQuinn** [comment]
Unable to reproduce

![image](https://user-images.githubusercontent.com/3430869/185111617-480a45b4-5171-4fd5-84f6-2dd9dac04a4c.png)
![image](https://user-images.githubusercontent.com/3430869/185111627-b4898b70-75e2-40e7-94a0-43d3d2af8509.png)

This works fine for me.

**Comment by pierremont** [comment]
which phone model are you using?
I'm using a Pixel 5, just as the Tasker developer's

I've used Tasker for about 5 years, actively developing tasks, so there must be something there. Maybe a missing permission through ADB?

**Comment by pierremont** [comment]
i've now let only the Flashlight action for Double Tap, the one from your screenshot - and it doesn't trigger the flashlight alone either
there is a tap back, though, so it reacts, somehow
so far, the only way to use it is to configure an actual Tasker task in there.

Can Tap Tap log its actions in a file?

**Comment by KieronQuinn** [comment]
Have you got the draw over other apps permission enabled?

**Comment by pierremont** [comment]
yes, sir


![image](https://user-images.githubusercontent.com/51104314/185114359-64040b50-4ee1-42d3-83dd-60726b74094b.png)

**Comment by pierremont** [comment]
using Tasker logcat event I've managed to capture system logs when TapTap was supposed to trigger
there's an interesting event there from taptap
As you can see it's trying to trigger a Tasker Task called com.local.petrus.aimp_rewind_tasker. The problem is that i used that task before in TapTap, but it's no longer set up in there

it seems that TapTap doesn't forget that old setting, for some reason. Now in Double Tap Action it's set up Tasker event
I've cleared the storage and cache for TapTap, but it's doing the same. I don't know where it stores that old setting...

![WhatsApp Image 2022-08-17 at 3 11 01 PM](https://user-images.githubusercontent.com/51104314/185116684-df581e83-8205-4343-8dd9-0c6b815593ba.jpeg)

**Comment by KieronQuinn** [comment]
The first item in that log is it being blocked from starting a service in the background - make sure you have disabled battery optimisation for both Tap, Tap and Tasker. 

As for it using the wrong tasker task, that is handled by Tasker if you are using the Tasker Event action. Only the Tasker Task action fires specific actions.

**Comment by pierremont** [comment]
the battery optimisation is stopped completely on my phone, and I'm using the phone right now, it couldn't intervene anyway

I don't mean to question anything, but are you sure Tasker is triggering the specific task?
In the first event - the one which is blocked - it says "RequestedQuery from ... package taptap" and it references the wrong task

thank you

**Comment by KieronQuinn** [comment]
Yes, the Tasker Event action was implemented by the Tasker developer and has worked fine since then.

**Comment by pierremont** [comment]
Then I guess that's it
thank you
