### ISSUE TITLE
Delay in action after double tap

### ISSUE THREAD

**Issue by shamilsherhan** [KieronQuinn/TapTap#536]
Hi,

Whenever I double tap, there is a huge delay in getting response, even from the setup page. I'm talking about delays that lasts more than 5-10 seconds.

I have adjusted the sensitivity as well as screen size. I have also checked the accelerometer and they work fine an on time.

Device: Nothing Phone (1)
OS: Android 12

**Comment by KieronQuinn** [comment]
Nothing I can do. The sensor code is standard, and uses a model that is not possible to modify.
