### ISSUE TITLE
doesnt seem to be working on the nothing phone 1

### ISSUE THREAD

**Issue by shailantani** [KieronQuinn/TapTap#537]
heyy good day, I tried to use the app on the nothing phone 1 but it just doesnt seem to recognise the sound. Tried on all the sizes with all the sensitivities. Any solution? Thanks and cheers!

**Comment by KieronQuinn** [comment]
#536

**Comment by Kirkalic** [comment]
Sorry, I'm busy. I'll reply shortly.
