### ISSUE TITLE
Only vibrates when i double tap

### ISSUE THREAD

**Issue by OhMyDaysFam** [KieronQuinn/TapTap#539]
So i made double tap action to be my flashlight but when i doubletap my phone on homescreen my phone only vibrates ....when im in the TapTap app and double tap my phone the action works perfectly .....can someone help ? My device is poco x3 pro with android 12

**Comment by KieronQuinn** [comment]
You need to make sure draw over other apps is enabled, and possibly disable some MIUI optimisation too. This isn't a Tap, Tap bug but is a system limitation.
