### ISSUE TITLE
Inconvenience with the lock of gates.

### ISSUE THREAD

**Issue by LucasDRavarotto** [KieronQuinn/TapTap#543]
What does the recognition of the applications work in the section of floodgates where you want to block the gesture when a certain application is opened, it just does not recognize and does not work. For example, PUBG New State, PUBG Mobile, COD Mobile, camera, etc.
And neither does the blocking when recognizing the device in pocket and on the table

**Comment by KieronQuinn** [comment]
If none of those are working that suggests the app isn't being allowed to work properly in the background. There's nothing I can do in this case, check that you have disabled any battery "optimisation" for Tap, Tap.
