### ISSUE TITLE
[NOT WORKING] Nothing Phone 1

### ISSUE THREAD

**Issue by yasinerarslan** [KieronQuinn/TapTap#544]
It doesn't work even though I tried different versions on Nothing Phone (Android12). What would be the reason? Has anyone had or solved this problem?

**Comment by KieronQuinn** [comment]
Insufficient information, does it crash? Does it work during setup? Does it work sometimes but not always? Have you tried all the combinations of models/device sizes, sensitivity options etc.?

Will reopen if actual information is provided showing an app bug, but it's very unlikely to be something that can be solved.
