### ISSUE TITLE
Samsung Galaxy S21FE not working

### ISSUE THREAD

**Issue by Zedliminal** [KieronQuinn/TapTap#549]
Just downloaded the latest version on my phone and it is not working at all, tried setting the sensitivty to max, changing the phone size, and also removing my case, but nothing works.. I also noticed that it apparently crashed, so I am attaching the log here.
[tap_tap_crash_report_2022-10-20T19_20_09.756.txt](https://github.com/KieronQuinn/TapTap/files/9834709/tap_tap_crash_report_2022-10-20T19_20_09.756.txt)

**Comment by KieronQuinn** [comment]
#515 

As for the crash, nothing I can do. startForegroundService is called immediately, it could not be quicker.
