### ISSUE TITLE
Feature: flashlihgt timer

### ISSUE THREAD

**Issue by aspidxt** [KieronQuinn/TapTap#550]
Would be nice to have some flashlight turn-off timer, which will be activated when flashlight turns on by double tap. This will protect from battery drain on false activation.   For ex, I have issues when I'm riding, and only there, so I don't want to lower senivity to non-comfotable level

**Comment by KieronQuinn** [comment]
If it's triggering in your pocket, I suggest using the Pocket gate. More complex actions like the one you've suggested are not within the scope of Tap, Tap and should use the Tasker plugin.
