### ISSUE TITLE
Nothing phone 1 - taps not registered/ delayed 

### ISSUE THREAD

**Issue by AnirudhN1508** [KieronQuinn/TapTap#551]
Nothing phone 1 I've tried most combinations of sizes and sensitivity

The app doesn't recognise any of the taps 

It eventually recognised some and proceeded to open the assistant multiple times 

Not sure how to resolve this

**Comment by KieronQuinn** [comment]
If it worked at all, then the app is working. You either need to find the right combination still or make sure it's excluded from any battery "optimisations"

#354
