### ISSUE TITLE
Samsung Backtap

### ISSUE THREAD

**Issue by IzzySoft** [KieronQuinn/TapTap#554]
Out of interest: does the Samsung Backtap library (`/com/samsung/android/backtap`) belong to TapTap and thus falls under the app's license, or was it imported from somewhere? There are no notes/comments in the code to find out, and I could not find it elsewhere.

Thanks in advance for clarification!

**Comment by KieronQuinn** [comment]
Much like Columbus, it's reverse engineered. The models are a grey area.

**Comment by IzzySoft** [comment]
Thanks!

**Comment by IzzySoft** [comment]
PS: Does `/com/google/android/odml/image` ([from Google's MLKit](https://developers.google.com/android/reference/com/google/android/odml/image/package-summary)) belong into the same corner? It's the only reference I see from MLKit.
