### ISSUE TITLE
Add swipe gestures

### ISSUE THREAD

**Issue by jacksongoode** [KieronQuinn/TapTap#555]
A number of older apps were able to take advantage of the ability to detect directional swipes on the fingerprint reader. I believe this might vary by API available (I know Pixel devices have access to it).

I'll see if I can find an OSS app that implements this and add it.

**Comment by KieronQuinn** [comment]
Not possible, the models don't support this. Integrating with a fingerprint sensor is out of scope for this app.

**Comment by jacksongoode** [comment]
Sorry, I totally thought this was intended as taps on the fingerprint sensor! My bad 😆 !
