### ISSUE TITLE
App is misfunctioning

### ISSUE THREAD

**Issue by powersagitar** [KieronQuinn/TapTap#556]
The app can't follow all the listed instructions when the double tap is detected.
For example, I want to simulate the home button and lock my phone when a double tap is detected (in the exact order), but the app can only perform simulating the home button.
Config file is attached.
[backup_2022-11-10T20_45_03.461.taptap.zip](https://github.com/KieronQuinn/TapTap/files/9985829/backup_2022-11-10T20_45_03.461.taptap.zip)

**Comment by KieronQuinn** [comment]
Please post a screenshot of your double tap actions list

**Comment by KieronQuinn** [comment]
You're misunderstanding how actions work, only the first one will be executed. For complex sequential flows, use something like Tasker.
