### ISSUE TITLE
Question/issue

### ISSUE THREAD

**Issue by Ziga440** [KieronQuinn/TapTap#557]
I can not use the Foldable : Device Folded (closed) gesture. I am using the Z Flip 4 and i don't know if it is only for the fold or the flip also?

**Comment by KieronQuinn** [comment]
It depends on [FoldingFeature](https://developer.android.com/reference/androidx/window/layout/FoldingFeature), but a legacy version as newer ones cannot be used from a background service. Unfortunately there's no workaround for this, so I can't do anything about it if your device doesn't support it.
