### ISSUE TITLE
App is overloading the system (CPU)

### ISSUE THREAD

**Issue by powersagitar** [KieronQuinn/TapTap#558]
CPU: Snapdragon 888
I don't know what else I'm supposed to provide at this moment, so I only attached the error screenshot. If more info is needed, please comment on this issue.
![Screenshot_20221118_092802_Device care](https://user-images.githubusercontent.com/114868133/202750895-2e4b8213-3a15-4693-90b0-4d56a1d5ea9c.png)

**Comment by KieronQuinn** [comment]
This is normal, it's doing sensor processing.
