### ISSUE TITLE
Samsung galaxy Note 9 Rooted (Android 12): no detection

### ISSUE THREAD

**Issue by Vaarlion** [KieronQuinn/TapTap#559]
Hi :)
Sorry for the lack for formatting, i didn't know what you'll prefer
I wanted to try this app on my rooted Note 9. I've installed the v1.5, run the setup with internet so it could get the setting of my device... and during the setup, i can't get it to detect the tap gesture.
I've try increasing the sensitivity to max without success
I've try to remove my case
I've skip the setup, added an action that require root just in case, allowed root, and redo the setup, same

Would they be any step that I'm missing ? Any extra log or debug i can get ?

**Comment by KieronQuinn** [comment]
If it doesn't work during setup, there's nothing I can do. Just make sure you've tried all the combinations of device sizes and sensitivity, beyond that it's probably a device or hardware incompatibility.

**Comment by Vaarlion** [comment]
I've seen other ticket on the samsung note 9, may i ask what does it use that could be compatible on some but not all device ?
I've read it's gyro based, so i don't see why it wouldn't work ?

Also, does it need root to work on none-pixel device ?
I never asked for it.
