### ISSUE TITLE
Cannot turn on Accessibility Service 

### ISSUE THREAD

**Issue by Kadiya99** [KieronQuinn/TapTap#565]
My device is A13 (CrDroid custom rom 9.1) 
I'm update the app and it's showing cannot turn on Accessibility Service like this image.
![Screenshot_20230210-131035_Settings](https://user-images.githubusercontent.com/49185138/218032512-827bbee9-05d3-42f5-8c20-d7ed28b46c49.png)

Reboot the device and reinstall it but nothing worked

**Comment by KieronQuinn** [comment]
You need to allow unrestricted settings: https://support.google.com/android/answer/12623953?hl=en
