### ISSUE TITLE
Glitch on Moto G52

### ISSUE THREAD

**Issue by supermegamestre** [KieronQuinn/TapTap#566]
Here's a glitch I found out.
I have my tap tap set to open the notification panel on 2 taps, and I discovered that whenever I locked the screen and unlocked it there was a chance that the program would simply be unable to execute the gesture until I opened the notification panel myself manually, the service is still running as signaled by the vibration from whenever I triggered the gesture.
Sometime later I set up the triple tap to open the quick settings menu as a test, and I discovered that when this glitch of not opening the notification panel happened, triggering the triple tap would instead open the notification panel, and then both gestures would work normally.

**Comment by KieronQuinn** [comment]
#516

**Comment by supermegamestre** [comment]
I'm sorry I'm a bit lost, why is it marked as closed?

**Comment by KieronQuinn** [comment]
Because your issue is a duplicate. This cannot be resolved, it's because of how Android works.

**Comment by supermegamestre** [comment]
Oh I see, can you explain to me in details why is that?

**Comment by KieronQuinn** [comment]
The details are already in the linked issue.
