### ISSUE TITLE
Feature Request: Enable / Disable TAPTAP from Tasker

### ISSUE THREAD

**Issue by Tomo-az0** [KieronQuinn/TapTap#569]
TapTap version 1.0.1 allows Tasker to START/STOP it using intents as this links describes. https://github.com/KieronQuinn/TapTap/issues/421#issuecomment-1019515847

Version 1.01 worked fine.

However, it does not work with the latest version. 
How can I get it to work from Tasker with the latest version of TapTap?

**Comment by KieronQuinn** [comment]
#541
