### ISSUE TITLE
Launching apps shortcuts with shizuku

### ISSUE THREAD

**Issue by saravanasg** [KieronQuinn/TapTap#570]
I've mapped my triple tap gesture to open an app shortcut using shizuku. However, the app doesn't get launched even though I get triple tap's vibration feedback.
It works totally perfectly with just opening apps and other stuff.
(Same behaviour with double tap)

**Comment by KieronQuinn** [comment]
Please post a logcat, it should be showing an error if it can't be launched. Also which device, Android version?

**Comment by saravanasg** [comment]
I don't get any error when that happens. I get the vibration feedback and that's it.
iQOO 9 SE (Vivo), Android 13

**Comment by KieronQuinn** [comment]
The error won't be visible, it will only be in logs.

**Comment by saravanasg** [comment]
Where can I find the logs?
By the way something interesting happened.....I turned off the notifications. So I thought I'll get an error notification if I turn them on. Suddenly, the triple tap worked! It didn't work again..
For once it worked, I don't know what is wrong

**Comment by KieronQuinn** [comment]
https://www.xda-developers.com/how-to-take-logs-android/

A system log is what is required, run the command just after trying to run the gesture and nothing happening.

**Comment by saravanasg** [comment]
02-21 02:03:36.758 14093 14093 I AppShortcutAction: Triggering for triple tap
02-21 02:03:36.759  1947  2634 D BatteryStatsService: notePemString  noteWhich: 56,arg1: 8, arg2: 0, arg3: 10315, arg4: 0, name: com.kieronquinn.app.taptap
02-21 02:03:37.240 27443 27610 V CCodec  : watch for 1 codecs
02-21 02:03:38.112  1947  2634 D BatteryStatsService: notePemString  noteWhich: 56,arg1: 8, arg2: 1, arg3: 10315, arg4: 0, name: com.kieronquinn.app.taptap
02-21 02:03:38.112  1947  2634 D BatteryStatsService: notePemString  noteWhich: 56,arg1: 8, arg2: 0, arg3: 10315, arg4: 0, name: com.kieronquinn.app.taptap
02-21 02:03:38.800  1947  2634 D BatteryStatsService: notePemString  noteWhich: 56,arg1: 8, arg2: 1, arg3: 10315, arg4: 0, name: com.kieronquinn.app.taptap
02-21 02:03:38.802 14093 14093 I AppShortcutAction: Triggering for triple tap
02-21 02:03:38.804  1947  2634 D BatteryStatsService: notePemString  noteWhich: 56,arg1: 8, arg2: 0, arg3: 10315, arg4: 0, name: com.kieronquinn.app.taptap
02-21 02:03:38.874 27250 27271 D BinderSender: onUidCachedChanged: uid=10248, cached=true
02-21 02:03:38.874 25299 25299 I GsaVoiceInteractionSrv: Handling ACTION_START_HOTWORD
02-21 02:03:38.874 25299 25334 I GsaVoiceInteractionSrv: (REDACTED) disregardHotwordSetting: %b
02-21 02:03:38.874 25299 25334 I GsaVoiceInteractionSrv: Not starting hotword, hotword should already be running.
02-21 02:03:38.878 24319 24319 V XMPush-24319: [Tid:2] onStart() with intent.Action = com.xiaomi.push.timer, chid = null, pkg = null|null
02-21 02:03:38.879 24319 24408 V XMPush-24319: [Tid:3793] [Job] Handle intent action = com.xiaomi.push.timer
02-21 02:03:38.880 24319 24408 V XMPush-24319: [Tid:3793] [Alarm] Service called on timer
02-21 02:03:38.880 24319 24408 V XMPush-24319: [Tid:3793] [Alarm] register alarm. (false)
02-21 02:03:38.880 24319 24408 V XMPush-24319: [Tid:3793] [HB] ping interval:600000
02-21 02:03:38.883 24319 24408 V XMPush-24319: [Tid:3793] [Slim] SND ping id=0
02-21 02:03:38.920 24319 31825 V XMPush-24319: [Tid:3830] [Slim] RCV ping id=0
02-21 02:03:39.957 27443 27613 D BufferPoolAccessor2.0: evictor expired: 2, evicted: 0
02-21 02:03:40.957 27443 27613 D BufferPoolAccessor2.0: bufferpool2 0xb400006f72f0f7c8 : 0(0 size) total buffers - 0(0 size) used buffers - 1/5 (recycle/alloc) - 4/48 (fetch/transfer)
02-21 02:03:40.958 27443 27613 D BufferPoolAccessor2.0: evictor expired: 1, evicted: 1


Is this it?

**Comment by KieronQuinn** [comment]
If you triggered it twice there, with a couple of seconds delay then yes, that's it. There's no error, so unfortunately I cannot do anything - it's probably an incompatibility with your device's firmware.

**Comment by saravanasg** [comment]
Well I haven't encountered anything like this for doing other actions such as google voice search.
Google voice search open perfectly fine even when i spam double tap every 1 sec

**Comment by KieronQuinn** [comment]
App Shortcuts are done via Shizuku and hidden APIs, they are more prone to issues like this as hidden APIs are not standardised and can be modified by OEM firmwares. There's nothing I can do without actually having access to this device to debug it, sorry.

**Comment by saravanasg** [comment]
Oh, I see.
Thank you for helping :)
