### ISSUE TITLE
Double tap not working on Redmi note 11

### ISSUE THREAD

**Issue by ADMalay001** [KieronQuinn/TapTap#571]
I set a double tap to screenshot. I tried to change the sensitivity, not working. I already enabled Tap, Tap accessibility service, not working. I re-run setup and it said that it feel the tap vibration. I tried tapping again, still not working. I already turned off the MIUI battery optimization, also not working. Please help me

**Comment by KieronQuinn** [comment]
If it worked during setup, but not after, it's #354.

If it's not working or intermittent during setup, all you can try is the different device sizes (models) and sensitivity options. Nothing further can be done.
