### ISSUE TITLE
How to verify that the Native Mode is working as expected?

### ISSUE THREAD

**Issue by BellaCoola** [KieronQuinn/TapTap#573]
Hello, I tried to follow the steps in [this Wiki page](https://github.com/KieronQuinn/TapTap/wiki/Native-Mode:-Manual-Setup) on a Pixel device. I am wondering, how can I verify that the Native Mode is working as expected? Is there some indicator inside of the application?

Thank you very much and have a nice day.

**Comment by KieronQuinn** [comment]
If you enable the option and it's working, then it's functioning as expected. You can also try using it while the screen is off without the display off gate enabled, if it doesn't react then it's definitely working.

Shizuku is not required, that is referring to the Low Power Mode requirements.

**Comment by KieronQuinn** [comment]
That is correct, it would be shown on the settings page if it was supported. What device is this?

**Comment by KieronQuinn** [comment]
> I tried it on Pixel 6a with a custom Android ROM.

That's your problem, many custom ROMs do not have the required files for it to work.
