### ISSUE TITLE
Landscape barrier not working 

### ISSUE THREAD

**Issue by supermegamestre** [KieronQuinn/TapTap#575]
The landscape barrier is not working at all, when I activate it it either blocks all gestures or none regardless of the phone's orientation.

**Comment by KieronQuinn** [comment]
[All it is doing is checking the orientation](https://github.com/KieronQuinn/TapTap/blob/master/app/src/main/java/com/kieronquinn/app/taptap/components/columbus/gates/custom/OrientationGate.kt). If that is not working, then I cannot do anything about that.
