### ISSUE TITLE
TapTap problem with Mui12

### ISSUE THREAD

**Issue by Igimk2023** [KieronQuinn/TapTap#577]
Latest version of TapTap have problem with double tap function it always goes backwards as button when example open notifications it does not open or close the app function ,please fix

**Comment by Igimk2023** [comment]
Why in version 1.0 is working okey but beyond 1.0.1 there is working as backward thanks for support Kieron!

**Comment by KieronQuinn** [comment]
1.0.1 introduced changes to improve notification shade closing on every other device. Not my fault if MIUI doesn't follow the standard.
