### ISSUE TITLE
Double tap still pauses music, even when uninstalled

### ISSUE THREAD

**Issue by F1reP0wer12345** [KieronQuinn/TapTap#580]
I completely uninstalled the app, and yet still double tapping the back of my phone pauses/unpauses my music. I'm NOT using a Google pixel and am running android 12. My phone model is the motorola moto g72. I'm 99% certain this feature didn't come with the device, and now I can't remove it. I tried removing every action and disabling tap, tap as well. Can you help me completely disable this functionality?

**Comment by KieronQuinn** [comment]
[Disable it in the Moto app](https://root-nation.com/en/gadgets-en/smartphones-en/en-motorola-moto-g72-review/#:~:text=A%20double%2Dtap%20gesture%20on%20the%20back%20panel%20activates%20the%20recorder%2C%20but%20you%20can%20assign%20it%20to%20start%20any%20program%2C%20start/pause%20while%20listening%20to%20music%20or%20take%20a%20quick%20screenshot.). This is nothing to do with Tap, Tap.
