### ISSUE TITLE
Unable to enable Accessibility service

### ISSUE THREAD

**Issue by Shahab-Sidd** [KieronQuinn/TapTap#582]
When try to enable Accessibility service, its showing security error stating "for your security this setting is currently unavailable"
![Screenshot_2023-06-25-15-16-26-04_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/KieronQuinn/TapTap/assets/60789263/6b61a063-e28e-405d-adf0-4c1ca24ad9e6)

**Comment by KieronQuinn** [comment]
Go to Tap Tap's app info > Overflow menu > Allow restricted settings

**Comment by kingkongballs** [comment]
Hi, similar issue here and the "Allow display over other apps" fix doesn't work on my phone.

Xperia 1V running android 13.
I'd like double tap to do a screen shot but I'm getting the same restricted setting error as above.

![Screenshot_20231031-024529](https://github.com/KieronQuinn/TapTap/assets/21693227/1538bd88-ffd3-4230-8642-5367128ee85b)
![Screenshot_20231031-024511](https://github.com/KieronQuinn/TapTap/assets/21693227/83130fc2-658c-4d58-b0f7-0541f156c6e0)

Any help would be great, this is a pretty cool feature to have!

**Comment by KieronQuinn** [comment]
> Hi, similar issue here and the "Allow display over other apps" fix doesn't work on my phone.
> 
> Xperia 1V running android 13. I'd like double tap to do a screen shot but I'm getting the same restricted setting error as above.
> 
> ![Screenshot_20231031-024529](https://user-images.githubusercontent.com/21693227/279243867-1538bd88-ffd3-4230-8642-5367128ee85b.png) ![Screenshot_20231031-024511](https://user-images.githubusercontent.com/21693227/279243869-83130fc2-658c-4d58-b0f7-0541f156c6e0.png)
> 
> Any help would be great, this is a pretty cool feature to have!

I already gave the fix for this above, the same applies to all devices.

**Comment by kingkongballs** [comment]
If by "Overflow menu" you mean "display over other apps", it's enabled but still has the same issue, hence the screen shot. If there's something else, it's not in my settings, hence the screen shot.

I'll keep looking though

**Comment by KieronQuinn** [comment]
> If by "Overflow menu" you mean "display over other apps", it's enabled but still has the same issue, hence the screen shot. If there's something else, it's not in my settings, hence the screen shot.
> 
> I'll keep looking though

The Overflow menu is fine three dots in the top right of the screenshot of the app inform

**Comment by kingkongballs** [comment]
> > If by "Overflow menu" you mean "display over other apps", it's enabled but still has the same issue, hence the screen shot. If there's something else, it's not in my settings, hence the screen shot.
> > I'll keep looking though
> 
> The Overflow menu is fine three dots in the top right of the screenshot of the app inform

Got it. Thanks!
