### ISSUE TITLE
Gates not working

### ISSUE THREAD

**Issue by ClassicWonderer** [KieronQuinn/TapTap#583]
Gates feature is non functional tho all permissions are given

![IMG_20230801_211722](https://github.com/KieronQuinn/TapTap/assets/141164605/ecce7f03-3c37-4d38-b417-dfa3216502e0)

**Comment by KieronQuinn** [comment]
Try rebooting your device, see if that fixes it.

**Comment by ClassicWonderer** [comment]
Nope , rebooted , bt still functions when screen is off (I tried turning off aod and then turning off my screen too)

![Screenshot_2023-08-02-07-53-36-73.jpg](https://github.com/KieronQuinn/TapTap/assets/141164605/777bf537-74b4-4bc4-b9d5-1839f85afd32)


This is what it captured☝️

Even when I tried it with the mentioned app (ff max) it still captured scrnshots...

**Comment by KieronQuinn** [comment]
Can you try with a different action, see if it persists with that?

**Comment by ClassicWonderer** [comment]
Sorry for being late , bt the issue seems to exist

**Comment by KieronQuinn** [comment]
But the action does change? I've not a clue what's happening if so.

**Comment by ClassicWonderer** [comment]
I'm sorry 😐, issue doesn't persist when  I change the action

**Comment by KieronQuinn** [comment]
I'm still not understanding. When you change the tap action in the app:
- Does the tap action actually change? Or does it still do the old action.
- Does it make the gates work?

**Comment by ClassicWonderer** [comment]
Yes , it does make the gates work and the action also changes ....

**Comment by KieronQuinn** [comment]
What device and rom is this?

**Comment by ClassicWonderer** [comment]
OnePlus nord 3 5g , with oxygen OS 13.1 Android 13

**Comment by KieronQuinn** [comment]
There's nothing I can really suggest then, sorry. Without physical access to the device to figure out why your phone in particular with this action, but none of the others, doesn't work with the gates, it's impossible for me to fix.
