### ISSUE TITLE
Suggestion: Allow tasker to call Tap, Tap's actions

### ISSUE THREAD

**Issue by AeliusSaionji** [KieronQuinn/TapTap#584]
This is a bit of a awkward request and it's for a selfish reason. Tasker apparently can't invoke the accessibility shortcut/button directly.

I suspect that I am unlikely to get the attention of the Tasker developer, and more likely to solve this problem by asking you to allow Tasker to do this through Tap, Tap.

I completely understand if this isn't something you want to spend time supporting.

Thanks!

https://www.reddit.com/r/tasker/comments/15krh39/have_tasker_trigger_the_accessibility_button/

**Comment by KieronQuinn** [comment]
This is not in scope for Tap, Tap. Sorry.
