### ISSUE TITLE
Can't install on TCL devices

### ISSUE THREAD

**Issue by tiagorangel2011** [KieronQuinn/TapTap#585]
My android TCL device has a gyroscope but it says it doesn't.

**Comment by KieronQuinn** [comment]
The Gyroscope check is the [standard system feature check](https://github.com/KieronQuinn/TapTap/blob/8180c92d78bc8f686426e5a941fb0ce03189b883/app/src/main/java/com/kieronquinn/app/taptap/utils/extensions/Extensions%2BContext.kt#L167). If the device does not declare that it has a gyroscope, but actually does, it is not my problem (complain to them).
