### ISSUE TITLE
Availability of official Android API?

### ISSUE THREAD

**Issue by mohan-aditya05** [KieronQuinn/TapTap#587]
Hi, thanks for this amazing project!

The project description says that it is a `backport` of the `quick tap feature` from Android 12 to Android 7+ devices.

Does it mean that an (official Android) API to detect quick tap is present in Android 12+ versions?

Thanks
Aditya

**Comment by KieronQuinn** [comment]
No, it's only on Pixels, and the API is only accessible by system apps.
