### ISSUE TITLE
Gesture not recognized if Microphone is disabled

### ISSUE THREAD

**Issue by Sonico98** [KieronQuinn/TapTap#588]
I set up TapTap on my phone and everything was working fine. Then, I decided to disable access to the microphone and camera from the quick settings toggles present on Android 12. Some hours later, I tried to use the gesture again and was confused as to why it wasn't working.
Tried toggling the Accessibility service off and on, made sure the battery usage for the app was set as unrestricted, tried disabling and enabling TapTap again, changing sensitivity, and lastly tried reinstalling the app, and it still wouldn't work.
That's when I started to think what was it that I changed on the phone after TapTap was already working, and realized that enabling the Microphone resulted in the gesture working perfectly fine again.

Phone is Motorola G32, Android 12 (stock firmware, which is AOSP-based).

**Comment by KieronQuinn** [comment]
I would assume the microphone sensor privacy stuff in the system is interfering with accelerometer/gyroscope access then. Since this is blocked at the system level, and Tap, Tap doesn't do anything out of the ordinary with it, this isn't something I can fix unfortunately.
