### ISSUE TITLE
Problem with accessibility 

### ISSUE THREAD

**Issue by LucasDRavarotto** [KieronQuinn/TapTap#589]
From one day to the next I got a system notice asking me to activate a restricted setting that I can't find anywhere. The system throws me as an application suspected of data theft, so it blocked the app.
I use double tap to lock my device, it's a Samsung S20FE with One UI 5.1 running Android 13.
![Screenshot_20231009_115711_Accessibility](https://github.com/KieronQuinn/TapTap/assets/71601457/ecfea9ca-cf29-402f-a98d-5a65e0eb7a99)

**Comment by KieronQuinn** [comment]
Go to the app info for Tap, Tap and allow restricted settings in the overflow menu. This is normal, there's no workaround for apps to do.
