### ISSUE TITLE
[UI] Content margin is not equal on each sides

### ISSUE THREAD

**Issue by busybox11** [KieronQuinn/TapTap#59]
As you can see in the following screenshot, the "Actions" content cards do not have the same margin on each sides, the right side is larger.

![Screenshot_20200801-190134_Tap,_Tap](https://user-images.githubusercontent.com/29630035/89106397-d45f8980-d429-11ea-8897-6034ea6f781d.png)

**Comment by KieronQuinn** [comment]
Fixed in 0.10 Beta, this turned out to be an issue with Insetter (joy!) rather than something I was doing, which made it really difficult to track down.

**Comment by busybox11** [comment]
Oh well. Glad you found it! It's been a while lol.
Keep up the good work!
