### ISSUE TITLE
Helping you to help fans for an even much much greater Experience than is

### ISSUE THREAD

**Issue by TechMan205** [KieronQuinn/TapTap#590]
what is up my bro sir dev of this app known by /as the Geat. Tap tap which a truly intelligent hard working guy known as keiron  has brought into existence  for us his own Loyal fans im here to simply Let  You mr tap tap keiron simply just know i fully appreciate his work & i will never stop un less it is given up on cuz its just amazing how up even to this day of it existing for a few years it still is the only app which Lets ppl mimick a special ios & pixel feature i just really find it unbelievable cuz 9/10 usually 1 good app will end up out right spawning a thousand copy with few good & some bad or then many trying to be as good as its original its just how usually it is & it isnt a unknown app cuz i know millions of ppl has this app so very very very far from it but still non is able to come up with a copy by atleast now in 2023  it must be difficult i blieve so it can be why so i just simply gotta appreciate your beautiful efforts entirely 100% Love it as how ever can possibly i not when i know it has did well for so many many many ppl in the world That needs your app & you in general so i wanna come & just express how i feel abt your work cuz the works of a man or a woman is just what ppl shall Always remmmber him or him / them by its Legacy or sometimes Ledgendary in this case it is deffinitly and yk since its name is tap tap i got a dream or a vision for this app which is to really see it grow much bigger although its very very very popular globally/world wide as is already its good to Love your own creation wether a child a product or what ever is how can it be wrong yk hm so what if you added a way to assign buttons in which even if a phone might not own all the right gyro sensors it will still be of great usefulness just as a button mapper cuz its name is tap tap not back tap so its name will not mislead any1 youd expect what youd its features is about i cant help but fall in Love with this idea it will open more doors for this app & stretch further and it will reach as far as it could get & all know its very very very far with finger print Long taps and double taps  aka tap taps regular taps ofc aswel& for exposure it should be added in play store it is a place to find apps very very very easily so it will hit a much much bigger/wider/Larger fanbase it will end up reaching even more multi milions  or even 
 possibly a full billion users ya just never know what can happen if you try making it happen cuz nothing just happens hard work pays off every single time no doubt just keep on working/believing/trying never give up cuz only a Loser will do such a thing cant win a race by collecting rocks from the ground while all runners passes miles beyond you and running laps when you havnt hit your first lap yet yk that feeling in a racing game if you crash hitting what ever is in the way and you see all vehicles comming behind you thinking youre winning but actually thyeyre almost finished running/winning the race while youre stuck in the start dont be that guy

**Comment by TechMan205** [comment]
Level up and watch your app reach heighest of all heights when an app dev is hard working his app will innevitably thrive from the source of his drive to make it big it Levels up with its dev simultaneously if there is a way to make it work on Lesser powered sensors on basic or all phones plz try if its open source and those kinds of apps arnt allowed in playstore uptodown and aptoide will not many can stand a chance against uptodown it has been around for years and more relevent Than ever to a point where it couldnt be more relevant cuz it peaked and maxed out in relevancy so never stop improving your work on this unique app cuz remmember ppl need it cuz non Like it exist or probably ever will so think

**Comment by KieronQuinn** [comment]
This is a huge block of text but thanks for your support, I'll answer a couple of questions:

- Tap, Tap is not allowed on Google Play (this has been answered a few times). It's available [unofficially on F-droid](https://android.izzysoft.de/repo/apk/com.kieronquinn.app.taptap) though.
- The device requires a gyroscope or the gestures cannot work.
- Low power options are already available, if they do not work with your device then nothing can be done.

**Comment by TechMan205** [comment]
well i know it simply had to be in a very big sort message cuz as we all do
know it aint everything which can be said or expressed in a simple fashion
kind of way its how many ppl does things & i know it isnt allowed in play
store cuz foss apps arnt allowed in playstore but if you made it closed in
which only you can make edits or changes to it yes it can be placed in play
store easily it doesnt need to be open for everyone to edit we just need to
use it for what it does it is the only app which gives ppl the ability that
iphones and pixels has has aka back tap gestures i am here to try to help
you in Leveling up your game as a fan its my job really tbh has How can i
watch Looking on seeing a guy who im a fan of fails when i got all my
knowledge to just help him to win and succeed in his Life id not be a fan
if i ever did such a terrible thing Now will i sharing is caring alota ppl
will come and will so very gladly bash you and the app just for having
imperfections but i will not as much prefer comming up with a way/solution
of what is its flaw and why its a flaw and finally how to fix said flaw
everything has a flaw so id never bash my idol or a favorite thing in my
case an app for it i can help so i will try to do so

**Comment by KieronQuinn** [comment]
FOSS apps are allowed on Google Play. This app uses reverse engineered code and would get me banned. Simple as that.

**Comment by TechMan205** [comment]
well id say the best #1 place for it is gonna be uptodown which is point
blank and period as we all know pretty much nothing beats up to down except
for play store cuz play store is king of all aptoide is fairly cool too and
apkpure is on par with uptodown and apk mirror is very popular it self
gotta spread it in everywhere it can go where if so it reaches as many ppl
as it could top youtubers with a big platform and fanbase do reviews of
this app so alota ppl knows it and is where i found it from they has
promoted and has referred many plz add button mapping for keys and for a
fingerprint sensor it is if a person installing it he or shouldnt wouldnt
be fully dis appointed cuz it would still be useful cuz id say most phones
wont and dont come with that kind of sensors it will need as far as i can
tell but with remapper it will still be capable of doing something and
something is always much greater than nothing at all if this happens i can
donate up to a hundred

**Comment by KieronQuinn** [comment]
I'm not uploading to other stores, as I've said. And what you're suggesting about remapping other buttons is way out of scope for this app. 

I don't need help to further publicise this app, sorry.

**Comment by TechMan205** [comment]
bro Let us not be stubborn its about a cause not just me or you
individually but other ppl That need your app i did say before as its name
is tap tap it wouldnt be a far fetched idea at all cuz you can double tap a
button aswel it will be just an extra feature its main will be back tap
Like a ps vita...........?

**Comment by KieronQuinn** [comment]
No, it's out of scope. End of discussion.
