### ISSUE TITLE
Accessibility permission issue 

### ISSUE THREAD

**Issue by Ks8430** [KieronQuinn/TapTap#591]
I am not able to give accessibility permission to the Tap tap . 
![Screenshot_2023-11-26-23-38-17-89_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/KieronQuinn/TapTap/assets/76089706/36449226-6f9f-42d7-9eac-f7afc5344b78)
W
![Screenshot_2023-11-26-23-38-10-37_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/KieronQuinn/TapTap/assets/76089706/ec06fe4e-858b-4891-aae3-bd82ab5f643d)
When I am clicking on the tap tap option then it is showing that restricted due to security reasons .

**Comment by KieronQuinn** [comment]
#582

**Comment by Ks8430** [comment]
> #582 

Got it bro.
Thanks very much.
