### ISSUE TITLE
Please support non-portrait screen orientations

### ISSUE THREAD

**Issue by tkuenneth** [KieronQuinn/TapTap#594]
Hello.

When I run the app on my Surface Duo using Android 14, the screen looks like this:

![image](https://github.com/KieronQuinn/TapTap/assets/13284437/82a56528-2649-4f2c-8007-426f41410ddf)
![image](https://github.com/KieronQuinn/TapTap/assets/13284437/a1735392-79d9-4a96-9cf8-dbbb820412ef)

The reason for the behavior is a setting in the manifest:

```xml
  <activity
      android:name=".ui.activities.MainActivity"
      android:screenOrientation="portrait"
```

This locks the orientation to, well, portrait. Setting it to `unspecified` implies that the app doesn't care about the screen orientation, which is the best approach if the ui looks good in non-portrait.

I applied the change and looked at quite a few screens of the app, and all seemed ok. It would be awesome if you consider applying the change. So far I have not created a pull request, but if this helps, I am certainly more than happy to create one. Thank you very much for the Incredible job you are doing.

**Comment by KieronQuinn** [comment]
Orientation is unlocked in 1.6.2 - it's not perfect in many places so use at your own risk, but it should work on a large screen.
