### ISSUE TITLE
Notification Shade Annoyance.

### ISSUE THREAD

**Issue by CoolCrescent186** [KieronQuinn/TapTap#596]
On my Motorola G100, (and I'd assume more devices), the open/close notifications works well, except when I wake the device up while not interacting with the lock screen at all. Fingerprint straight into OS. I can feel the vibration, but the notification shade doesn't open. The moment I interact with the Notification Shade, this issue goes and stays away until I unlock my phone again. Is this just a limitation with Android, or something which can be fixed?

**Comment by KieronQuinn** [comment]
It's an Android limitation, I have no control over whether the shade actually opens.

**Comment by CoolCrescent186** [comment]
Is there an ADB command that can force-open the notification shade that might require Shizuku? A compatibility mode, perhaps?

**Comment by KieronQuinn** [comment]
There's no way for it to know if the shade is open, that's the problem. It already thinks it's open, so sends a "close" request instead, opening the shade updates syncs it back up again. Shizuku can't help here unfortunately.

**Comment by CoolCrescent186** [comment]
Perhaps a conpatibility mode that always sends an "open" command every time the screen is turned off and on?
