### ISSUE TITLE
Low power mode requires one extra tap when Triple Tap is enabled

### ISSUE THREAD

**Issue by radugrecu97** [KieronQuinn/TapTap#597]
I'm using Pixel 5. If I have low power mode enabled and allowed on Sui, double tap works just fine as of native Pixel double tap.

But once I enable Triple Tap, then double tap requires 3 fast taps to activate or 2 with large delay.

Triple Tap requires fast taps.

What can it be?

**Comment by KieronQuinn** [comment]
Low Power Mode receives events direct from the system, the difference between double tap and triple tap is the event monitoring is different; there's an event specifically for single and double taps but not triple taps, so it has to check these single tap timings to detect triple taps.

It's possible the system is not reporting all the single tap events if they're not spaced out enough, unfortunately I have no control over this.
