### ISSUE TITLE
Update Tasker Icon

### ISSUE THREAD

**Issue by etyarews** [KieronQuinn/TapTap#598]
I presume the Tasker icon used inside Tap, Tap was something made for Tap, Tap. At the time Tasker didn't have an official monochrome icon, this changed with the lastest icon.

I'm the designer of the new icons, and here's the 24dp monochrome version as a SVG, it was made to fit with other material icons.

![tasker121](https://github.com/KieronQuinn/TapTap/assets/113912802/5ef7e48a-a268-4ac7-8fa7-3cb0ad049458)

**Comment by KieronQuinn** [comment]
Added in 1.6.2, thanks!
