### ISSUE TITLE
Tap tap not working on big screen device 

### ISSUE THREAD

**Issue by SeanDylan** [KieronQuinn/TapTap#600]
Im using a big screen device and despite having a geo sensor it's not working

**Comment by KieronQuinn** [comment]
If it doesn't work during setup, there's nothing I can do. Just make sure you've tried all the combinations of device sizes and sensitivity, beyond that it's probably a device or hardware incompatibility.

**Comment by ZeusOfTheCrows** [comment]
this might not be a hardware compatibility issue. i've just bought a tall phone (6.5", but 21:9 so it's) and i can only get it working with pixel 4 xl (6.3") and sensitivity set to max, or tapping near the top of the device. perhaps a larger device model option would solve this

sidenote: i couldn't make custom sensitivity work, as i have no idea what values it expects (tried 1.0, 99, 999, & 65535) - probably a hint for the order of magnitude would be helpful

**Comment by KieronQuinn** [comment]
> perhaps a larger device model option would solve this

I don't make the models.

**Comment by ZeusOfTheCrows** [comment]
oh okay, i assumed the model was just a ux representation of some sensitivity and/or vertical centre offset variables. where do they come from?

also, what should i put in the "custom sensitivity" box as equivalent to the highest value on the slider?

**Comment by KieronQuinn** [comment]
> oh okay, i assumed the model was just a ux representation of some sensitivity and/or vertical centre offset variables. where do they come from?
Google made them, this app is a port of that feature.
> also, what should i put in the "custom sensitivity" box as equivalent to the highest value on the slider?
You can find what the slider values for the regular setting map to here: https://github.com/KieronQuinn/TapTap/blob/8180c92d78bc8f686426e5a941fb0ce03189b883/app/src/main/java/com/kieronquinn/app/taptap/components/columbus/sensors/TapTapGestureSensorImpl.kt#L41, and decide yourself what to set the custom one to.

**Comment by ZeusOfTheCrows** [comment]
> Google made them, this app is a port of that feature.

ah okay, that makes sense

> You can find what the slider values for the regular setting map to here: […]
, and decide yourself what to set the custom one to.

that's helpful, thank you!
