### ISSUE TITLE
Dont work on Emui 14.2

### ISSUE THREAD

**Issue by AhmedsBanna** [KieronQuinn/TapTap#604]
It was ok on Emui 13.1
But after i update p60 pro to Emui 14.2 taptap cant found sensor

**Comment by AhmedsBanna** [comment]
Can any one help to solve problem for huawei Emui 14.2

**Comment by KieronQuinn** [comment]
If it's showing the no gyroscope message, then your device is not exposing the sensor to apps. Contact Huawei.

**Comment by AhmedsBanna** [comment]
No message as that

**Comment by AhmedsBanna** [comment]
Also i have tested gyroscope on asphalt
It was ok
