### ISSUE TITLE
Gesture tracking should pause when Gates conditions are not met

### ISSUE THREAD

**Issue by DrSapling** [KieronQuinn/TapTap#607]
Gesture tracking should pause when Gates conditions are not met. This would reduce battery drain.

In my case I have ```Double Tap Action``` for ```Flashlight``` without any requirements.
For ```Gates``` I have ```Lock Screen not showing``` and ```Screen off```.
Even though I rarely use the gesture and am not on the lock screen very often, the app still uses 5-10% of the battery (4200mAh).

My suggestion is to prevent gesture tracking if all Gates conditions are not met, or at least have an option to pause tracking when the device screen is off.

**Comment by KieronQuinn** [comment]
This already happens where possible. Read the battery & optimisation page: https://github.com/KieronQuinn/TapTap/wiki/Battery-and-Optimisation
