### ISSUE TITLE
Restricted Setting 

### ISSUE THREAD

**Issue by KamalSDhami** [KieronQuinn/TapTap#608]
i am using OnePlus 9 5g, and i am on Android 14, when i go in accessibility it don't let me give permission to app, it show restricted setting for your safety.
![Screenshot_2024-08-11-17-13-45-41_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/user-attachments/assets/0b808ad8-a5cc-4420-8570-c4f15c83885c)
![Screenshot_2024-08-11-17-13-43-03_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/user-attachments/assets/e635d12a-7bf1-4a6d-8dc9-586ec981702e)

**Comment by KieronQuinn** [comment]
#582
