### ISSUE TITLE
Splitscreen not working

### ISSUE THREAD

**Issue by inkassso** [KieronQuinn/TapTap#617]
Splitscreen action doesn't work. I've configured the action on triple tap (with no conditions and no gates) and when I attempt to do so while having an app open, I only get the confirmation vibration, but splitscreen is not opened. Activating splitscreen manually (in my case swipe up from the bottom edge with both fingers) works as intended in all the apps I've tried so far (e.g. Chrome, the Tap, Tap app etc.).

I never got it working even on my older Samsung Galaxy A51 (Android 13, OneUI 5).
The Feature says it's using the accessibility service which I have it enabled (both of them actually). I verified it's running by choosing another action using the service (screenshot) and confirmed that works as intended.

To reproduce the issue:
1. Open the Tap, Tap app
2. Configure splitscreen to be activated on e.g. triple tap
3. Go back, exit and close the app and relaunch it to apply the settings (see #616)
4. Open an app supporting splitscreen
5. Triple tap to activate splitscreen
6. Notice the vibration confirming the action, but no splitscreen is opened

Environment:
- Device: Samsung Galaxy S23 Ultra (EU)
- Android version: 14 (OneUI 6.1)
- App version: 1.6.2
- Accessibility services: Turned on, both
- Battery optimization: disabled for the Tap, Tap app (without limitation)
- System battery saver: disabled when testing

**Comment by KieronQuinn** [comment]
#508
