### ISSUE TITLE
Tap Tap Service crashed

### ISSUE THREAD

**Issue by inkassso** [KieronQuinn/TapTap#620]
I received a notification about the service crashing.
Afaik I wasn't performing an action, but I haven't found the right sensitivity setting yet and sometimes the tap action is detected when I don't want it to, so I can't be sure really. In either case, there was no vibration confirming the action.

Here's the crash report generated by the app:
[tap_tap_crash_report_2024-11-10T22_46_11.142.txt](https://github.com/user-attachments/files/17693180/tap_tap_crash_report_2024-11-10T22_46_11.142.txt)

**Comment by KieronQuinn** [comment]
#482 although it is interesting you're hitting it when changing settings 🤔

**Comment by inkassso** [comment]
Sorry for the duplicate, didn't check the closed issues.

I'm not changing it daily, I adjust it and live with it for a week or two, last time I adjusted was cca a week ago. I'll just restart the phone and see if it happens again sometime soon.
