### ISSUE TITLE
Can't enable Tap Tap in Accesibility

### ISSUE THREAD

**Issue by Publicitytop** [KieronQuinn/TapTap#622]
The access is not restricted, but the switch just refused to turn on even though I allowed it

android 15 
Oppo 
![Screenshot_2024-12-08-11-08-03-11_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/user-attachments/assets/ab30baaf-49a2-455c-adf4-ba0f661a8682)
![Screenshot_2024-12-08-11-08-00-69_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/user-attachments/assets/04cfec05-9fba-45dc-97aa-031fcd272bad)
Color os 15

**Comment by KieronQuinn** [comment]
Are you sure it's not a restricted permission issue? OEMs don't have to use the same behaviour so it wouldn't surprise me if it's the same.

If not, there's nothing I can do since this is a system setting.

**Comment by Publicitytop** [comment]
It is indeed permission problem.

After trying everything, the solution is simple. Just sideload the app using app installer such as https://play.google.com/store/apps/details?id=com.lb.app_manager and you're good to go
