### ISSUE TITLE
Feature Request: frame tap Detection for Custom Functions

### ISSUE THREAD

**Issue by Pankaj-Meharchandani** [KieronQuinn/TapTap#623]
suggestion:
This app can easily differentiate between taps on the device frame and back panel. 
Is it possible to add a feature to sense vibrations coming from different sides of the frame and assign functions accordingly? 

For example, double tap on the left side of the device frame for the previous track and on the right side for the next track. 

I don't know if it's possible, but if it is, please give it a try.

**Comment by KieronQuinn** [comment]
Not possible since I didn't make the recognition model.
