### ISSUE TITLE
Feature request: Have 'toggle notification shade' as well as 'open notification shade'

### ISSUE THREAD

**Issue by adendiamond** [KieronQuinn/TapTap#67]
I think this would be cool. Love the app by the way.

**Comment by KieronQuinn** [comment]
There's no API to know when the shade is expanded, so this isn't possible.

**Comment by ChildishGiant** [comment]
When opening the shade does whatever method have a callback or something of the sort to see if it fails? I feel like there must be a way to do this.

**Comment by KieronQuinn** [comment]
Nope. Even if it did it would be prone to state changes outside of the app that would leave it out of sync. For this to be possible, there needs to be either a synchronous check for "is panel open" or a way to listen for it opening and closing.
