### ISSUE TITLE
MIUI seems to kill the app despite disabling battery optimization

### ISSUE THREAD

**Issue by devmrfitz** [KieronQuinn/TapTap#71]
I'm running MIUI 11 with Android 9 on Redmi Note 5 Pro. The app seems to get killed off once I lock the screen and has to be manually relaunched.

Possible fix:
Apps like Tasker hold themselves in the memory by using a persistent notification. Something similar might be helpful here

**Comment by Martin5001** [comment]
Just for your information: there are some steps which could help https://dontkillmyapp.com/xiaomi, but it needs to be done manually.

**Comment by shivangchopra22** [comment]
Try this:
Open the app, open the accessibility settings through the app, and enable/disable and re-enable the accessibility service. Then restart the phone. If it still doesn't work, then open and close the app, go to accessibility settings, and enable/disable and re-enable the accessibility service. I'm assuming you've disabled battery optimization, locked the app in recents, enabled autostart, and set the battery saver to no restrictions

**Comment by KieronQuinn** [comment]
Please try with the new update, specifically trying one or both of the new advanced options.

**Comment by devmrfitz** [comment]
Seems much more stable now
