### ISSUE TITLE
Play/Pause

### ISSUE THREAD

**Issue by Andriy2** [KieronQuinn/TapTap#76]
Sometimes this Action doesn't work for Spotify Connect and Netflix when casting to Google Home/Chromecast.

Start working with Spotify Connect only if stop playing, switch to device, switch to Google Home again.

Google Pixel 4
Android 11 Beta 2.5

**Comment by KieronQuinn** [comment]
The Play/Pause action triggers system code, which behaves the same as a headset button. I know first hand (from getting very annoyed at it) that Spotify Connect does not play well with headset buttons, and will sometimes refuse to start playing once paused and the system decides to kill spotify (it also happens the other way round if you try to play on your PC from a phone that has stopped playing music a few seconds ago, but the system has killed it).

Unfortunately this means there's nothing for me to fix, I can't change system code.

**Comment by Andriy2** [comment]
Ok, thank you for explanation!
