### ISSUE TITLE
Draining battary, heating device and gates not working

### ISSUE THREAD

**Issue by bhaskar452** [KieronQuinn/TapTap#88]
This application is draining battary and heating my device(Redmi note 9s Indian variant) very much.
I set it for locking screen. But when I am typing something or forwarding video by dable tap on screen my screen goes off.so,I creat a gate for whatsapp but the gesture is still working on whatsapp.
Do something.... @KieronQuinn 
Otherwise this application is a really great application and I really loves it's UI.

**Comment by mjdwyc** [comment]
It's draining battery on my Note 9 Pro (global) too.

**Comment by sotakoira** [comment]
Same thing on Xiaomi Mi A3, hit 6 hours of SOT with TapTap installed and with power off gate enabled, after uninstalling I'm on 7h30m sot with 40% battery left atm.

**Comment by KieronQuinn** [comment]
Post rewrite, the app is now as efficient as it can be. Possible Android 12 will improve this, especially if the feature makes it to the release this time, but I've done as much as I can.
