### ISSUE TITLE
Not working correctly on Honor 10 lite 

### ISSUE THREAD

**Issue by erfanr** [KieronQuinn/TapTap#92]
It works but I have to try several times (different locations sometimes and sometimes by doing more than 2 taps)
I am running android 10.
Also I am ready to help if you want to send a test version or something (I am just a noob in android development so I don't know what to say :) )

**Comment by KieronQuinn** [comment]
Try changing the gesture model. If it's working sometimes, it's doing the best it can on your device with those models.
