### ISSUE TITLE
No or delayed response on screen off

### ISSUE THREAD

**Issue by rahim21** [KieronQuinn/TapTap#98]
Works fine on screen on 
Gone back to 2.0 issue doesn't exist

**Comment by KieronQuinn** [comment]
Have you disabled the screen off gate?

**Comment by rahim21** [comment]
Yes

**Comment by KieronQuinn** [comment]
What device & android version?

**Comment by rahim21** [comment]
Galaxy A50 , android 10

**Comment by KieronQuinn** [comment]
Try disabling battery optimization for the app, that apparently helps on Samsung devices

**Comment by rahim21** [comment]
Still no deference .. when screen on gate is on this issue happen, no response on screen off ...works fine with no gates on 
So I think this issue has to do with gates

**Comment by KieronQuinn** [comment]
I'm not following, please send a screenshot of which gates you have enabled

**Comment by rahim21** [comment]
![Screenshot_20200804-122957_Tap, Tap](https://user-images.githubusercontent.com/69078834/89288897-49130d80-d64e-11ea-9496-83434a97de06.jpg

No response when screen turned off on this setting

**Comment by KieronQuinn** [comment]
And it works if you disable the screen on gate?

**Comment by rahim21** [comment]
Yes

**Comment by KieronQuinn** [comment]
Sounds like the screen on gate isn't working properly on your device then. If you enable the screen off gate, does that behave as it should, working when on and not when off?

**Comment by rahim21** [comment]
Yes works fine ..i just retested and everything seem to work fine now maybe it was just my device system .. anyway thank you for your kind help.
Just one more thing will triple tap feature come in future updates ?

**Comment by KieronQuinn** [comment]
Possibly, there's already another ticket for that #3
